### ISSUE TITLE
catt will break with next pychromecast release

### ISSUE THREAD

**Issue by theychx** [skorokithakis/catt#12]
Upstream has removed `get_chromecast` from pychromecast, see https://github.com/balloob/pychromecast/commit/dac71620f6faa22a2da79a2432eb9126f30292e1.
So we need to either freeze the pychromecast requirement or implement auto-discovery filtering ourselves. I can do a PR for either, if you are interrested.

**Comment by skorokithakis** [comment]
Hmm, how does filtering work now? Does it return all Chromecasts and you select one? If so, that would be pretty easy to add, no? That would probably be my preference.

**Comment by theychx** [comment]
There is only `get_chromecasts` left, so no filtering.

**Comment by skorokithakis** [comment]
Ah, right. Filtering should just be a one-liner though, no? I don't have multiple Chromecasts, so I'm not familiar with how filtering worked, I'm afraid.

**Comment by theychx** [comment]
I'll work something out

**Comment by skorokithakis** [comment]
This should be resolved with #11, right?

**Comment by theychx** [comment]
Yep

**Comment by theychx** [comment]
I'm reopening this, as pychromecast 0.8.0 is out, and catt is no longer working properly. The new issue is not related to what we already discussed (get_chromecast), but rather with how `play_media` now works internally.
Please see https://github.com/balloob/pychromecast/issues/151.
The problem with `block_until_active()` is that it is implemented in such a way, that it is blocking until `media_controller` is actually playing something. That means we can't use it in `CastController.init`. And as described in the pychromecast issue, this method call is now needed to make `play_media` work properly. 
I'll discuss this with the pychromecast people. In the meantime I can make a PR with a freeze on requirements, if you like.

**Comment by theychx** [comment]
We could also just hotfix it, and just add `self.cast.media_controller.block_until_active()` to `CastController.play_media`. That seems to work ok, but not super-reliably.
And besides, I never liked the `time.sleep(0.2)` in `CastController.init`. There should be a way of making shure everything is ready, without waiting an arbitrary amount of time.

**Comment by skorokithakis** [comment]
Hmm, I think a freeze on the requirements will be better for now, until we can figure out how to fix the problem for good, thank you.
