### ISSUE TITLE
Unable to seek file

### ISSUE THREAD

**Issue by teromene** [skorokithakis/catt#130]
When playing video files (I tried ```video/mp4``` files), using any of the command ```seek```, `ffwd` or `rewind` causes the chromecast device to restart the playback from scratch.
From what I managed to gather, it seems that the media server should implement `http progressive download` for the chromecast to be able to seek properly

**Comment by theychx** [comment]
Thanks for reporting.
Yes, this is indeed annoying. I've done a bit of quick research, and have not been able to find prior python implementations of this.
@skorokithakis, any ideas?

**Comment by skorokithakis** [comment]
Unfortunately I'm not aware of anything supporting this. I thought it would be done with the `Range` header, but of course clients can't know the actual byte range if the media is VBR-encoded, so the server actually uses seconds.

Here's how it works with nginx, the client sends a query string parameter with the seconds it wants:

http://nginx.org/en/docs/http/ngx_http_mp4_module.html

I think the server needs to be media-aware to do this, and seek to the nearest i-frame and continue serving from there, so I don't think this will be very easy to implement :/

**Comment by Konubinix** [comment]
FYI, I just found out that a twistd web server manage to handle the seek instruction.
Now, I first run the command `/usr/bin/twistd3 -n web --path . --port tcp:9999`, then `catt cast http://<myaddress>:9999/myvideo.webm`

I suggest to take a look at twistd and maybe using it to serve the content.

**Comment by teromene** [comment]
Another solution that works and that is really lighter https://github.com/danvk/RangeHTTPServer

**Comment by theychx** [comment]
I can confirm that it is working. @teromene Thanks!

**Comment by theychx** [comment]
@skorokithakis Are you going to have a go at this?

**Comment by skorokithakis** [comment]
Ah, yes, sorry, this escaped my attention. I'll try it now.

**Comment by skorokithakis** [comment]
I've implemented this in #140, can you guys test it and let me know if everything is okay? I'm not 100% certain it's bulletproof.
