### ISSUE TITLE
Typo in readme command write-config

### ISSUE THREAD

**Issue by KimOlsson** [skorokithakis/catt#131]
On [readme](https://github.com/skorokithakis/catt) page it says that you need to run this line in order to write to config file:
`catt -d <name_of_chromecast> write_config`
**write-config** (with a dash) is how it probably is supposed to be, at least it is so on my Windows 10 installation.

Thank you very much for writing this program! It's awesome 👍

**Comment by theychx** [comment]
You're right. Thank you for reporting this!

**Comment by theychx** [comment]
@KimOlsson This was actually not a typo, but rather caused by a change in behaviour in one of the libraries we use. So the name is back to ```write_config```, as of ```0.8.1``` (just released).
Sorry for the confusion!
