### ISSUE TITLE
Add better API documentation

### ISSUE THREAD

**Issue by skorokithakis** [skorokithakis/catt#135]
I use catt in other programs for easily casting URLs to a device. It might be worth thinking about adding a stable API at some point, for the benefit of people who want an easier layer over PyChromecast. For now, I think we should at least add a moderately detailed docstring to the `DefaultCastController` so people can at least know what valid values are for the parameters.

What do you think, @theychx? Would the best way be to use `setup_cast` and then call `play_media_url`, or use a controller directly, or what?

I think what I'm trying to say is that it would be worthwhile if we drafted a high-level overview document to make the internals of catt more accessible to contributors, to make their lives easier.

Thoughts?

**Comment by theychx** [comment]
I'm sympathetic towards all of what you are saying, although I do not think that the time is ripe to provide a stable API. In a next-6-months perspective, there's still some new stuff I'd like to implement, mostly new YouTube functionality.
I definitely think that the standard approach to using ```catt``` as a library, should be to use castcontrollers and ```StreamInfo``` directly. I intended ```setup_cast``` to be the function where the magic happens, in the context of conventional use of ```catt```. I also predict that ```setup_cast``` is going to keep mutating in the foreseeable future.
But yeah, I can definitely see users wanting to use ```catt``` as a library benefiting from detailed docstrings in both ```StreamInfo``` and ```CastController``` :smiley: , so I'll put that on my todo list.

**Comment by skorokithakis** [comment]
Yeah, maybe a stable API is a big thing to ask, but maybe an unstable API would be nice. I'm currently using `setup_cast` in my scripts, just because it was the first thing that worked. We should at least come up with enough documentation to point people to what they should use, I guess.

**Comment by theychx** [comment]
A well-documented unstable API sounds great to me.

**Comment by theychx** [comment]
Some of stuff in ```setup_cast``` might be useful for catt-as-a-library users, we could put that in its own function.

**Comment by skorokithakis** [comment]
Yeah, that makes total sense to me.

**Comment by theychx** [comment]
After your comments about using ```catt``` as "an easier layer over PyChromecast", I gave things a bit of thought. I'm now in the process of splitting ```setup_cast``` into several parts (almost completed). I've also reworked the media-listener in such a way that a ```wait_for_playback_end``` method and other  conveniences are possible.
And yes, I changed my mind about using castcontroller / streaminfo directly. :smiley: 
This new project is probably going to need multiple additional PR's, so maybe you could make a new "develop" branch or the like, so master is stable for as long as possible.

**Comment by skorokithakis** [comment]
That sounds good to me. Also, do you think this project provides enough additional functionality over PyChromecast that putting effort into this (Sphinx documentation, clean API, etc) would be useful? Or should we just make the internal API a bit cleaner and add a few docstrings?

**Comment by theychx** [comment]
> putting effort into this would be useful?

Not initially, but I definitely think that a lot of people who are interested in tinkering with PyChromecast, would appreciate something that is very-high level. So if usage picks up momentum, then yes.

**Comment by skorokithakis** [comment]
That sounds like a good compromise. I like Sphinx because it's basically free once you have good docstrings, and then you can extend it as much as you want, all the way to custom pages that link to the code, as in [this library I made once](https://stringphone.readthedocs.io/en/latest/protocol.html).

**Comment by theychx** [comment]
@skorokithakis Has this been resolved, in your view?
I haven't forgotten about the Sphinx stuff, and I'll properly dive into that, once the api is a bit more complete (feat. more ytdl niceties etc.)

**Comment by skorokithakis** [comment]
Yes, I think it's pretty much done. I think the `ctrl` methods could be renamed (is it the verb "control"? Is it "controller"? If the latter, why is it not "ctrlr"? Etc), as we can afford the extra characters, and private methods could be docstringed as well, but the public-facing stuff is pretty complete. Thanks for all your hard work on this!
