### ISSUE TITLE
Minor API changes

### ISSUE THREAD

**Issue by skorokithakis** [skorokithakis/catt#152]
Hey @theychx, I tried to use the API again and found a few omissions:

1. We should probably expose the `_cast` property, so the consumer can read the IP address, name, etc.
2. I think we should rename `ctrl` to `control` or `controller`, whichever it is.

What do you think?

**Comment by skorokithakis** [comment]
Actually, I think we should proxy the properties and expose a better API for the `pychromecast` devices, i.e. add proxy properties for its fields onto the `CattDevice`.

**Comment by theychx** [comment]
> I think we should proxy the properties

I agree. ```CattDevice``` already exposes name and ip-adress (```_create_cast``` updates those attributes with the data from the ```Chromecast``` object).

One of these days, I'll make a PR with the renaming of ```ctrl``` to ```control```. Any additional info from the ```Chromecast``` object you think would be useful as ```CattDevice``` attributes, I can include such changes in that PR.

**Comment by skorokithakis** [comment]
I'm just about to push it now, although I missed the exposed name and IP, looking for those now.
