### ISSUE TITLE
certificate issue casting youtube

### ISSUE THREAD

**Issue by willzeng** [skorokithakis/catt#165]
Hi there! Thanks so much for this project!

I'm able to `cast_site` successfully but casting returns the following error. For example when I run the README example:
```
$ catt cast "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))
Error: Remote resource not found.
```

Some details:
- Operating System: macOS 10.14.2
- catt was installed with pip3

I tracked this error down as something that has also occured in `youtube-dl` [[github issue](https://github.com/rg3/youtube-dl/issues/4816)]. I separately installed `youtube-dl` and got the same certificate error and then added the suggested workaround (adding the flag `--no-check-certificate` to the `youtube-dl` command) which then worked to download the video. Adding this in case it helps in some way.

**Comment by skorokithakis** [comment]
Ah, this appears to be an issue with youtube-dl. Just pass the youtube-dl option to catt with `catt cast -y` and it should work.

**Comment by benmargolin** [comment]
Would it be possible to get an example commandline? I've tried every variant I can think of and can't get catt to accept/pass through this option.

For example,
`catt -d "Office Home" cast --ytdl-option --no-check-certificate' <url>`
seems like it should work but gives:

> Error: Invalid value for '-y' / '--ytdl-option': --no-check-certificate is not a valid key/value pair.

and trying to "fake it" with things like "--no-check-certificate=1" doesn't work (but doesn't give the same error, either).

Stumped as to how to format unary flags through -y in catt!

**Comment by theychx** [comment]
@benmargolin You need to use `youtube-dl`s [internal option names](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/__init__.py#L317). This really should be in readme.
```
catt -d "Office Home" cast -y "nocheckcertificate=true" <url>
```

**Comment by skorokithakis** [comment]
Good call, I've added that. Thanks to both of you!
