### ISSUE TITLE
Please add a version option

### ISSUE THREAD

**Issue by ArtBIT** [skorokithakis/catt#176]
Please add a version flag to the list of cli options for getting easier information about the current release version:
```
catt --version
```

**Comment by skorokithakis** [comment]
Done, thanks!

**Comment by theychx** [comment]
@skorokithakis 
> Winter Waterfall

:rofl: :rofl: :rofl:

**Comment by skorokithakis** [comment]
https://www.youtube.com/watch?v=L0MK7qz13bU

**Comment by theychx** [comment]
I get to choose the next version codename, and trust me, it's going to be silly. Like, Ubuntu silly.

PS: I was unable to extract any subliminal messages from the video you linked to, but then again, I'm pretty dumb.

**Comment by skorokithakis** [comment]
Who said we're changing it every version, or, indeed, ever?!

**Comment by skorokithakis** [comment]
The video was just winter-waterfall-themed :P

**Comment by theychx** [comment]
> Who said we're changing it every version, or, indeed, ever?!

Party pooper :cry:

**Comment by skorokithakis** [comment]
Actually, we can start picking release names if you want to, it just felt like too much work :stuck_out_tongue: Let's alternate, I'll take odd (starting with this 0.9.3, Winter Waterfall), you take even.

The rules are:

1. They have to alliterate.
2. They can't be serious.
3. Starting with the next letter from the previous release would be nice.
