### ISSUE TITLE
rtsp support

### ISSUE THREAD

**Issue by Breakerz** [skorokithakis/catt#179]
catt is a gem! thx a lot.
I will use it in my home automation. I am using Home Assistant maybe I will try to integrate catt with it, with a customs component or addon. 

I able to cast video from  "[Android IP Webcam app"](https://play.google.com/store/apps/details?id=com.pas.webcam ), with the build-in webserver in the app. Great! 

I have others cam, streaming RTSP flux. I try to cast it, but i got this error 
`ERROR: Unable to download webpage: <urlopen error unknown url type: rtsp> (caused by URLError('unknown url type: rtsp',))
`
The flux should be convert in a format compatible for the ChromeCast I guest... maybe it's something catt can do on the fly ?

**Comment by skorokithakis** [comment]
Thanks for your kind words! We don't currently aim to support stream conversion, catt aims to strictly cast files that the device can already play.
