### ISSUE TITLE
Traceback ERROR

### ISSUE THREAD

**Issue by Lipsck** [skorokithakis/catt#183]
Traceback (most recent call last):
  File "/usr/local/bin/catt", line 7, in <module>
    from catt.cli import main
  File "/usr/local/lib/python2.7/dist-packages/catt/cli.py", line 7, in <module>
    from pathlib import Path
ImportError: No module named pathlib

What can I do to fix this?

**Comment by theychx** [comment]
Are you the same person who just opened a nearly identical ticket? Really?

Like I said: You need Python 3 in order to use `catt`.
There's also a [readme](https://github.com/skorokithakis/catt/blob/master/README.rst).

**Comment by skorokithakis** [comment]
Maybe we should add an if check to not run on 2, although it shouldn't be able to be set up anyway.

**Comment by theychx** [comment]
> although it shouldn't be able to be set up anyway

Yeah, thats odd.

**Comment by skorokithakis** [comment]
I'm guessing they just cloned the repo and tried to run.
