### ISSUE TITLE
Scrubber interface?

### ISSUE THREAD

**Issue by alexyuriev** [skorokithakis/catt#184]
Hi there,

I was wondering if anyone is aware of either a CLI or web/gui based scrubber for catt. If not, I could probably write one fairly quickly but I would like to see if you folks could formalize some sort of a protocol that would allow a different application to request catt to issue a seek command to relative or absolute time position in 1s increments.

I realize that catt itself may not be aware of a playback position immediately or being able to switch a position immediately but it seems the information is available in Google Home so I'm guessing either chromecast itself or a receive app should have that information so we should at least theoretically be able to pull it.

Thoughts?

**Comment by skorokithakis** [comment]
Hey @alexyuriev! Is the functionality you're referring to different from the `catt seek` command? It can seek either absolutely or relatively, and the scrubber could just launch catt to perform the seek, and possibly run `catt info` to get info back.

Maybe a JSON output flag would be more convenient?

**Comment by alexyuriev** [comment]
Morning @skorokithakis - In my experiments ( Debian 8 ) for about 15% of the cases while it is playing a video ( served locally ) calling a ``catt seek`` returns an error "Nothing is currently playing``.  Running it again typically solves the problem but as you can imagine it is rather odd.

My thought is:

1. Implement stream-based control interface - in addition to/instead of the current one ( current one could be used to wrap the new interface ). Say catt when it is running would either directly or via ``inetd`` type wrapper open a TCP port for commands.

2. Formalize the commands to ``catt`` and responses from ``catt`` as JSONs that could be fed to or read from that interface. So say ``catt cast file.mp4`` will connect to control socket and send the following JSON:

{
   "command" : "cast",
   "device" : "chromecast-1",
   "cast_type" : "local",
   "resource" : "file.mp4",
}

etc

With something like this it would be relatively painless to implement scrubbers from a rather simple ones to the ones that can use i-frames form a local video let user visually scrub through the video.

**Comment by theychx** [comment]
@alexyuriev 
> for about 15% of the cases while it is playing a video ( served locally ) calling a catt seek returns an error "Nothing is currently playing"

This should be fixed in this branch: https://github.com/skorokithakis/catt/tree/blocking-statusupdate
Please let us know how well this works.

As for your own suggestion, that is honestly a bit too much on the elaborate side for my taste. In the end, that would be @skorokithakis 's call though.

**Comment by skorokithakis** [comment]
Hmm, I'm not sure why catt needs to connect to the control socket. Can't you just run it and parse the output from stdout, or, better yet, just use the API to import it and seek/play/stop/etc?

**Comment by alexyuriev** [comment]
@skorokithakis 

The reason why I think a control socket makes sense is that it sort of does already kind of does it:

If I do ``catt cast thisfile.mp`` catt is going to hang there until I Ctrl-C out of it, even after the playback is completed. Lets call this catt-1. If I want to do issue a command, I am going to do it via another command such as ``catt seek 400``. Lets call this catt2. When catt2 exits, catt1 is still going to continue to run, even if the casting session is over and Chomecast is done playing the local file. So if it behave this way already would not it be cleaner to formalize the service vs. command split?

P.S. I will test the new version of catt over next few days.

**Comment by skorokithakis** [comment]
Oh, that's just because Catt includes an HTTP server for convenience. The service is "serving files", not "controlling playback", although I agree that it would be handy to be able to control playback while serving.

However, since that's just a subset of functionality, and not even a particularly large one, I wouldn't want to hang too much functionality off of it. Anything that works while casting local files will have to work when casting remote files, and, since Catt isn't active for long, the socket wouldn't really work...

**Comment by jaconey** [comment]
@alexyuriev any update on this? Did you end up writing a simple Web/GUI for `catt`? I'm thinking to do it myself for my Raspberry Pi.

**Comment by alexyuriev** [comment]
@jaconey I hacked together some rudimentary code based on creating a p-frame-based seek-map but never made it into anything really useful. It is not doable inline on RPI ( too slow ) but it works if a map is pre-built. 

I should make finishing it a weekend project as I'm becoming more and more disappointed with the likes of Jellyfin.

**Comment by theychx** [comment]
This doesn't seem to be going anywhere, so closing.
