### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by law0077** [skorokithakis/catt#185]
hello, i have python3 but:
catt scan

Traceback (most recent call last):
  File "/usr/local/bin/catt", line 6, in <module>
    from catt.cli import main
  File "/usr/local/lib/python2.7/dist-packages/catt/cli.py", line 13, in <module>
    from .controllers import Cache, CastState, StateFileError, StateMode, get_chromecast, get_chromecasts, setup_cast
  File "/usr/local/lib/python2.7/dist-packages/catt/controllers.py", line 196
    def set_data(self, *args) -> None:
                              ^
SyntaxError: invalid syntax

help me please.

**Comment by theychx** [comment]
From the traceback that YOU just posted (for the third time):

`File "/usr/local/lib/python2.7/dist-packages/catt/cli.py"`

You're still using python 2. Try this:

`pip3 install catt`

**Comment by skorokithakis** [comment]
What's up with all these new accounts having the exact same problem? I pushed an error message for this, maybe we should release?

**Comment by theychx** [comment]
I'm pretty sure it's one person with several accounts. It's a bit bizarre.
I have a couple of minor things I want to fix, and then it should be ok to release.
