### ISSUE TITLE
Unable to start on raspberry pi

### ISSUE THREAD

**Issue by talormanda** [skorokithakis/catt#186]
I am trying to use this on my raspberry pi, however, I am running into an issue. It would see that it has python 2.7 and python 3 installed, and it is defaulting to v2.7. Is there any way I can run the command "catt" and tell it to point to python 3?

![image](https://user-images.githubusercontent.com/10092964/54883840-805d9180-4e40-11e9-99fd-3edd88e1695f.png)

**Comment by theychx** [comment]
Install with: `pip3 install catt`

**Comment by skorokithakis** [comment]
Alright I'm going to make a patch release.

**Comment by theychx** [comment]
@skorokithakis Please wait a couple of hours. There's no need to rush out a release, because of something that is not an actual bug.

**Comment by talormanda** [comment]
@theychx I did try using pip3 install catt , but it still produces what I have in the screenshot. I tried to remove python 2.7 and ended up screwing up my pi install.

**Comment by skorokithakis** [comment]
@theychx There isn't really anything in this potential release, just the error message when trying to install on 2.

**Comment by theychx** [comment]
@skorokithakis https://github.com/skorokithakis/catt/compare/v0.9.2...master

**Comment by talormanda** [comment]
@skorokithakis will this fix anything regarding my issue or is there something else I should do to make this work given my situation?

**Comment by skorokithakis** [comment]
@theychx Hmm, we may need to be more diligent about our commit messages so they get included in the changelog...

@talormanda It makes catt installable only on 3, so it would refuse to install on an older Python. Can you try to install from HEAD?

**Comment by talormanda** [comment]
@skorokithakis - sorry, I am unsure what HEAD is. But I can research and try if it is hard to explain

**Comment by skorokithakis** [comment]
I just meant clone or download the repo and install that.

**Comment by talormanda** [comment]
> I just meant clone or download the repo and install that.

excuse my dumbness, I don't know how to install from the repo after downloading the files.
