### ISSUE TITLE
syntax error: invalid syntax 

### ISSUE THREAD

**Issue by mangnik** [skorokithakis/catt#188]
Catt v0.9.2
Os : Kali 2019.1
Python3 : v 3.6.8
Python2.7.15+

Traceback (most recent call test):
File "/usr/local/bin/catt" line 6, in <module>
from catt.cli import main
file "/usr/local/lib/python2.7/dist-packages/catt/cli.py", line 13, in <module>
from .controllers import Cache, CastState, StateFileError, StateMode, get_chromecast, get_chromecasts, setup_cast
file "/usr/local/lib/python2.7/dist-packages/catt/controllers.py", line 196
def set_data(self, *args)-> None;
SyntaxError : invalid syntax

**Comment by theychx** [comment]
We somehow missed this ticket, sorry about that. Python2 is no longer supported.
