### ISSUE TITLE
No module named configparser on Rasbpian stretch

### ISSUE THREAD

**Issue by marek-saji** [skorokithakis/catt#189]
I’ve installed catt from `pip` on Raspbian 9.8 (stretch), but unfortunatelly it does not run:

```
$ catt
Traceback (most recent call last):
  File "/usr/local/bin/catt", line 7, in <module>
    from catt.cli import main
  File "/usr/local/lib/python2.7/dist-packages/catt/cli.py", line 3, in <module>
    import configparser
ImportError: No module named configparser
```

**Comment by theychx** [comment]
`catt` needs python 3.

Install with `pip3`, to make shure you are using that.

@skorokithakis Release? :smile: Master should be in a releasable state.

**Comment by skorokithakis** [comment]
Yep, will release soon. I wonder why the sudden uptick in this issue...

**Comment by skorokithakis** [comment]
Released 0.9.3! I'm not quite sure why it built a py2 wheel, but oh well.

**Comment by theychx** [comment]
Just tried to install with pip2 in a vm, and it did not fail, I'm afraid.
Which is strange, as I tried the same thing yesterday, where it failed as expected.

**Comment by skorokithakis** [comment]
Which version did it install?

**Comment by theychx** [comment]
`0.9.3` on python 2.7

**Comment by skorokithakis** [comment]
What the...

**Comment by theychx** [comment]
I get the same traceback when trying to run `catt`

**Comment by skorokithakis** [comment]
Same here, looking into it.

**Comment by theychx** [comment]
Yesterday I used `pip install --user https://github.com/skorokithakis/catt/archive/master.zip`,
just before I used `pip install --user catt`.
Don't know if that is an useful clue.

**Comment by skorokithakis** [comment]
I think it might do different things depending on if it's an egg vs if it's a zip (i.e. it tries to run `setup.py` in the zip and fails).

**Comment by skorokithakis** [comment]
Released 0.9.4, which refuses to run properly. I haven't found a way to prevent it from installing under 2, unfortunately.

**Comment by theychx** [comment]
Oh well. Still an improvement.

**Comment by theychx** [comment]
@skorokithakis Please remember to draft a `0.9.4` release here on gh.

**Comment by skorokithakis** [comment]
I released 0.9.5 as well, which doesn't even build a py3-compatible artifact. We should have done that the moment we broke compatibility, but unfortunately I didn't know how. That way, the latest py2-compatible version would install on 2, and the latest version on 3.

**Comment by skorokithakis** [comment]
@theychx Done, although I find GitHub releases a bit cumbersome and would prefer to switch to PyPI-only, since that's how everyone downloads releases anyway. Still, GitHub makes it easy enough that I can't complain.

**Comment by theychx** [comment]
It doesn't work. Now it just installs `0.9.4` instead on py2.

**Comment by skorokithakis** [comment]
That means it does work. It doesn't install 0.9.5.

**Comment by theychx** [comment]
> It doesn't install 0.9.5.

Eh, I'm confused now. It still installs. Wasn't the point to abort installation completely?

**Comment by theychx** [comment]
> but we can make packages not even attempt to install on py2, which is what we do as of 0.9.5.

Running `pip2 install catt` installs `0.9.4`, regardless of what the newest release would be. I dont understand how that is an improvement.

**Comment by skorokithakis** [comment]
Because we don't want it installing any package that's not compatible with 2.  We should have stopped at the latest 2-compatible package, but we were too late, so we might as well stop now.

**Comment by theychx** [comment]
Ah, I understand now. Thanks.

**Comment by skorokithakis** [comment]
No problem. Unfortunately I can't go back and retroactively mark packages as incompatible, it would be nice if `pip2 install catt` could install the latest version that actually did work there... Maybe the error message should read "Please install catt==0.8.whatever"...
