### ISSUE TITLE
Doesn't seem to be doing anything

### ISSUE THREAD

**Issue by parkerlreed** [skorokithakis/catt#190]
I'm trying 

```
catt -d "FIMC TV" cast_site https://en.wikipedia.org/wiki/Rickrolling
```

But nothing ever happens. TV doesn't respond and the program just sits there not printing anything.

Is there any way to debug what might be going on?

Arch, catt 0.9.5

**Comment by parkerlreed** [comment]
If I scan it does find it

```
[parker@e55 ~]$ catt scan
Scanning Chromecasts...
192.168.0.68 - FIMC TV - Google Inc. Chromecast
192.168.0.147 - TV2 - Google Inc. Chromecast
192.168.0.174 - TV3 - Google Inc. Chromecast
```

**Comment by skorokithakis** [comment]
Hmm, this works for me... Does casting videos work?

**Comment by parkerlreed** [comment]
Video took a second to load. site was still being weird but worked after rebooting the Chromecast. Thanks.
