### ISSUE TITLE
Esp8266 & Esp32 Support?

### ISSUE THREAD

**Issue by Edris89** [skorokithakis/catt#191]
Hi there,

I it possible to make al of this into a C application running on a Esp32 or Esp8266.
Esp32 is dual core so that would be nice.

This way it would be possible not to run this only in a python env or raspberry pi. 
But also in a small design. I could interact with it, with a android app and do some cool ethical hacking xD xD

It would also be possible to run this with the esp32 and a usb host device. 
This way if a PC is connected to the network and also a chromecast, after plugging it into the PC it would use the internet connection network information of that PC and thus it could attack the chromecast. LOL

It's a suggestion. I could start something small with this. What do you guys think of it?

**Comment by skorokithakis** [comment]
I'm not sure how an ESP32 can attack the Chromecast in a way a PC can't, but you can try porting the library to MicroPython or C if you want.

**Comment by Edris89** [comment]
Because then you would't need a PC. This way I could use a small device, smaller than a Raspberry. Hook it up with a battery and interact with my own made app to do some cool ethical hacking xd. One question do you know how to import the catt library with micropython?

**Comment by skorokithakis** [comment]
You need to try to run it there, fix any problems that come up and try again, and so on until it all works.
