### ISSUE TITLE
Two question about play local file

### ISSUE THREAD

**Issue by ozzyst** [skorokithakis/catt#192]
Hello. Thank you for good library!

I try play local video file and I get exception APIError("Playback failed"):
`cast = CattDevice(name=ChromecastConfig.device_name, ip_addr=ChromecastConfig.ip)
cast.play_url('/home/user/Downloads/Bumblebee.2018.BDRip.720p.seleZen.mkv', resolve=True, block=True)`
1. What a format of video file supporeted streaming?
2. What about path of video file? Does support abs path? or video should be 
must be in directory with projet?

**Comment by theychx** [comment]
I'm afraid that the API does not support local file casting at all, at this moment.

On the general question of which formats the chromecast supports, please see:
https://developers.google.com/cast/docs/media

**Comment by ozzyst** [comment]
Oh, thank you. You are saved my time!
