### ISSUE TITLE
Youtube uri's only work for VIDEO chromecasts

### ISSUE THREAD

**Issue by ppibburr** [skorokithakis/catt#195]
Casting a youtube uri to a google home mini results in nothing played.

I have to manually get the audio url with youtube-dl

**Comment by theychx** [comment]
The home mini was just added as an audio device in `pychromecast` (post latest release).
So please try:
`pip install -U https://github.com/balloob/pychromecast/archive/master.zip`
and let me know if this makes a difference.

**Comment by ppibburr** [comment]
Awesome that worked! Thanx

**Comment by ppibburr** [comment]
Just an FYI the 'add' command is incompatible

**Comment by theychx** [comment]
> the 'add' command is incompatible

This is only possible with the YouTube chromecast app, which is not available to audio-only devices. So that is expected. Your home mini is running the default/generic media receiver app when casting YouTube content.
