### ISSUE TITLE
Using IP of chromecast as alternative to device name

### ISSUE THREAD

**Issue by lunarok** [skorokithakis/catt#196]
Hi,

In some case, it's easier to use IP than device name. Seeing the code a simple alternative in the controllers must make this possible.
Do you think it could be added ?

**Comment by skorokithakis** [comment]
Hmm, yeah, I guess it would be simple to add. Maybe we could make `--device` check whether the passed value is an IP address?

**Comment by skorokithakis** [comment]
What do you think, @theychx?

**Comment by lunarok** [comment]
I just try the branch device-ip, it works :)
