### ISSUE TITLE
Support of audio group : how to use it

### ISSUE THREAD

**Issue by lunarok** [skorokithakis/catt#198]
Hi,

I see last summer the feature to support chromecast group was added. But I'm unable to understand how to use it.
-d option seems to be for one device only. do we have to pass it multiple times ? or only by file ?
I can't understand from the actual code what to do to use it and the help doesn't say anything also.

Thanks

**Comment by theychx** [comment]
I don't have access to a cc audio group myself, but as I recall you have to setup the group in the Google Home app, and then you should be able to just do:
```
catt -d name_of_group cast https://www.youtube.com/watch?v=z2_dhUv_CrI
```

**Comment by lunarok** [comment]
Arf, was simple like that
Yes, I create a group with Google Home, call -d MyGroup and everything works
Great
