### ISSUE TITLE
Allow specifying subtitles when casting remote url

### ISSUE THREAD

**Issue by cfal** [skorokithakis/catt#199]
Currently subtitle_url is only set here for local files:
https://github.com/skorokithakis/catt/blob/master/catt/cli.py#L186

It should be possible to specify a remote subtitle to go with a remote file eg:

catt cast -s "http://127.0.0.1/subs.vtt" "http://127.0.0.1/file.mp4"

**Comment by skorokithakis** [comment]
Does that not work right now?

**Comment by skorokithakis** [comment]
Interesting, it looks like we only fetch remote subtitles if they're SRT. @theychx, is there a technical reason for this?

**Comment by theychx** [comment]
Yep, that does not work. I'll whip up something.

> Interesting, it looks like we only fetch remote subtitles if they're SRT. @theychx, is there a technical reason for this?

Yes, we only to fetch the subtitle, if we need to process it (i.e. srt->vtt conversion). So in the case of a vtt sub, we just pass the url on to the cc.
Looking at that code, I can see that it still needs more work. We're currently not failing, if the sub is neither srt or vtt.
