### ISSUE TITLE
Cannot get to work

### ISSUE THREAD

**Issue by bipolarmorgan** [skorokithakis/catt#200]
I have python3 installed, yet catt command tells me it needs it to run. Please advise. More information available upon request.

Currently using ParrotOS Linux Distro, and if it makes a difference dual installed python v2 & v3 - see exact versions below.

#python2 --version
Python 2.7.16
#python3 --version
Python 3.7.3

Also I was going to try and install version 0.5.6, but didn't know how to go about that.
-----------------------------------------------------------------------------------------------------------

EDIT: So while waiting for more info, I decided to give one thing a shot. What about pip, was that the key. Sure was... here's what I did to make it work. Notice the first thing I thought of was the check the pip version.

#pip --version
pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7)
#curl -O https://bootstrap.pypa.io/get-pip.py
#python3.7 get-pip.py
Collecting pip
  Downloading https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl (1.4MB)
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-19.1.1
#pip3 install catt

Notice I used pip3 instead of pip to install catt... Ran catt scan to test and it found nothing, but it didn't complain about python. However, it did break pip command. Now simply create a symbolic link from pip2 to pip and that is resolved:

#pip
bash: /usr/bin/pip: No such file or directory
#cd /usr/bin
#ln -s pip2 pip
#pip --version
pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7)
#pip3 --version
pip 19.1.1 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)

THERE YOU HAVE IT, maybe a Hack of a Solution?? :)

**Comment by theychx** [comment]
try this:
`pip3 install catt`
