### ISSUE TITLE
Privacy concern / Chrome App?

### ISSUE THREAD

**Issue by JonathanMH** [skorokithakis/catt#201]
First of all thank you for this awesome project, I just briefly tried it on Ubuntu and it works like a charm!

I'm struggling to understand how it works when showing websites with commands like:

```
catt cast_site 'https://example.com'
```

because it flashes "DASH CAST" and that appears to be some sort of Chromecast app that is hosted and could theoretically log every URL that i cast to my chromecast?

**Comment by theychx** [comment]
All apps that run on your chromcast are fetched dynamically, even the `Default Media Receiver` which is the one `catt` uses for non-YouTube content.

You can poke around the applist yourself, with this command:
```
curl 'https://clients3.google.com/cast/chromecast/device/baseconfig' | tail -n+2 | jq .applications
```

The Dashcast repo is [here](https://github.com/madmod/dashcast).

**Comment by JonathanMH** [comment]
Thank you for the response! I didn't mean to call out Dashcast, pychromecast or catt specifically, it was more of a conceptual "how does this work exactly?" kind of question.

I'll close the issue, because I'm looking for something that doesn't necessarily expose URLs to third parties.

**Comment by theychx** [comment]
> because I'm looking for something that doesn't necessarily expose URLs to third parties

No urls are exposed to third parties. Chromecast apps run in a Chrome instance that runs on the Chromecast. The Dashcast app (running on your chromecast) simply enables you to display arbitrary webpages in this browser instance.
