### ISSUE TITLE
catt command not found

### ISSUE THREAD

**Issue by greeven** [skorokithakis/catt#203]
I am a bit confused. The readme.md simply says: Do a `pip install catt` and then start cast with `catt cast <youtube-url>`.

After doing the install part and restarting the terminal the catt command is not available.

Am I missing an obvious step here?

I will gladly provide any additional information if needed.

**Comment by theychx** [comment]
The `bin` location that your `pip` uses, most likely is not in your path (see with `echo $PATH`). 
If you installed with `pip install --user catt` on linux, then you probably need to add `~/.local/bin` to your path (by editing `~/.profile` or the like).

**Comment by greeven** [comment]
Thank you!

`export PATH="$PATH:~/.local/bin"` did it.
