### ISSUE TITLE
Weird pre-commit hook issues

### ISSUE THREAD

**Issue by theychx** [skorokithakis/catt#206]
I'm currently struggling with the pre-commit hook. It keeps on claiming that `flake8` failed, but running `flake8` manually produces no complaints.

**Comment by skorokithakis** [comment]
Hmm, what's it failing on?

**Comment by theychx** [comment]
I can't tell, as there's no useful output. There doesn't seem to be a way to tell `pre-commit` to be more verbose.

**Comment by theychx** [comment]
Just tried:
```
pre-commit clean
pre-commit run
```
..and now it's working! Do you have any idea what is going on?

**Comment by skorokithakis** [comment]
pre-commit should have output flake8's lines. If it didn't, maybe it couldn't run? I did get weird failures sometimes, but they're always resolved by pinning the flake8 version. I don't know what might be the problem here, but maybe running flake8 in verbose mode could be more informative?

Before it started working, anyway😛

**Comment by theychx** [comment]
> pre-commit should have output flake8's lines. If it didn't, maybe it couldn't run?

I must have been unable to run `flake8`, the alternative doesn't make sense when `flake8` runs ok by itself. It's strange that cleaning out the `pre-commit` cache would help though.

**Comment by skorokithakis** [comment]
Were you running the precommit flake8 or your systems flake8?

**Comment by theychx** [comment]
Flake8 of the virtual environment. Is that what you mean by precommit flake8?

**Comment by skorokithakis** [comment]
No, precommit makes its own environment in the cache folder. If that one fails for some reason, deleting that dir will fix it.

**Comment by theychx** [comment]
> No, precommit makes its own environment in the cache folder

I didn't know that, thanks.
> If that one fails for some reason, deleting that dir will fix it

That still doesn't make any sense to me, but whatever, it's working. :smile:

**Comment by skorokithakis** [comment]
Yep, as long as it works!
