### ISSUE TITLE
TypeError: Str, bytes or bytearray expected, not NoneType

### ISSUE THREAD

**Issue by drareve** [skorokithakis/catt#212]
Great project. 
I plan to use it with a script to play customised MP4 videos to visitors when they open the door with their access card.

I am using catt on Win10pro x64, using catt v0.10.0 and python3.7.4. 
The Chromecast device is Gen2, located on a separate VLAN
I connect to it directly over IP (no proxy) and it opens connections on TCP8008 and TCP8009
I can use catt to stream utube video without any issue.

However when I tried MP4 files it fails. See output in attached error.txt file
[error.txt](https://github.com/skorokithakis/catt/files/3694148/error.txt)

I initially thought I was using the wrong syntax to launch the program but https://www.computerhope.com/issues/ch001980.htm seems to use the same syntax without issue, albeit to a local chromecast.

I am not a coder but the error suggests it is expecting a value that is not there.

So I began to suspect there was corruption in the file itself which was MOV format converted by VLC to MP4. So I tried a sample from "https://file-examples.com/index.php/sample-video-files/sample-mp4-files" and got the same error.

Finally I downloaded the file of the utube video that I knew I could stream OK. But alas the same error.

Can you suggest how to resolve the issue. Thx

**Comment by skorokithakis** [comment]
That's odd, it looks like the local server address is `None` when it tries to save the file. Is there any restriction on your machine that makes `catt` unable to open the port? Can you add a `print(address)` on `c:\users\username\appdata\local\programs\python\python37-32\lib\site-packages\catt\http_server.py:109`?

**Comment by theychx** [comment]
I'm getting a feeling this is the culprit:
https://github.com/skorokithakis/catt/blob/master/catt/util.py#L62

**Comment by skorokithakis** [comment]
That seems very plausible. We should add a `raise ValueError("No adapters found")` at the end there or something similar, instead of returning `None`.

**Comment by theychx** [comment]
> I'm not sure why we can find no adapters, though.

We're not looking for adapters. Ever since we dropped using `netifaces` for this purpose (because `zeroconf` switched to `ifaddr`), we are guessing the local ip from the cc ip. As far as I can tell, the logic in `get_local_ip` doesn't suffice in this usecase, because the box running `catt` and the cc are on different subnets.

**Comment by theychx** [comment]
@skorokithakis Any ideas for an alternative implementation? Having looked through the suggestions from [this SO answer](https://stackoverflow.com/questions/166506/finding-local-ip-addresses-using-pythons-stdlib), I couldn't find anything that looked ideal for `catt`.

**Comment by drareve** [comment]
I tested CATT with the chromecast connected to the same subnet and it can play the mp4 file OK. Is it peculiar how CATT casts youtube content OK to different subnet but not when the source is local file.

**Comment by theychx** [comment]
@drareve 
> Is it peculiar how CATT casts youtube content OK

In that case the chromecast would be streaming directly from googles servers and not from your box, and so this problem doesn't come into play.

**Comment by theychx** [comment]
@drareve 
Can you try out the `local-ip-fix` branch? Should fix this problem.
```
pip install -U https://github.com/skorokithakis/catt/archive/local-ip-fix.zip
```

**Comment by drareve** [comment]
Thank you. It was successful. Applied the local-ip-fix on PC and ran catt from a different subnet to the CAST device. The results appeared to be the same as if it were on a local subnet. 

PC makes two connections to CAST on TCP:8008 and TCP:8008
CAST makes one connection to PC on TCP:46841

Is the service TCP:46841 opened on the PC a setting configured in CATT or is the port number selected by the CAST device, and if CAST selected, is it always this fixed value or random? Would be good to know for any firewall configurations.
