### ISSUE TITLE
Catt does not exit after playback ends

### ISSUE THREAD

**Issue by soreau** [skorokithakis/catt#218]
As the title states, catt simply does not exit after playback is complete. In catt-qt, I run catt instead of using catt api to play, because catt can play files and catt api can't. It runs catt in the background and this works with the exception of leaving running catt processes behind. I suppose it could try to kill catt processes on idle state but this seems sketchy at best. Is there a reason why catt doesn't exit after playback ends?

**Comment by skorokithakis** [comment]
You mean playback of local files, correct?

**Comment by soreau** [comment]
Yes

**Comment by soreau** [comment]
I basically figured out I can save the Popen'ed process to later kill the pid on certain conditions. This is fine while catt-qt is running but when it exits, it basically has to kill any running catt processes it spawned, which means the stream will eventually end (if you play from catt-qt and exit) or leave stale catt processes around. I guess doing the former will teach people to keep catt-qt running if they're playing something from it and I suppose this is expected behavior. I still don't understand why catt can't exit when playback ends but I guess this is just the way it works.

**Comment by skorokithakis** [comment]
We need to investigate whether this is a bug. We do know when the serving thread ends, and we kill catt when it does, but I'm wondering whether we can/do know for sure that playback has ended. @theychx, is that the case? Can we exit the thread when that happens?

**Comment by theychx** [comment]
It's not a bug. We're blocking the main thread, exactly because we currently do not know whether playback has ended. It should be easy to remedy though, as we can setup a listener to do that job.

**Comment by soreau** [comment]
Also what about cases where catt is passed a file that isn't media, like a text file? I see chromecast plays along and gives a buffering status message with the filename as title but catt doesn't exit in this case. Audio files work ok while image files cast and the chromecast reports paused state. I can't imagine a simple solution to this 'problem'. Then there's the case of catt stream stopped by another device or other external means. Streaming url's is less of a problem because catt seems to stop running eventually.

Ultimately my aim was to auto-play files in a directory. When a file is played, it attempts to play the next file in the directory (in alphabetical order). I have succeeded in doing this without 'leaking' catt processes but if there are non-playable files in the directory, it will stall on that file. I suppose it's not a showstopper but it is in the literal sense. The other obvious possibility is trying to look at file attributes and avoid playing files that will obviously not play but I'm thinking this is probably more work than it's worth.

**Comment by skorokithakis** [comment]
Agreed, due to the number of devices that support the Chromecast protocol I don't think we can know beforehand which files can be played and which can't... We could take a wild guess, but that would probably be worse than doing nothing. Maybe you could check playback and if it hasn't started in N seconds move on to the next file?

**Comment by soreau** [comment]
> Maybe you could check playback and if it hasn't started in N seconds move on to the next file?

I tried this and it wasn't working the way I wanted, mainly because there are 'null' media status messages sent when playback stops but also when it starts. I finally found a magic combination of timeouts and other sauce that seems to work now.. catt-qt 2.6 released. If you happen to try it and find any bugs, please report. Thanks for the help.

**Comment by soreau** [comment]
As a side note, I notice with catt-qt 2.6, if I skip to the next video file in a directory, the title information stays on screen when playing the video, it never disappears unless seeking. I found I can fix it by sending a stop command on skip before playing next file but it seems like it shouldn't be necessary.

**Comment by skorokithakis** [comment]
Hmm, I see. I'm not sure what might cause this, maybe @theychx will have more info.

**Comment by greghesp** [comment]
Did anyone manage to get any further with this?

I'm finding the same thing. After the playback of local files, the cast is not stopped and on a smart display, stays on the black screen with the cast logo.  On a speaker, the audio stops, but the cast connection is still connected (subsequent casts dont trigger the cast start noise)

I've also found that issuing the CATT stop command doesn't work for local files etc.  Works fine your YouTube etc.

**Comment by theychx** [comment]
I'll work something out.

@greghesp Is #235 resolved then?

**Comment by greghesp** [comment]
@theychx I'll add an update to #235
