### ISSUE TITLE
Feature request: HDMI CEC from catt

### ISSUE THREAD

**Issue by blomdahldaniel** [skorokithakis/catt#22]
Hi!
I have a TV with HDMI CEC functionality. So when the chromecast starts, the TV is started as well throug HDMI CEC. But if I shut off the TV, the HDMI CEC wont work for a couple of minutes. It would be awesome to be able to trigger the HDMI CEC again manually from catt.

Is that possible?

**Comment by skorokithakis** [comment]
Hmm, I have no idea, my TV doesn't support HDMI CEC... What would triggering it again do? Turn the TV on again?

**Comment by blomdahldaniel** [comment]
As far as I understand HDMI CEC the tv would be triggered to start and swap to the active HDMI port. So that would be a handy way of also changing the HDMI-port while triggering the startup. And if the TV is already up and running it will just switch channels.

So i was wondering how you talk to the chromecast, maybe there is already an api for that..?

**Comment by skorokithakis** [comment]
I use pychromecast: https://github.com/skorokithakis/catt/blob/master/catt/controllers.py

**Comment by blomdahldaniel** [comment]
Thanks, will take a look at it!
