### ISSUE TITLE
no cast_site command

### ISSUE THREAD

**Issue by CurtisZM** [skorokithakis/catt#221]
Installed using the pip install catt. When I try to cast_site, I get:

catt cast_site https://en.wikipedia.org/wiki/Rickrolling

Usage: catt [OPTIONS] COMMAND [ARGS]...

Error: No such command "cast_site".

Please assist. Thank you.
P.S. I'm very new to Rpi.

**Comment by skorokithakis** [comment]
Which version of catt are you using?

**Comment by CurtisZM** [comment]
This is where the rookie comes in. Where or how do I find that? Thank you for responding.

**Comment by skorokithakis** [comment]
Run `catt --version`.

**Comment by CurtisZM** [comment]
No such version is is saying

**Comment by CurtisZM** [comment]
I'm running Raspbian GNU/Linux 9 (stretch)

**Comment by skorokithakis** [comment]
Can you paste the entire output?

**Comment by CurtisZM** [comment]
Let me ask you this. How do you upgrade python 3.4? I have 2.7.13

**Comment by skorokithakis** [comment]
I think you need to install a newer version of Raspbian, but I don't know. You need Python 3.5 to use catt.
