### ISSUE TITLE
pip3 install 

### ISSUE THREAD

**Issue by CurtisZM** [skorokithakis/catt#223]
Installed the latest version of NOOB -Raspbian (3.2.1) and when I performed the pip3 install catt I'm seeing this warning.

Installing collected packages: youtube-dl, ifaddr, protobuf, casttube, zeroconf, PyChromecast, catt
  The script youtube-dl is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script catt is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**Comment by CurtisZM** [comment]
You changed the install to pip3?

**Comment by skorokithakis** [comment]
Glad it works!
