### ISSUE TITLE
CATT - add 'close' command to stop casting

### ISSUE THREAD

**Issue by kluszczyn** [skorokithakis/catt#224]
Hi there,

First, thank you for this very useful project!

I started using it to cast video stream from [Motion-Project](https://github.com/Motion-Project) and it works flawlessly! It utilizes `cast_site` option of CATT.
I did not discovered option how to stop casting. Issuing command `stop` do not close running app on chromecast. So if there is no already solution, I would propose to develop/add new command `close` and this command should close running app/casting session on chromecast, the similar way as voice command `stop casting` does.

Thanks!

**Comment by skorokithakis** [comment]
Hmm, yeah, I was looking for this yesterday as well. I thought we had implemented the `kill` command but it looks like we haven't, though `stop` eventually stops the app for me.

I agree we should implement this.

**Comment by theychx** [comment]
I'm not sure I understand this discussion: https://github.com/skorokithakis/catt/blob/a4b578c4937265345ec7e6274b2c668ca0d3fc44/catt/controllers.py#L510

I've never experienced the `stop` cmd NOT killing the running app. Steps to reproduce?

**Comment by kluszczyn** [comment]
I feel embarrassed as I can't reproduce behavior I observed earlier. Just checked on Google Chromecast and on Google Nest Hub and issuing command `stop` closes casting session opened with `cast_site`. Sorry for creating confusion. I'll close the issue.

**Comment by skorokithakis** [comment]
No problem!
