### ISSUE TITLE
Autodiscovery issues (new users, look here!)

### ISSUE THREAD

**Issue by Metus88** [skorokithakis/catt#226]
I installed catt in a raspberry pi 4 (rasbian lite) and also in my windows pc.
The installation looks ok.
If I write:
`catt scan`
I can see my two devices:
`root@raspberrypi:/# catt scan
Scanning Chromecasts...
record[a,in-unique,XXXXX-XXeditXX-XXXX-XXXXX-XXeditXXXXXXXX.local.]=120/119,192.168.1.111 - Cucina - None Google Nest Hub
record[a,in-unique,XXXXX-XXeditXX-XXXX-XXXXX-XXeditXXXXXXXX.local.]=120/119,192.168.1.110 - Studio - None Google Home Mini`
But when I try to use catt (youtube or also increase volume) with exemple `catt -d Studio volumeup` this is the answer:
`[record[a,in-unique,XXXXX-XXeditXX-XXXX-XXXXX-XXeditXXXXXXXX.local.]=120/119,192.168.1.111:8009] Failed to connect, retrying in 5.0s`

Every command catt.... give me this Failed to connect.
Have you any idea what I'm wrong?

p.s
I censored the output XXXXX-XXeditXX-XXXX-XXXXX-XXeditXXXXXXXX.local.
It's normal that after the scan there is "None" before "Google...."

**Comment by theychx** [comment]
This is caused by the newest version of zeroconf (`0.24.4`). Please downgrade to zeroconf `0.24.3`. I'll try to investigate what is wrong.

**Comment by Metus88** [comment]
Thanks you are right. On my raspberry I unistalled zeroconf with this command:
`pip3 uninstall zeroconf`
and after that I installed zeroconf 0.24.3:
`pip3 install zeroconf==0.24.3`
And now it's working.
Thanks a lot!

**Comment by skorokithakis** [comment]
Thanks for the report!

**Comment by theychx** [comment]
@skorokithakis Let's keep this open, so its easier for new users to find the solution to current `zeroconf` issues.

**Comment by skorokithakis** [comment]
Yep, agreed.

**Comment by nicholaswagner** [comment]
> @skorokithakis Let's keep this open, so its easier for new users to find the solution to current `zeroconf` issues.

#literallymejustnow  Thank you for keeping this issue open for new users!

**Comment by Faalangst26** [comment]
This no longer seems to be working, im running zeroconf 0.24.3 and im still getting the same error mesage. has something changed?

**Comment by theychx** [comment]
> im running zeroconf 0.24.3

That makes no sense, as these problems initially surfaced after the release of `zeroconf 0.24.4`.

**Comment by Faalangst26** [comment]
That's what I thought too, I am 100% certain running 0.24.3 though.

**Comment by theychx** [comment]
We haven't implmented any logging functionality (yet).
I still find this weird though. Can you post the output of `python3 -m site`? And `pip list` in the appropiate environment.

**Comment by Faalangst26** [comment]
python3 -m site returns:
```
sys.path = [
    '/home/p1mon',
    '/usr/lib/python37.zip',
    '/usr/lib/python3.7',
    '/usr/lib/python3.7/lib-dynload',
    '/home/p1mon/.local/lib/python3.7/site-packages',
    '/usr/local/lib/python3.7/dist-packages',
    '/usr/lib/python3/dist-packages',
]
USER_BASE: '/home/p1mon/.local' (exists)
USER_SITE: '/home/p1mon/.local/lib/python3.7/site-packages' (exists)
ENABLE_USER_SITE: True

```
pip3 list returns:

```
Package         Version
--------------- ---------
asn1crypto      0.24.0
bcrypt          3.1.7
casttube        0.2.0
catt            0.10.2
certifi         2019.6.16
cffi            1.12.3
chardet         3.0.4
Click           7.0
colorzero       1.1
cryptography    2.6.1
dropbox         9.4.0
entrypoints     0.3
falcon          2.0.0
future          0.17.1
gpiozero        1.5.1
gunicorn        19.9.0
idna            2.8
ifaddr          0.1.6
iso8601         0.1.12
keyring         17.1.1
keyrings.alt    3.1.1
pip             18.1
pip-autoremove  0.9.1
protobuf        3.11.2
psutil          5.6.3
PyChromecast    4.1.0
pycparser       2.19
PyCRC           1.21
pycrypto        2.6.1
PyGObject       3.30.4
PyNaCl          1.3.0
pyserial        3.4
python-apt      1.8.4
python-crontab  2.3.7
python-dateutil 2.8.0
pytz            2019.1
pyxdg           0.25
PyYAML          5.1.1
requests        2.22.0
RPi.GPIO        0.7.0
SecretStorage   2.3.1
setuptools      40.8.0
six             1.12.0
spidev          3.3
urllib3         1.25.3
wheel           0.32.3
youtube-dl      2020.1.1
zeroconf        0.24.3
```

**Comment by theychx** [comment]
Hmm, everything seems normal. If you for some reason are not keen on updating, you could install `pipx` and then do `pipx install catt`. That will create a seperate environment for all `catt`s dependencies (transparent to you). If that doesn't work either, then surely whatever is wrong must be specific to your setup.

**Comment by Faalangst26** [comment]
Reinstalling catt using pipx did the trick!

Thank you so much!
