### ISSUE TITLE
Get error: Failed to connect, retrying in 5.0s 

### ISSUE THREAD

**Issue by FabrizioA** [skorokithakis/catt#227]
Hi, I've 3 CC devices (1 Home Mini, 1 Nest Hub and 1 Chromecast (no Ultra)). I've installed catt correctly with Python3 .. all works ok .... BUT only for the first time :'(
Now, every time execute catt -d "Nest Hub" cast_site "https://mysite.ecc.ecc" I get the error:

[record[a,in-unique,UNIQUE-ID-HIDDEN-FROM-ME.local.]=120/119,NEST-HUB-IP:8009] Failed to connect, retrying in 5.0s

I've verified that catt scan works ok... and with a telnet that TCP ports 8008 and 8009 are open...
I don't know why it doesn't works anymore :'(

Thank you in advance.

**Comment by Metus88** [comment]
I happy to hear that I'm not alone. I opened 226 issue [https://github.com/skorokithakis/catt/issues/226](url)
But it was my first try to use catt, so can you tell me that before it worked and now it doesn't?

**Comment by theychx** [comment]
This is caused by the newest version of zeroconf (`0.24.4`). Please downgrade to zeroconf `0.24.3`. I'll try to investigate what is wrong.

**Comment by theychx** [comment]
#226

**Comment by FabrizioA** [comment]
@Metus88 yes I confirm you.

@theychx Thank you very much! ;)
