### ISSUE TITLE
Catt command not found

### ISSUE THREAD

**Issue by Faalangst26** [skorokithakis/catt#228]
I installed catt on my raspi by using
"pip3 install catt" it did not throw any errors but I can't seem to use any commands. I have all the dependencies. What did I do wrong?

**Comment by skorokithakis** [comment]
What happens exactly?

**Comment by Faalangst26** [comment]
I type in "catt - - help" and I get

`-bash: catt: command not found`

**Comment by skorokithakis** [comment]
Can you paste the output of the installation command and then running catt?

**Comment by Faalangst26** [comment]
`pinonepinontethe= 1921682220 ulane=):/hone $ pip3 install catt
Looking in indexes: https://pypi.org/sinple, https://ww.piwheels.org/simple
Collecting catt
Using cached https://files.pythonhosted.org/packagCs/45/Bc/abcedr9r5772bb7c18a945e1z2zrbf9aalee5a9eezcidfse319a10etars
Requirement already satisfied: youtube dl>=2819.01.24 in prov.local/lib/python2.7/site-packages
Requirement already satisfied: PyChromecast>-2.4.0 in pinon. local/lib/python3.7/site packages (from catt) (4.1.0
Requirement already satisfied: ifaddr>=.1.in Apimon.local/lib/python3.7/site-packages from catt) (8.1.6)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.7/dist-packages (from catt) (2.22.8)
Requirement already satisfied: Click)-5.0 in ./plain. local/lib/python3.7/site-packages (from catt) (7.0)
Requirement already satisfied: cast tube >=0.2.6 in .pro.local/lib/python3.7/site packages from AS11.
Requirement already satisfied: zeroconf>=0.17.7 in .prow.local/lib/python3.7/sitepackages (fron PyChromecast>-2.4.0-c
Requirement already satisfied: protobuf>=3.0.0 in ./pinon/.local/lib/python3.7/site packages (from PyChronecast-2.1.0-at
Requirement already satisfied: urllib 3t=1.25.0,1=1.25.1,1.26,>=1.21.1 in usr/local/lib/python3.7dist-packages (from reg
Requirement already satisfied: chardet.1.0,>=3.0.2 in usr/local/lib/python3.7/dist-packages (from requests) 2.18.4-xatt
Requirement already satisfied certifi>-2017.1.17 in Usr/local/lib/python3.7/dist-packages (fron requests>-2.18.4->catt) a
Requirement already satisfied idna2.9,>=2.5 in /usr/local/lib/python3.7/dist-packages (fron requests>2.18.+Seatt
Requirement already satisfied six=1.9 in /usr/lib/python3/dist-packages (from protobuf>-3.8.0->PyChronecast>2.4.8-catt)
Requirement already satisfied: setuptools in usr/lib python3/dist-packages (from protobuf)=3.0.0->PyChronecast>-2.1.0-catt
Installing collected packages: catt
The script catt is installed in /home/pimon.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-wara-script-location.
Successfully installed catt-0.10.2
plan@pinonlethe- 1921682220 alone=):/home $-`

**Comment by skorokithakis** [comment]
This is your problem:

```
The script catt is installed in /home/pimon.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-wara-script-location.
```

**Comment by theychx** [comment]
I'm guessing `~/.local/bin` is absent from `PATH`.

@Faalangst26 
Please add
```
if [ -d "$HOME/.local/bin" ] ; then
  PATH="$HOME/.local/bin:$PATH"
fi
```
to `~/.profile`

**Comment by Faalangst26** [comment]
Where would I need to add this?

**Comment by theychx** [comment]
`~/.profile` is a file.

**Comment by Faalangst26** [comment]
I do not have this file, I'm guessing that is the problem

**Comment by theychx** [comment]
Do you have a `~/.bash_profile`?

**Comment by Faalangst26** [comment]
Nvm, I just looked in the wrong place... Edited the file, testing it now

**Comment by Faalangst26** [comment]
I just reinstalled with the edited and `. Profile` it still throws the same error

**Comment by theychx** [comment]
You need restart the terminal, or log out-in if you are ssh'ing into your pi.

**Comment by Faalangst26** [comment]
Thx, trying that

**Comment by Faalangst26** [comment]
Still the same error, my profile file looks like this

`# the default umask is set in etc/profile: for setting the umask
# for ssh logins, install and configure the 11bpan-unask package.
umask 022

# if running bash
if [ -n "BASH_VERSION" ]; then
#include bashrc if it exists
if [ -f "HOME.bashrc" ]; then

"HOME.bashrc"
fi
fi

#set PATH so it includes user's private bin if it exists
if [ -d "HOME/bin" ]; then
PATH="$HOME/bin:$PATH"
fi

if [ -d "SHONE/pimon.local/bin" ]; then
PATH="SHOME/pinon.local/bin:$PATH"

fi`

**Comment by theychx** [comment]
You borked the snippet I told you to add to the file.
Please figure this out for yourself. This is an issue tracker, not a support forum.

**Comment by Faalangst26** [comment]
Alright, sorry Im not that fluent with Linux.
