### ISSUE TITLE
Youtube playlists 

### ISSUE THREAD

**Issue by blomdahldaniel** [skorokithakis/catt#23]
When I provide catt with a youtube link to a youtube playlist, the youtube dl is triggered correct (as it seems) but catt is faling. This is the logg for when i try to do this.

So, is this a bugg just form me or is thre functionality just not there yet for playlists?

I am on macOS and all other features in `catt` is working properly.

Logg
```bash
▶ catt cast https://www.youtube.com/watch\?v\=kk0WRHV_vt8\&list\=PL52RKVKBFM328OwddSMRQS9BYOA3oVDgl

Casting remote file https://www.youtube.com/watch?v=kk0WRHV_vt8&list=PL52RKVKBFM328OwddSMRQS9BYOA3oVDgl...
[youtube:playlist] Downloading playlist PL52RKVKBFM328OwddSMRQS9BYOA3oVDgl - add --no-playlist to just download video kk0WRHV_vt8
[youtube:playlist] PL52RKVKBFM328OwddSMRQS9BYOA3oVDgl: Downloading webpage
[download] Downloading playlist: Snarky Puppy - We Like It Here
[youtube:playlist] playlist Snarky Puppy - We Like It Here: Downloading 8 videos
[download] Downloading video 1 of 8
[youtube] kk0WRHV_vt8: Downloading webpage
[youtube] kk0WRHV_vt8: Downloading video info webpage
[youtube] kk0WRHV_vt8: Extracting video information
[youtube] kk0WRHV_vt8: Downloading MPD manifest
[download] Downloading video 2 of 8
[youtube] fuhHU_BZXSk: Downloading webpage
[youtube] fuhHU_BZXSk: Downloading video info webpage
[youtube] fuhHU_BZXSk: Extracting video information
[youtube] fuhHU_BZXSk: Downloading MPD manifest
[download] Downloading video 3 of 8
[youtube] kDXnPfA_5pY: Downloading webpage
[youtube] kDXnPfA_5pY: Downloading video info webpage
[youtube] kDXnPfA_5pY: Extracting video information
[youtube] kDXnPfA_5pY: Downloading MPD manifest
[download] Downloading video 4 of 8
[youtube] eFUOZ5PI3m8: Downloading webpage
[youtube] eFUOZ5PI3m8: Downloading video info webpage
[youtube] eFUOZ5PI3m8: Extracting video information
[youtube] eFUOZ5PI3m8: Downloading MPD manifest
[download] Downloading video 5 of 8
[youtube] 4Qo1NFwMhBA: Downloading webpage
[youtube] 4Qo1NFwMhBA: Downloading video info webpage
[youtube] 4Qo1NFwMhBA: Extracting video information
[youtube] 4Qo1NFwMhBA: Downloading MPD manifest
[download] Downloading video 6 of 8
[youtube] y0bcTSDFScg: Downloading webpage
[youtube] y0bcTSDFScg: Downloading video info webpage
[youtube] y0bcTSDFScg: Extracting video information
[youtube] y0bcTSDFScg: Downloading MPD manifest
[download] Downloading video 7 of 8
[youtube] L_XJ_s5IsQc: Downloading webpage
[youtube] L_XJ_s5IsQc: Downloading video info webpage
[youtube] L_XJ_s5IsQc: Extracting video information
[youtube] L_XJ_s5IsQc: Downloading MPD manifest
[download] Downloading video 8 of 8
[youtube] mg2cMqW_hOY: Downloading webpage
[youtube] mg2cMqW_hOY: Downloading video info webpage
[youtube] mg2cMqW_hOY: Extracting video information
[youtube] mg2cMqW_hOY: Downloading MPD manifest
[download] Finished downloading playlist: Snarky Puppy - We Like It Here
Traceback (most recent call last):
  File "/usr/local/bin/catt", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/catt/cli.py", line 238, in main
    return cli(obj={}, default_map=readconfig())
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/catt/cli.py", line 103, in cast
    stream_info = get_stream_info(video_url)
  File "/Library/Python/2.7/site-packages/catt/controllers.py", line 25, in get_stream_info
    "url": best_format["url"],
KeyError: 'url'
```

**Comment by skorokithakis** [comment]
Nope, it's a catt bug, thanks for the report. We need to tell youtube-dl to ignore playlists, as I don' t yet know how we can support them...

**Comment by theychx** [comment]
YouTube playlists are currently nor supported by pychromecast, as it requires the use of a dedicated youtube-controller, and the one currently in pychromecast is broken. [Someone](https://github.com/ur1katz/pychromecast) made a fork with a new [youtube-controller](https://github.com/ur1katz/pychromecast/blob/master/pychromecast/controllers/youtube.py) that works with the current yt cc-app. The author has unfortunately not done a PR for this, maybe he feels that it is not ready, who knows.
Anyhow, supporting this would seriously complicate what `catt` is doing, as we would need to utlilize both the standard media controller AND the youtube one, depending on the content.

**Comment by skorokithakis** [comment]
Agreed, catt would have to stay open while the playlist was playing, so I'm disinclined to support this. We shouldn't crash, though, we should just play the first video.

**Comment by theychx** [comment]
If we could use the new youtube-controller, `catt` would not need to stay open, as the entire playlist is dumped to the yt cc-app in one go (as I understand it).
In the meantime, I can do a PR to block playlists or play the first video, whichever you prefer.

**Comment by skorokithakis** [comment]
Oh, hmm, if catt doesn't need to stay open, I think that would be a very nice feature. We'll have to look into switching controllers, though, which is a task for later. For now, it'd be great if it just played the first (or rather current) video, ie just parse the playlist query parameter out of the URL. I think that would be the least surprise behavior, what do you think?

**Comment by theychx** [comment]
Current?

**Comment by skorokithakis** [comment]
A playlist URL can be pointing to any video in the playlist, like here:

https://www.youtube.com/watch?v=dZ2iKwydb2c&index=22&list=PLIhNUXJ4tecczqOyP-O1RkJ6ZpMrPygYk

This points to the 22nd video in the playlist, although just removing everything other than the `v` parameter results in the correct behavior (i.e. the video that the user was watching plays in catt).

**Comment by theychx** [comment]
Ah ok, I'll look into it.

**Comment by blomdahldaniel** [comment]
Great stuff! Would be an awesome feature if it will work with the new controller!

But do you really think the best way is to show the first video rather than echoing out an error in the terminal that _playlists are not supported_? Otherwise the user (me for eg) will start it, then think "ah, nice it worked!" and then it just stops after the first video...? I don't think that is the desired behaviour? It would be better to be loud and clear and tell the user that playlists are not supported right away..?

**Comment by skorokithakis** [comment]
@blomdahldaniel Yes, this is a valid concern. It depends on what the user's intent is. When I'm watching a playlist and copy-paste the URL to catt, I just mean "play what I'm playing now", in which case I wouldn't want catt to complain about the playlist rather than just strip the file. If someone meant "play the whole playlist", they would want a warning.

Maybe we should show a message like "Warning: playlists not supported, playing current video"?

**Comment by theychx** [comment]
The "show warning and play current video" strategy makes sense to me. But what if the supplied URL only contains a reference to a playlist, and not a video?

**Comment by skorokithakis** [comment]
Ah, hmm... Can we play the first video then, or is it too hard?

**Comment by theychx** [comment]
It is not too hard, but as @blomdahldaniel suggested, this might not be what the user expects. Your call.

**Comment by skorokithakis** [comment]
Yeah, it's definitely a UX issue... I'd rather do the most "helpful" thing for now and print "Playlist playback is not currently supported, playing the first/current video only" or something similar.

**Comment by theychx** [comment]
Agreed

**Comment by blomdahldaniel** [comment]
The perfect solution as of now I must say! 👌

**Comment by skorokithakis** [comment]
Boom, released! Thanks, @theychx!

**Comment by theychx** [comment]
@skorokithakis 
Thank you for the invitation!. Moving forward, I would be most comfortable creating branches of your repo and then do PR's from there (as opposed to commiting directly).

**Comment by skorokithakis** [comment]
@theychx Sounds good to me, although the repo is set up in a way so nobody can commit, everything must be merged in master :)

**Comment by theychx** [comment]
Cool, so how did you do that? Choose "master" as a protected branch?

**Comment by skorokithakis** [comment]
Yep, there's a thing in the options that lets you specify you want PRs to only be merged after a review, after tests pass, etc. I only found out about it recently, though, as I usually use Gitlab for my repos.

**Comment by blomdahldaniel** [comment]
This speed is impressive fellas! Great stuff!

While I still hsve you: Would it be possible to and a command that echoes out the available chromecasts in the network? Would be a neet feature as well imo...?

**Comment by theychx** [comment]
@blomdahldaniel 
> Would it be possible to and a command that echoes out the available chromecasts in the network?

I thought about that too. Feel free to open a new issue with this request.
