### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by karlzre** [skorokithakis/catt#230]
Hi, 

I just discovered Catt, looks a very interesting tools.

I'm trying to cas a website on a google Nest Hub.
When i launch de command : catt cast_site https://en.wikipedia.org/wiki/Rickrolling
I get : [record[a,in-unique,f4bc0b2a-b6b7-5001-1a43-db6e4aa55c88.local.]=120/119,192.168.1.xxx:8009] Failed to connect, retrying in 5.0s

a scan can find all my google home.
I've try with the option -d googlehomename i get the same error.

Could you help me with this error ?

**Comment by karlzre** [comment]
Ok found on other issue:

On my raspberry I unistalled zeroconf with this command:
pip3 uninstall zeroconf
and after that I installed zeroconf 0.24.3:
pip3 install zeroconf==0.24.3
And now it's working.

**Comment by theychx** [comment]
#226
