### ISSUE TITLE
Catt does not work when called from cron

### ISSUE THREAD

**Issue by Faalangst26** [skorokithakis/catt#231]
When using crontab to schedule a task that contains CATT, it does not function.
Either when i call it directly or when I call it via a shell script. 
Following is my crontab file:

`
PATH=$PATH:/bin

* * * * * /home/p1mon/catt.sh >> /tmp/catttest
* * * * * /bin/catt -d "Google Hub" cast_site "http://192.168.2.104" >> /tmp/catttest2.log`

Where the file catt.sh contains the following CATT code:
`catt -d "Google Hub" cast_site "http://xxx.xxx.x.xxx"`

This is weird because the catt.sh file also contains an echo "testing", and this does get echoed into the catttest file.

**Comment by skorokithakis** [comment]
What does the log say?

**Comment by skorokithakis** [comment]
Try redirecting stderr to it as well. This looks like a user error.

**Comment by Faalangst26** [comment]
SysLog Says:
`Jan 8 16:46:16 p1mon CRON[7411]: (root) CMD (/home/p1mon/catt.sh >> /tmp/catttest)
`

**Comment by Faalangst26** [comment]
log now says:
/home/p1mon/catt.sh 3: /home/p1mon/catt.sh catt: not found

**Comment by Faalangst26** [comment]
You were right, in my script i was not pointing towards the path for catt, where is catt stored by default?

**Comment by jhamilt0n** [comment]
Can you share your solution?  I cannot figure this out.

**Comment by Faalangst26** [comment]
When using a call from a script, you need to directly reference to the location of the catt files. So instead of using ```
catt -parameters
```
You need to use ```
/your/installation/path/catt -parameters
```
