### ISSUE TITLE
Amazon Prime Video or Tim Vision

### ISSUE THREAD

**Issue by StefanoGiu** [skorokithakis/catt#232]
Hello, is there a way to support paid services (of course having the subscription to that service), like:
- Amazon Prime Video
- Tim Vision

Thanks

**Comment by skorokithakis** [comment]
Hmm, I don't think so, they wouldn't love third-party utilities being able to play their content and I wouldn't want to get into a cat-and-mouse game with them. If you want to write a utility to return the URL of a video file, catt will happily play that, though.
