### ISSUE TITLE
ERROR: This video is unavailable.

### ISSUE THREAD

**Issue by ernstwys** [skorokithakis/catt#233]
Most youtube videos not playing anymore :(

ERROR: This video is unavailable.

**Comment by skorokithakis** [comment]
Can you try `pip install -U youtube-dl`?

**Comment by theychx** [comment]
@ernstwys I wonder if the laugh emoji means "problem solved"?

**Comment by ernstwys** [comment]
yes sorry.. did the trick .. perfect!

**Comment by theychx** [comment]
Great!
