### ISSUE TITLE
Cast MP3 file from server?

### ISSUE THREAD

**Issue by greghesp** [skorokithakis/catt#235]
I've got a local express server which when you make a GET request, serves up an mp3 file.  If I access this directly in the browser, it loads up and plays fine.

However if I do `catt -d "Office Hub" "http://localhost:3000/server/sounds/doorbell.mp3"` then nothing plays.

I can see catt logs out:
```
Casting remote file http://localhost:3000/server/sounds/doorbell.mp3...
Playing "doorbell" on "Office Hub"...
```

My Google Home goes into Cast Mode and opens the Default Media Receiver, shows the title of the file "doorbell" but no audio is played.

Looking on my Express server, I can only see 1 request:
`HEAD /server/sounds/doorbell.mp3 200 3.185 ms - 146703`

Is there something I need to respond with to make this work?
I should also add that using the `stop` command after this, doesn't kill the cast connection either

**Comment by theychx** [comment]
It could be a [CORS](https://developers.google.com/cast/docs/media) issue.

**Comment by greghesp** [comment]
I've got CORS disabled, and I can successfully make calls to my server from WebCore etc.

I've just commented out `//app.use(cors());` but still run into the same issue

**Comment by theychx** [comment]
You need to enable CORS.

**Comment by greghesp** [comment]
Sorry, typo.  CORS is enabled on the server, I commented it out just to make sure.  I've also added the option to change the success status but no joy there either.  Seems only to be making the HEAD request
`app.use(cors({optionsSuccessStatus: 200}));`

**Comment by theychx** [comment]
Maybe [http_server.py](https://github.com/skorokithakis/catt/blob/master/catt/http_server.py) can offer you clues.

**Comment by greghesp** [comment]
I dont know Python at all, so not entirely sure what I'm looking at there

**Comment by theychx** [comment]
Fair enough, I meant [this](https://github.com/skorokithakis/catt/blob/3e9dc9b8845823a21dc03e38e5481a84079d68a5/catt/http_server.py#L73) part of code specifically, to give you an idea of how our minimal server responds (the range stuff is not necessary for basic functionality).

**Comment by greghesp** [comment]
Hmm, looking at it, all the Headers seem to be OK.

![image](https://user-images.githubusercontent.com/768908/73957537-631d9e80-48fe-11ea-8ccf-614a74f267ae.png)

**Comment by skorokithakis** [comment]
Does the device play any other files?

**Comment by greghesp** [comment]
I haven't tried them, however I know this is due to how Express is serving the files. 
What I cannot figure out is the correct way for Express to serve them for CATT to play them

**Comment by skorokithakis** [comment]
Hmm, I'm afraid this is outside the scope here, as catt only sends the URL to the Chromecast, and what happens from then on is between the Chromecast and the server...

**Comment by greghesp** [comment]
I haven't figured out why this isn't actually working.  It must be a way the cast protocol calls the file.  My guess is that CATT defaults to a Live stream rather than a buffer, so the file needs to be streamed from Express, not served up as just a file.

**Comment by skorokithakis** [comment]
Express doesn't support content-range? The Chromecast protocol uses that a lot, from what I remember.

**Comment by theychx** [comment]
> My guess is that CATT defaults to a Live stream rather than a buffer, so the file needs to be streamed from Express, not served up as just a file

This is definitely not the case. You can always check with `catt info | grep stream_type`, when casting.

**Comment by greghesp** [comment]
Got it.  I was simply doing sendFile()

```
router.get('/sounds/*', async(req, res) => {
  res.sendFile(path.resolve(__dirname, `../bin/sounds/${req.params[0]}`));
  res.end();
});
```

however, I've change this to a readStream that works perfectly.

```
router.get('/sounds/*', async(req, res) => {
  fs.createReadStream(path.resolve(__dirname, `../bin/sounds/${req.params[0]}`)).pipe(res);
});
```

**Comment by theychx** [comment]
> Just need to figure out how to close the cast once the file has finished playing now

I'll implement an "block shell while casting" option, so you can just monitor the `catt` process, and be assured that playback has ended when this process dies. Would that be useful?

**Comment by greghesp** [comment]
I'm currently trying to work CATT into [Assistant Relay](https://github.com/greghesp/assistant-relay) since the Assistant SDK restricts people from casting via the SDK.

It's not so much an issue on monitoring the process since users can cast any remote file and stop any remote file.  
The main problem is if they add say a doorbell sound to Assistant Relay and have that cast when the doorbell is rung, the smart speakers etc will stay in cast mode, and `CATT -d "device" stop` doesn't work for local files for some reason.

**Comment by theychx** [comment]
> It's not so much an issue on monitoring the process since users can cast any remote file and stop any remote file.

I'm not sure we're on the same page here. What I meant was that, currently `catt` exits immediately after having fired a cmd at the cast device. With the new blocking behaviour, you could be notified of playback end, simply by observing the process.
Otherwise you would have to communicate directly with the cast device yourself from `node`, which I'm guessing you want to avoid.

**Comment by theychx** [comment]
> and CATT -d "device" stop doesn't work for local files for some reason.

I'm guessing this is specific to certain devices, not local files. I've never experienced this with my CC2, CC Ultra or CC Audio.

**Comment by greghesp** [comment]
> > and CATT -d "device" stop doesn't work for local files for some reason.
> 
> I'm guessing this is specific to certain devices, not local files. I've never experienced this with my CC2, CC Ultra or CC Audio.

Hmmm.  If you cast a local file and it finishes. What if you cast another file?  Does it make the cast noise again to initiate a new cast, or does it continue with the same connection.

**Comment by theychx** [comment]
>  Does it make the cast noise again

This must be specific to smart speakers, of which I own none. I only have "regular" Chromecast devices. Given that `catt` is not serving the local file itself, but you are serving it by other means, I don't understand how this kind of problem could ever be specific to local files.

**Comment by theychx** [comment]
Unless of course, your express thingy is confusing the smart speaker. :smiley:

**Comment by greghesp** [comment]
> Unless of course, your express thingy is confusing the smart speaker. 😃

I've tried it via command line too and it does the same thing :)
Let me test with a Google Home Mini, see if that has the same issue

**Comment by greghesp** [comment]
Yep,  it seems that the Google Home devices keep the cast session connected when serving local files for some reason

**Comment by theychx** [comment]
> I've tried it via command line too

Does this mean you also let `catt` serve the file?

**Comment by greghesp** [comment]
Yes like below.  The second cast attempt does not trigger the cast start sound.  Also as you can see, casting local files does not close the catt connection. I have to force abort it

![image](https://user-images.githubusercontent.com/768908/74233357-68923480-4cc2-11ea-9ee6-ff9faf121b5f.png)

**Comment by theychx** [comment]
Ah, ok. So this is actually two seperate issues:
1. When you are serving the file yourself, there's currently no way for you to know when playback has ended (at least using only `catt`). That's where the blocking behaviour would be useful.
2. When `catt` is serving the file itself, it currently has a crude behaviour, where you have to kill the process yourself, after casting of the local file has ended.

I'm pretty sure I can fix both of these problems.

**Comment by greghesp** [comment]
OK
1) Makes sense

2)  Use the command line, I have cast a local file to my Google Home Hub (display).  

![image](https://user-images.githubusercontent.com/768908/74234254-544f3700-4cc4-11ea-9cfc-3b89f680500e.png)

Once the file has finished playing, this screen is shown
![image](https://user-images.githubusercontent.com/768908/74234323-72b53280-4cc4-11ea-9183-08f43a34392d.png)

If I force the closing of catt using `Ctrl-C` it Aborts catt, but that screen still stays.  If I then do `catt -d "Office Hub" stop` the screen still stays.

**Comment by theychx** [comment]
> If I force the closing of catt using Ctrl-C it Aborts catt, but that screen still stays. If I then do catt -d "Office Hub" stop the screen still stays.

Hmm ok. Like I said, I've never experienced this behaviour from one of my casting devices.
I think I'll implement my solution to the two problems regardless, as this needs to be fixed anyway. With the new behaviours, it might be easier to understand the nature of the issues you experience with your Google Home Hub and smart speaker.

**Comment by greghesp** [comment]
> With the new behaviours, it might be easier to understand the nature of the issues you experience with your Google Home Hub and smart speaker.

It that something specific you want me to run through, or do you mean in general as to how smart speakers and displays work?

**Comment by theychx** [comment]
> It that something specific you want me to run through, or do you mean in general as to how smart speakers and displays work?

The former.

**Comment by greghesp** [comment]
OK, i'll open a new issue for it and run through the replication
