### ISSUE TITLE
Add video to queue from local files

### ISSUE THREAD

**Issue by lucki1000** [skorokithakis/catt#245]
I found it annoying to wait till the video ends to play another video from local, I wish there is a queue like it is in your project for youtube. Please add it. Your Project is very cool and I love it so far.

Regards
Lukas

**Comment by theychx** [comment]
Thank you for this suggestion!

A youtube-like queue for playback of local files, is not going to happen anytime soon, as it requires not only changes to `catt`, but also for us to make a custom chromecast app that implements the queing functionality (for youtube videos, the actual queing is done on the chromecast).

What we could do though, is to provide some means of playing an entire directorys worth of local files and/or play multiple files specified in a text-file (eg one file per line).

**Comment by lucki1000** [comment]
Oh I understand, 

> What we could do though, is to provide some means of playing an entire directorys worth of local files and/or play multiple files specified in a text-file (eg one file per line).

This is also a good solution.
