### ISSUE TITLE
Cast from YouTube without ads with premium

### ISSUE THREAD

**Issue by pokgak** [skorokithakis/catt#247]
Hi, thank you very much for the awesome software. 

I have a premium account for YouTube which means when casting from my other devices I never got ads before the video starts. When casting using catt I usually got an ad. I suspect this is due to catt not using my YouTube account when casting. Is that true? Could specifying credential in youtube-dl config (not sure if this doable) solve this?

**Comment by theychx** [comment]
> I suspect this is due to catt not using my YouTube account when casting. Is that true?

Yes. You can specify credentials with `-y username=bob -y password=bobscat` or alternatively use a `.netrc` file and do `-y usenetrc=true`. That would unfortunately also mean that `catt` would be using the default chromcast app and not the custom Youtube app (we currently can not specify anything other than video and playlist ids when communicating with the youtube cc app). But try it, it might work.
> Could specifying credential in youtube-dl config (not sure if this doable) solve this?

`catt` is not using the `youtube-dl` config file.

**Comment by theychx** [comment]
I just remembered that ads only show when using the custom youtube cc app. So if all you just want to avoid ads (and do not mind slightly inferior streaming quality), then you could simply do:
```
catt cast -f https://www.youtube.com/watch?v=sw_ETsbAvRM
```

**Comment by pokgak** [comment]
Login failed when specifying the credentials but I use 2FA for my google account so that may be the cause here. Output:

```
~ catt cast -y username=<EMAIL> -y password=<PASSWORD> "https://www.youtube.com/watch?v=wo3vQ2BfDa4"
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube] wo3vQ2BfDa4: Downloading webpage
[youtube] wo3vQ2BfDa4: Downloading video info webpage
Casting remote file https://www.youtube.com/watch?v=wo3vQ2BfDa4...
Playing "Are Cherry MX Keyswitches Really the Best?" on "Bedroom TV"...
```

> I just remembered that ads only show when using the custom youtube cc app

I noticed that the chromecast have different interface when specifying the credentials too.

> So if all you want is to avoid ads (and do not mind slightly inferior streaming quality), then you could simply do:
> 
> ```
> catt cast -f https://www.youtube.com/watch?v=sw_ETsbAvRM
> ```

confirmed no ads with the `-f` flag. Quality good enough for my use. Thanks @theychx !
