### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by skorokithakis** [skorokithakis/catt#248]
Our tests started failing recently. We're currently getting "resource not found", I'm not sure if that means we're getting throttled or if the video has been removed. Flappy/failing tests are very unhelpful, so we should try to get them back to good health.

@theychx do you have more info about the failures and potential solutions?

**Comment by theychx** [comment]
As far as I can tell, there appears to be some kind of surge in traffic from the CI provider to youtube, which results in these random "Too many requests" failures. I've noticed that this always happens late afternoon or evenings (CET), tests always seem to succeed earlier in the day. If this analysis is correct, then we could start using a GitHub actions based CI setup instead, which in my tests works really well.

PS: I've never been able to reproduce these yt errors on my own boxes.

**Comment by skorokithakis** [comment]
Do we need the tests to reach YouTube? Can we not just mock the response?

**Comment by theychx** [comment]
> Can we not just mock the response?

I guess we could, but wouldn't that be even worse than the current state of affairs? Any kind of actual change from yt that affects `catt`s functionality could go unnoticed.

**Comment by skorokithakis** [comment]
Oops, wrong button. It depends on what the test is testing. We clearly can't have tests failing at random. The other alternative is to consider the test passing when we get a throttling response, that way they would fail legitimately, at least, if not every time.

**Comment by theychx** [comment]
> The other alternative is to consider the test passing when we get a throttling response, that way they would fail legitimately, at least, if not every time.

Sounds workable.

**Comment by skorokithakis** [comment]
Great, I'll look into doing that (unless you can get to it faster?).

**Comment by theychx** [comment]
I can look into it this afternoon, no problem.

**Comment by skorokithakis** [comment]
❤️
