### ISSUE TITLE
Feature request: List of Chromecasts available

### ISSUE THREAD

**Issue by blomdahldaniel** [skorokithakis/catt#25]
A command that echoes out the names (and statuses, playing/not playing) of the available chromecasts. 

Would be a great feature!

**Comment by theychx** [comment]
I'm most in favour of doing this, with just the information we get from auto-discovery - which is: name, device type, ip-adress. Otherwise a good idea.

**Comment by skorokithakis** [comment]
Agreed, it'll help with the multiple Chromecast feature. I'll do that today.

**Comment by skorokithakis** [comment]
Damnit, I meant to make a PR for @theychx to review but botched the branch. @theychx, can you tell me if e9e3fb9089ad3335a2190f47845d7f7aedcdc4eb looks okay?

**Comment by theychx** [comment]
Works great.
But wouldn't it be easier to make a `CastController.scan` method that calls `pychromecast.get_chromecasts` and echo's, and just call that from `cli.py`, like the rest of the functionality?

**Comment by skorokithakis** [comment]
Fixed in e9e3fb9089ad3335a2190f47845d7f7aedcdc4eb.

**Comment by skorokithakis** [comment]
@theychx Oh, have they committed to that? I don't see anything in the documentation, and I'd rather not rely on an implementation detail. Can you point me to the docs where they define `get_chromecasts` as sorted?

**Comment by theychx** [comment]
Fair point. And sorry about bringing this up in the other PR-thread, that was a bit obnoxious. :pig:

**Comment by skorokithakis** [comment]
Nah, no problem, it could have saved us a few lines of code.
