### ISSUE TITLE
Stop cast after use ffwd command twice

### ISSUE THREAD

**Issue by mathefeitosa** [skorokithakis/catt#250]
The transmission is stopping after 2 uses of `catt ffwd <time>`.

**Comment by theychx** [comment]
I can't reproduce this. A bit of context would be useful.

**Comment by skorokithakis** [comment]
It's not "fast forward to TIME", it's "fast forward N seconds". You're fast-forwarding past the end of the video.

**Comment by theychx** [comment]
I think it's safe to close this.
