### ISSUE TITLE
set_default improvements

### ISSUE THREAD

**Issue by skorokithakis** [skorokithakis/catt#253]
While trying to test the directory feature from #251, I found some issues with `set_default`:

* `write_config` is deprecated, correct? If so, its help text should read "DEPRECATED:" at the start.
* `set_default` lets you add a device name or IP as the default, but we never show the user the names and IPs of devices, do we? We should make that clearer, or make `set_default` print a list of devices if no device is specified.

**Comment by theychx** [comment]
You mean make it print what device is being set as default?

**Comment by skorokithakis** [comment]
No, I mean have it show a list of devices so you can pick one. We don't do that, do we?

**Comment by theychx** [comment]
Oh, you mean pick one interactively?

**Comment by skorokithakis** [comment]
No, just literally print a list and exit 😛

**Comment by theychx** [comment]
Lol, I get it now. :face_with_head_bandage: I'll work something out.
