### ISSUE TITLE
Inquiry - Video Fullscreen?

### ISSUE THREAD

**Issue by ryancasler** [skorokithakis/catt#255]
I searched and searched but could not find anything on this...is there a way to force the resolution of the media displayed to be full screen on the chromecast?  I have a stream from a security camera which is lower resolution to allow it to stream faster.  But it doesn't appear full screen.  Thanks!!!

**Comment by theychx** [comment]
Nope, to my knowledge there isn't any way to do that. The chromecast does automatically scale some low resolution content. So maybe it's the aspect ratio it doesn't like, who knows.

**Comment by ryancasler** [comment]
Thanks!
