### ISSUE TITLE
Casting disappear after 10 minutes about

### ISSUE THREAD

**Issue by maframan** [skorokithakis/catt#260]
Hi,
in the last 2 weeks, casting disappear after 10 minutes about despite the info command provide me the dashcat casting information (below the details) but the Google HUB show the google picture.

Thanks and regards
Francesco
/home/pi/.local/bin/catt --version
catt v0.11.0, Yearning Yachtman.

/home/pi/.local/bin/catt -d 192.168.102.64 info
current_time: 0
content_id: None
content_type: None
duration: None
stream_type: UNKNOWN
idle_reason: None
media_session_id: None
playback_rate: 1
player_state: UNKNOWN
supported_media_commands: 0
volume_level: 0.29921257495880127
volume_muted: False
media_custom_data: {}
media_metadata: {}
subtitle_tracks: {}
current_subtitle_tracks: []
last_updated: None
is_active_input: False
is_stand_by: True
app_id: 84912283
display_name: DashCast
namespaces: ['urn:x-cast:com.google.cast.debugoverlay', 'urn:x-cast:com.google.cast.cac', 'urn:x-cast:com.madmod.dashcast']
session_id: a874b2c3-e659-45b8-870f-7650114798b7
transport_id: a874b2c3-e659-45b8-870f-7650114798b7
status_text: Overview - Home Assistant
icon_url:

/home/pi/.local/bin/catt -d 192.168.102.64 status
Volume: 30

**Comment by skorokithakis** [comment]
Hmm, are you casting a local or a remote file?

**Comment by maframan** [comment]
> Hmm, are you casting a local or a remote file?

I cast my home assistant hub site exposed on public internet

**Comment by maframan** [comment]
Now, i tried to factory reset my google hub and wait if the problem happen again.

**Comment by maframan** [comment]
After factory reset the problem appear again......... :(
/home/pi/.local/bin/catt -d one cast_site 'https://<MY_HA_SITE>:8123/lovelace/hub'

 cat .config/catt/catt.cfg
[options]
device = Cucina HUB

[aliases]
one = Cucina HUB

**Comment by skorokithakis** [comment]
Hmm, have you checked whether Chromecast has updated and now times sites out? catt doesn't really do anything after casting.

**Comment by maframan** [comment]
> Hmm, have you checked whether Chromecast has updated and now times sites out? catt doesn't really do anything after casting.

Yes, is it updated.
My Site is reachable, tried via Chrome Browser and with smartphone via cellular data.

**Comment by maframan** [comment]
the problem has appeared for two weeks, before it worked very well!

**Comment by maframan** [comment]
is there the command for debugging mode in catt?

**Comment by skorokithakis** [comment]
Not really, does catt exit after you cast the site or does it stay open? I haven't used the site casting functionality much.

**Comment by maframan** [comment]
Exit, with exit code 0

**Comment by skorokithakis** [comment]
And ten minutes later the cast stops?

**Comment by maframan** [comment]
can I to purge all cast configuration? I see this options --delete-cache how do It use?

**Comment by maframan** [comment]
> And ten minutes later the cast stops?

10 minutes about

**Comment by maframan** [comment]
Now, I tried to cast with ip address of google cast hub, test in progress

**Comment by maframan** [comment]
Not resolved........I'm very confused about this problem and not undestand how to debug It.

**Comment by skorokithakis** [comment]
Unfortunately I'm not sure how to help you, but this doesn't sound like a problem with catt. All catt does is launch the website, it doesn't run afterwards at all.

**Comment by maframan** [comment]
for help the community https://support.google.com/googlenest/thread/45388769?hl=en
The problem should be caused by firmware version 1.46.203796

**Comment by skorokithakis** [comment]
That makes sense, thanks!
