### ISSUE TITLE
mutlicast and cast groups- feature request

### ISSUE THREAD

**Issue by diaahussein** [skorokithakis/catt#261]
Hi is it possible to add the feature to cast the same video or URL to multiple chromecasts at the same time,
also to add groups in the config so you can send a song to the google home and a move to the chromecast
or select some chromecasts to be in group1 and some other chromecasts to be in group2 where you can stream content to teh group

**Comment by diaahussein** [comment]
I have tried building this script to perform the multi cast on multiple chromecasts

`catt scan | grep Chromecast | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b|([0-9]{2,5})' | grep -A1 -E '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' | sed '/--/d' |awk '!a[$0]++' >/tmp/chromecast.list
url=$1
filename="/tmp/chromecast.list"
while read -r line
do
catt -d $line cast "$url" > /dev/null 2>&1 &
done < "$filename"`

it works but unfortunately the video is not in sync on all of them 

will keep trying to find another solution.

**Comment by skorokithakis** [comment]
Hmm, I think it'll be very tricky to synchronize all of them so it doesn't sound bad, I'm afraid.

**Comment by diaahussein** [comment]
Actually I thought of the same thing
Maybe we can wait for the movie to start on all of them and then issue a seek command  to specific time to sync them up on that time

But if the network quality  in not the same on all of them we might get buffering delays on one of them

**Comment by skorokithakis** [comment]
It depends on what your goal is, if you want to synchronize within under 100ms, I think it's going to be hard. Might be worth a shot, though I don't have multiple Chromecasts to try with.

**Comment by theychx** [comment]
Syncing video content between chromecasts is not going to happen, and the groups in config suggestion is out of scope, IMO.
So closing.
