### ISSUE TITLE
Information returned isn't correct

### ISSUE THREAD

**Issue by dbrown8674** [skorokithakis/catt#263]
Version info:
`catt v0.11.0, Yearning Yachtman.`

`catt -d 192.168.2.54 info
current_time: 0
content_id: None
content_type: None
duration: None
stream_type: UNKNOWN
idle_reason: None
media_session_id: None
playback_rate: 1
player_state: UNKNOWN
supported_media_commands: 0
volume_level: 0.5
volume_muted: False
media_custom_data: {}
media_metadata: {}
subtitle_tracks: {}
current_subtitle_tracks: []
last_updated: None
is_active_input: False
is_stand_by: True
app_id: 84912283
display_name: DashCast
namespaces: ['urn:x-cast:com.google.cast.debugoverlay', 'urn:x-cast:com.google.cast.cac', 'urn:x-cast:com.madmod.dashcast']
session_id: 60b3605a-92b6-4601-b4ee-0bc6d6b938fe
transport_id: 60b3605a-92b6-4601-b4ee-0bc6d6b938fe
status_text: Overview - Home Assistant
icon_url:`

I get this info back but the device isn't casting actively. If I send the stop command it corrects the info but it wont correct its self automatically. This happened in a recent update to my nest hubs.

My nest hub's version is 22.81.36.303038810

**Comment by skorokithakis** [comment]
That's odd, but I'm afraid I don't have a Nest hub to be able to reproduce, I will try with my Chromecast and see, thank you.

**Comment by dbrown8674** [comment]
I tried replicating it on my chromecast ultra but it doesn't seem to be working, is there anything I can do to get you the information you need?

**Comment by dbrown8674** [comment]
https://support.google.com/googlenest/thread/21806578?hl=en

This might be an issue with the nest hubs in general, this support topic describes the same issue for apps like youtube. I'm going to cast some yule logs via the normal casting method and I'll update you.

**Comment by dbrown8674** [comment]
I wasn't able to replicate it with the normal cast methods, also something that I didn't mention is that after like 15 mins the site I casted would stop casting and that's when I get the incorrect info returned to me if I check status so I can't recast when the cast stops.

**Comment by skorokithakis** [comment]
Sounds like a duplicate of #260.

**Comment by dbrown8674** [comment]
Seems like this, I'll close this then thanks.
