### ISSUE TITLE
Live stream buffering issues

### ISSUE THREAD

**Issue by clam-i-am** [skorokithakis/catt#264]
Hello,
Thanks for the awesome tool!  Noticed one thing during testing - some live mp3 streams take forever to play, and it seems like low bitrate ones suffer the most. (Local mp3 files, videos, etc work fine.)

To reproduce: Here's an example live mp3 stream with low bitrate.  The live stream eventually started to play, after about 5 minutes of waiting:
```
user@host:~$ catt -d 192.168.1.4 cast http://d.liveatc.net/kjfk_twr
Casting remote file http://d.liveatc.net/kjfk_twr...
Playing "kjfk_twr" on "Wine Bar Display"...
user@host:~$ catt -d 192.168.1.4 info
current_time: 0
content_id: http://s1-bos.liveatc.net:80/kjfk_twr?nocache=2020053100061862051
content_type: video/mp4
duration: None
stream_type: BUFFERED
idle_reason: None
media_session_id: 1
playback_rate: 1
player_state: BUFFERING
supported_media_commands: 274447
volume_level: 1
volume_muted: False
media_custom_data: {}
media_metadata: {'title': 'kjfk_twr'}
subtitle_tracks: [{'trackId': 1, 'type': 'VIDEO'}]
current_subtitle_tracks: []
last_updated: 2020-05-31 00:06:35.854357
is_active_input: False
is_stand_by: True
app_id: CC1AD845
display_name: Default Media Receiver
namespaces: ['urn:x-cast:com.google.cast.cac', 'urn:x-cast:com.google.cast.debugoverlay', 'urn:x-cast:com.google.cast.broadcast', 'urn:x-cast:com.google.cast.media']
session_id: f3f5871f-9ebb-45e0-9d27-184903adcbfd
transport_id: f3f5871f-9ebb-45e0-9d27-184903adcbfd
status_text: Casting: kjfk_twr
icon_url:
```

Few things I noticed:

1. `content_type` is `video/mp4`.  To see if this was potentially the issue, I fired up a local icecast instance and created a dummy stream.  The content_type being specified by the stream is `audio/mpeg`, and I renamed the temp mountpoint to stream.mp3 (adding the file extension per [util.py](https://github.com/skorokithakis/catt/blob/master/catt/util.py)), and catt instantly recognized the content_type as being `audio/mp3` - cool!  Sadly, it didn't appear to change anything in terms of making the ~5 minute buffer time go away.  So not sure this is the problem, or at least the root of it.
2. What seems more interesting, at least at first glance to me, is the `stream_type` above - it appears that the stream is being treated as `BUFFERED`.  I noticed per the [Google Cast docs](https://developers.google.com/cast/docs/reference/chrome/chrome.cast.media#.StreamType) that `LIVE` is the other valid stream type.

I'm wondering if the low bitrate streams are just getting the brunt of this because of their smaller size - and thus more available to put in the buffer.  Using a different stream - say http://stream.wqxr.org/wqxr - tends to load within 5-10 seconds for me (128kbps stream).

Thoughts?  Possible to add a command line toggle to specify a `LIVE` 'StreamType'?

Not a hardcore developer here, so apologies if I've misstated something.  Want to ensure I've given a complete picture from what my testing has seen.

_(Version: v0.11.0, Yearning Yachtman.)_

**Comment by skorokithakis** [comment]
Hmm, I think your investigation is correct and the Chromecast is just waiting to fill the buffer before starting. Would it be possible for you to check if the problem goes away when specifying the `LIVE` StreamType?

**Comment by clam-i-am** [comment]
Certainly, happy to do so.  Using Ubuntu 20.04, downloaded via pip3.  I didn't see anything in `catt -h` that would allow me to do so - is there a quick and easy hack that I could try?  (github n00b here.)

**Comment by skorokithakis** [comment]
You can open `cli.py` and go to line 278ish, in `play_media_url`, and add `stream_type="LIVE"`. It's not making any difference for me, though :/

**Comment by skorokithakis** [comment]
Sorry, that was the wrong place. It should be in `controllers.py`, line 603, in `DefaultCastController`.

**Comment by clam-i-am** [comment]
Just tried that - no dice here either on that change :/

**Comment by skorokithakis** [comment]
It's too bad, I wonder what the problem is...

**Comment by clam-i-am** [comment]
Looks like `catt -d IPADDR play` may force it?

**Comment by skorokithakis** [comment]
Hmm, yeah, it looks like that workaround is hit-or-miss, so I don't think we can really even implement it, especially when this is a Chromecast problem... Sorry about that :/
