### ISSUE TITLE
Run as background/network service - Feature Request

### ISSUE THREAD

**Issue by weyrleader** [skorokithakis/catt#265]
First up a big thank you, catt is awesome! Please excuse any ignorance I display in this request, my understanding of these things is rudimentary at best.

Some background: I am using the catt cast-site feature as part of a home automation project for two separate tasks. Firstly to automatically cast the stream from one of my security cameras when motion is detected to our two Google Nest Hubs, the intent is to give us a heads up that someone is at the door ideally before they even reach it and knock (or attempt to break in). Secondly to stream a lovelace UI web page to the livingroom Nest Hub when someone starts the home theatre system via Home Assistant or Google Assistant, the page being cast has a bunch of controls on it effectively dynamically turning the nest hub into a remote control for all the theatre devices when its on. 

Catt works awesomely for both of these automation's, however I have found the initial load time can be delayed by several seconds (even just typing catt with no options) I assume its loading python libraries at this time, and the delay is especially evident when running from the RPi 4 I use for running Home Assistant. This is not really a big deal for the second of the above automations, but for the security use case, when you add this initial load time to the remote shell, the motion detection, and then the time to begin the cast it can take a good 10 seconds or more before we are seeing the security camera stream. 

Whilst 10 sec may not sound like a long time, in real life it makes the difference between whether it will even get looked at or not before one of the kids answers the door. I managed to improve the load times by moving catt to a docker container on a synology disk station which is also running the motioneye application to serve the camera streams, but it can still be variable depending on what the NAS is doing. 

So my thought here was two fold, having catt running as a background network service would mean that initial load time is no longer a problem, and it would remove the need for remote shell scripts allowing commands to be sent to a catt server from anywhere on the network.

Hope this made some sense.
James

**Comment by skorokithakis** [comment]
Hmm, it only takes less than a second to run catt for me, but you're right that it's a bit too slow even with no commands. I'll have to look into what we're loading that makes startup that slow, but your use case is a bit too specialized. You should look into using the API, it'll cut your response times as you won't have to load the libraries every time.

**Comment by weyrleader** [comment]
Thanks for the quick response, I will check out the API and see what I can do.

**Comment by greghesp** [comment]
@skorokithakis  What API are you referring to?

**Comment by skorokithakis** [comment]
@greghesp we have a relatively stable but undocumented API in `api.py`.
