### ISSUE TITLE
Feature for Loop of Local Video File

### ISSUE THREAD

**Issue by matts-2020** [skorokithakis/catt#266]
Hi,

I really appreciate all the time and effort that you have put into this.  I stumbled across it after days of searching for something that does exactly this, streaming to chromecast easily from a cli.  

I've got it installed and working and I was trying to see if there was either a way to loop playback of a local video or playlist.  I'm still a novice to coding so before I tried to create a loop function I thought i'd ask here.

Also what is the recommended or easiest way to create a local video playlist?

Thanks,

**Comment by theychx** [comment]
Sorry about the late reply, we seem to have missed this one.

> if there was either a way to loop playback of a local video or playlist

We have a simple high-level [API](https://github.com/skorokithakis/catt/blob/master/catt/api.py), with example code [here](https://github.com/skorokithakis/catt/blob/master/examples/accidents.py). This unfortunately does not support local files yet, but it's something I plan on implementing in the coming months.
I you are asking about seemless looping of content, then that is not currently possible (and likely ever will).

> Also what is the recommended or easiest way to create a local video playlist?

Outside of our API (which is not yet an option for your usecase), you could use `catt` cmds in a shell (like `bash`) script.
