### ISSUE TITLE
Just a question - CATT timeout

### ISSUE THREAD

**Issue by jonare77** [skorokithakis/catt#268]
This may not be releated to CATT behaviour, but I have with success been using it for a long time to cast my Home Assistant dashboards to Google Hub. This has been working great, suddenly the Google Hub started to go to Clock mode after 5 minutes of casting. This has never happend before, but I now have to start a new cast every five minutes.

I have checked out all settings on the hub rearding timeouts and screensaver settings and so on, but cant find a match.

Does anyone know why this happens ?

**Comment by skorokithakis** [comment]
Yes, check out #260.
