### ISSUE TITLE
Cannot play youtube playlist links

### ISSUE THREAD

**Issue by soreau** [skorokithakis/catt#269]
When I try `catt cast https://www.youtube.com/watch?v=<hash>&list=<hash>&start_radio=1&t=0` the chromecast begins showing youtube but then I get the message:
```
Error: Playlist is empty.
```
and catt exits. The link is found by going to any youtube video link and clicking on the '50+' thumbnail link in the top of the right column of videos, then copy the link from the browser address bar. This used to work, not sure where the bug is. Playing a single video link that is not a playlist works fine.

**Comment by theychx** [comment]
Does upgrading `youtube-dl` fix the problem?

**Comment by soreau** [comment]
Actually, I did have to upgrade youtube-dl to get catt working again to this point. Before I upgraded youtube-dl, I got a youtube-dl error. I currently have youtube-dl-2020.6.16.1. Do playlist links work for you?

**Comment by soreau** [comment]
I'm not sure if something changed or it was a fluke, but this seems to be working now with the same version of youtube-dl.
