### ISSUE TITLE
Casting remote mp4 does not work on chromecast ultra

### ISSUE THREAD

**Issue by trefis** [skorokithakis/catt#270]
Hi,

I just updated my old chromecast (1st gen) to a chromecast ultra (firmware version 1.42) and while I used to be able to `catt cast 'http://foo.bar/file.mp4'` without issues on the 1st gen, that doesn't seem to work anymore.
catt tells me `Playing "file" on "ChromeCastName"...` and exits but the file doesn't get played. If I download the file and cast locally then everything works fine.

Happy to help debugging this if you can provide some guidance.

**Comment by theychx** [comment]
Does the problem affect all playback of video content, or is it specific to some website and/or kind of content? If the latter, then please provide real url for testing.

**Comment by trefis** [comment]
Thanks for the questions, apparently my testing wasn't good enough.
I did manage to get some files to play properly, even from that website. Which indicates that there is indeed an issue with the content. That seems contradictory with my initial report « if I download the file and cast locally then everything works fine », and it is: casting from a local file doesn't work either. So there is indeed a problem with the content.

I have uploaded a test file [here](http://parce-q.eu/~trefis/test-file.mp4) and can confirm that it can be casted without issues on a 1st gen chromecast but not on my chromecast ultra.

**Comment by theychx** [comment]
It's the sound your ultra doesn't like. A quick google search reveals that a lot of people are having problems with surround sound on cc's, after a firmware update a couple of years back. It then also makes sense that your 1st-gen cc has no problems with this content, as I assume it hasn't received any firmware updates for a long time now.
I can't test any further myself, as I do not have access to a surround sound setup.

If you dont care about surround, you could fix the problem by giving downloaded files this treatment:
```
ffmpeg -i testfile.mp4 -c:v copy -ac 2 fixed_testfile.mp4
```

**Comment by skorokithakis** [comment]
There have been a few firmware-related Chromecast issues lately, haven't there... Odd that there are so many issues.

**Comment by trefis** [comment]
Ah indeed @theychx, that was the issue.
Sorry to have bothered you guys, and thanks for the help!

**Comment by theychx** [comment]
@trefis You might be able to get streaming directly from the service working if the content is available without surround sound. Find out with:
```
youtube-dl -F <contenturl>
```
If you find a useful format, you can then use the format code from the corresponding column:
```
catt cast -y "format=<formatcode>" <contenturl>
```

**Comment by trefis** [comment]
Thanks for the tip!
