### ISSUE TITLE
FW rules

### ISSUE THREAD

**Issue by norey** [skorokithakis/catt#274]
So I have a Google mini in a separate VLAN than the host. Everything works fine when I don't have any traffic blocked going back to the host. I can cast any audio just fine. But when I block traffic going back to the host, casting fails even though established/related traffic from host to the mini is allowed. What kind of traffic should I allow from the mini to the host?

**Comment by skorokithakis** [comment]
You should probably only block outgoing connections from the Google Mini VLAN, that's what I do IIRC and it works well.

**Comment by norey** [comment]
That's what I'm already doing. Outgoing connections from the mini VLAN to host VLAN is blocked. Established / Related traffic from host VLAN to mini VLAN is allowed.

**Comment by skorokithakis** [comment]
Hmm, when I was doing that, I had made a mistake and it wasn't working, but I'm not sure now what the mistake was. Only allowing established connections should work, I think there might be an issue with your configuration.

**Comment by norey** [comment]
When outgoing connections from mini VLAN to host VLAN are allowed, everything works fine. I'm not sure what else should I try. Is catt hosting some kind of server that needs access from the chromecast device?

**Comment by skorokithakis** [comment]
Only if you're casting local media, but you're casting remote files, no? That requires access to the internet.

**Comment by norey** [comment]
I forgot to mention that I'm only casting local audio files. Nothing is remote.

**Comment by skorokithakis** [comment]
Oh, then yes, you'll need the incoming connection, I'm afraid.

**Comment by norey** [comment]
So allow all outgoing connections from google mini to host? are there any specific ports that should be open?

**Comment by skorokithakis** [comment]
We use port 45114 TCP by default.

**Comment by norey** [comment]
Thanks, I'll try it out.

**Comment by norey** [comment]
Any way I can configure that port? after a tcpdump, I don't see 45114, it looks random to me.

**Comment by skorokithakis** [comment]
Hmm, I'm not quite sure because we've never really needed to, you can have a look at the code to see, it's in `http_server.py`. I can look later, I'm trying to fix a breaking bug at the moment.

**Comment by norey** [comment]
Actually, after digging into the code, the ports used are between 45000 and 47000. Configuring those in the firewall worked nicely, thanks.

**Comment by skorokithakis** [comment]
Ah, great, thanks for letting me know!
