### ISSUE TITLE
"invalid byte range" casting to Nest Hub Max

### ISSUE THREAD

**Issue by srd424** [skorokithakis/catt#279]
Using 0.11.2, in an Ubuntu 18.04.4 container, python 3.6.9. Installed with pip:

```
~/birdcam$ ~/.local/bin/catt -d "Kitchen display" cast ./wk-robin-long-bath.mp4
Casting local file ./wk-robin-long-bath.mp4...
Playing "wk-robin-long-bath" on "Kitchen display"...
Serving local file(s).
192.168.128.172 - - [07/Jul/2020 19:32:21] code 400, message Invalid byte range video/mp4 - 151.13 MB
192.168.128.172 - - [07/Jul/2020 19:32:21] "GET /?loaded_from_catt HTTP/1.1" 400 - video/mp4 - 151.13 MB
Error: Playback of local file has failed.
```

Any ideas here? The Nest Hub Max can be a little weird compared to ordinary Chromecasts, I think. There shouldn't be anything odd about the file ..

**Comment by skorokithakis** [comment]
Hmm, no, I'm afraid we'd need to see the byte range it's attempting to fetch... Can you run Wireshark and check?

**Comment by pachecora** [comment]
I also have the same error ...

(venv) morpheu@kivy:~$ catt cast TwoStepsFromHell.mp4 
Casting local file TwoStepsFromHell.mp4...
Playing "TwoStepsFromHell" on "Sala de TV"...
Serving local file(s).
192.168.1.6 - - [07/Jul/2020 21:46:35] code 400, message Invalid byte range video/mp4 - 38.39 MB
192.168.1.6 - - [07/Jul/2020 21:46:35] "GET /?loaded_from_catt HTTP/1.1" 400 - video/mp4 - 38.39 MB
Error: Playback of local file has failed.

ubuntu 18.04
Python 3.6.9

**Comment by skorokithakis** [comment]
@erdeiattila fixed this in #280, which is now in master. Can you confirm that the fix works?

**Comment by srd424** [comment]
I'll try, may take a couple of days, stuck in one of my eternal health
mini-crises! Thanks for speedy response, I was going to get around to
tcpdump eventually :)

**Comment by srd424** [comment]
Almost there ... needs #281 as well! Thanks :)
