### ISSUE TITLE
Some videos play with wrong orientation on Nest Hub Max

### ISSUE THREAD

**Issue by srd424** [skorokithakis/catt#282]
This is a weird one which may well not be a catt issue, but .. some of my videos play with the wrong orientation, i.e. rotated 90° clockwise .. there's no weird metadata set, and transcoding with ffmpeg fixes the issue. I know ffmpeg is supposed to rotate if the appropriate metadata is set, but it isn't .. really odd.

[raw-meta.txt](https://github.com/skorokithakis/catt/files/4898050/raw-meta.txt) metadata on raw file, which plays rotated
[working-meta.txt](https://github.com/skorokithakis/catt/files/4898051/working-meta.txt) metadata from the transcoded file, which is fine 

Here's the diff:

```
@@ -5 +5 @@
-profile=High
+profile=Constrained Baseline
@@ -7 +7 @@
-codec_time_base=125257/7528000
+codec_time_base=1/60
@@ -18 +18 @@
-level=51
+level=30
@@ -31,2 +31,2 @@
-avg_frame_rate=3764000/125257
-time_base=1/150000
+avg_frame_rate=30/1
+time_base=1/15360
@@ -35,3 +35,3 @@
-duration_ts=18788550
-duration=125.257000
-bit_rate=6318487
+duration_ts=1924608
+duration=125.300000
+bit_rate=10114461
@@ -40 +40 @@
-nb_frames=3764
+nb_frames=3759
@@ -57 +56,0 @@
-TAG:encoder=AVC Coding
@@ -81,2 +80,2 @@
-bit_rate=64000
-max_bit_rate=127313
+bit_rate=509
+max_bit_rate=69000
@@ -84 +83 @@
-nb_frames=1957
+nb_frames=1958
```

Very likely not a catt issue, but posting here in case anyone has any clues?

**Comment by skorokithakis** [comment]
Hmm, that's very odd indeed... I doubt it's a catt issue, since we just serve the file's bytes and don't do anything ellse to it, but I also don't know what else the problem might be...

**Comment by srd424** [comment]
Probably some whacky heuristics in there somewhere .. if catt doesn't extract metadata from the video and pass it the Nest Hub Max separately, I guess it's just a firmware problem .. feel free to close!

**Comment by skorokithakis** [comment]
Yep, sounds like it!
