### ISSUE TITLE
code 400 invalid byte range on local files

### ISSUE THREAD

**Issue by jmolg** [skorokithakis/catt#283]
Thanks for this excelent app,  but I a have a proble using local files.

If I use 

catt -d two cast "https://www.youtube.com/watch?v=dQw4w9WgXc

It is works.

But if I try a local file i have this error

catt -d three cast ./HomeControl/Luka1.mp3

Casting local file ./HomeControl/Luka1.mp3...
Playing "Luka1" on "Planta Alta"...
Serving local file(s).
192.168.1.72 - - [17/Jul/2020 12:00:31] code 400, message Invalid byte range audio/mp3 - 13.50 KB
192.168.1.72 - - [17/Jul/2020 12:00:31] "GET /?loaded_from_catt HTTP/1.1" 400 - audio/mp3 - 13.50 KB
Error: Playback of local file has failed.

Thanks

**Comment by skorokithakis** [comment]
Can you try the latest master? Sounds like a duplicate of #279.

**Comment by jmolg** [comment]
Sorry, How can I install from master?

**Comment by skorokithakis** [comment]
You can download the zip file from Github (on the main page) and pip install that.

**Comment by skorokithakis** [comment]
I will make a new release if it works for you.

**Comment by jmolg** [comment]
pi@raspberrypi:~ $ sudo pip install catt-master.zip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing ./catt-master.zip
    Complete output from command python setup.py egg_info:
    This program requires Python 3 and above to run.

sudo apt-get install python3
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3 is already the newest version (3.7.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ python --version
Python 2.7.16
pi@raspberrypi:~ $ python3 --version
Python 3.7.3

**Comment by jmolg** [comment]
I dont know how to install manually

**Comment by skorokithakis** [comment]
How did you install catt originally?

**Comment by jmolg** [comment]
pip3 install catt

**Comment by jmolg** [comment]
Thanks!! Now its work
