### ISSUE TITLE
Add full Desktop casting support to CATT!

### ISSUE THREAD

**Issue by Spamm00r** [skorokithakis/catt#284]
Hi,

I'm using CATT extensively and wonder what would be necessary to add full Desktop casting support to CATT.

While everything else I can cast using CATT, for full Desktop casting, I still need to do it manually via the Goolge Chrome browser.

I know that CATT just sends the links to streams to the Chromecast. But what do we need to also be able to cast the full Desktop to the Chromecast?

How does Google Chrome transcode the Desktop and stream it to the Chromecast?

Can we just use CATT to let the full Desktop stream to the chromecast instead of selecting it in the Google chrome browser?

That would have the added benefit, that you would be able to stream any content, that the Chromecats normally does not support, from your Desktop PC to the chromecast including high definition content like BluRay's etc.

That would be a very useful addition.

**Comment by skorokithakis** [comment]
Unfortunately I think this is too far outside the scope of catt, although if you find something that will capture the screen and expose that on a local HTTP server, you can easily get catt to cast it!
