### ISSUE TITLE
Issue with seek when casting local VP9/Vorbis WebM file

### ISSUE THREAD

**Issue by MaxBarraclough** [skorokithakis/catt#285]
I downloaded [this](https://audio-video.gnu.org/video/2016-02-08--rms--free-software-and-your-freedom--zurich--hd.webm) VP9/Vorbis WebM video (listed [here](https://audio-video.gnu.org/video/)) and I'm able to cast the local file, but if I use `catt seek`, the audio begins to play correctly, but it takes some time (up to several minutes) for the video to begin to play.

I'm running catt v0.11.3 on Windows 10.

**Comment by skorokithakis** [comment]
This sounds like a problem with the Chromecast ckdec, as catt doesn't really know anything about the file format, it just serves raw bytes.

**Comment by MaxBarraclough** [comment]
Ok, thanks for the quick response.

**Comment by MaxBarraclough** [comment]
I've since tried playing the same video file in various other players, including Firefox and VLC. Turns out they all struggle to seek, and Chromecast copes pretty well by comparison.
