### ISSUE TITLE
Feature request: cast with seek

### ISSUE THREAD

**Issue by MaxBarraclough** [skorokithakis/catt#286]
Feature request: a new `--seek` flag for `catt cast`, so that initialization of the cast, and setting the seek position to start playing from, can be done in a single command.

**Comment by theychx** [comment]
Yeah, that would be nice. It's on my todo list.

**Comment by skorokithakis** [comment]
Can we tell the Chromecast to start from a specific timestamp, or do we have to do a play and a seek internally?

**Comment by theychx** [comment]
> Can we tell the Chromecast to start from a specific timestamp

Yep, the default receiver supports this. As for YouTube, this was implemented in `casttube` recently, but the `pychromecast` controller hasn't been updated yet.
