### ISSUE TITLE
Feature request: Docker Image

### ISSUE THREAD

**Issue by g00nix** [skorokithakis/catt#287]
A docker image would be really helpful for cases where there are problems with dependencies on the host.

Having a tutorial for docker would allow us to run `catt` just with one command.

**Comment by skorokithakis** [comment]
Isn't it possible to just do this?:

```
docker run -i -t python:3.7 /bin/bash -c "pip install catt; catt cast 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'"
```

I don't know if maintaining a Docker package for such a simple package is worthwhile, really...

**Comment by g00nix** [comment]
> I don't know if maintaining a Docker package for such a simple package is worthwhile, really...

Can you please add this docker example to the readme?

**Comment by skorokithakis** [comment]
Yep, done!
