### ISSUE TITLE
catt cast_site stuck on "DashCast - Force Loading <local url>" for insecure site

### ISSUE THREAD

**Issue by fnord123** [skorokithakis/catt#292]
$ catt --version
catt v0.11.3, Yearning Yachtman.

Target device: Tried on both ChromeCast Ultra and Nest Hub Max

command line: catt -d 192.168.86.3 cast_site "http://192.168.86.200"

**What happens:** The Chromecast displays, "DashCast" in the center of the screen and "Force loading: http://192.168.86.200" at the bottom edge of the screen.

**What I want to happen:** Show the output of the web page.

http://192.168.86.200 is a local web server of a Tesla Gateway 2 that serves an insecure website (per Chrome) with a self signed cert.

When I view 192.168.86.200 via Chrome on my laptop Chrome complains about an insecure website and I have to click advance to force it to proceed (by accepting the site as safe).  Once I do that, I can view the website on my laptop browser. Furthermore, at that point I can then cast the website to my ChromeCast and it does successfully display on the ChromeCast device.

I'm guessing that the problem here is that ChromeCasts don't like self-signed certs.  However, since I can successfully cast the website from a tab once I accept the cert in Chrome on my laptop, I'm hoping there is a way to do the equivalent when using Catt/DashCast.

**Comment by skorokithakis** [comment]
Unfortunately I don't think there's a way to force the Chromecast to accept an invalid cert, especially through the network, as that would compromise security.
