### ISSUE TITLE
[FR] change cast_site URL without connection reset

### ISSUE THREAD

**Issue by mario-tux** [skorokithakis/catt#293]
It would be useful if CATT could, having a device already casting a URL by a previous CATT request, to switch on another URL without making the splash screen appears again. I'm using CATT to show cameras streaming on my Google Nest Hub Max: using this feature I could rotate vision on the different cameras or change tab in Home Assistant dashboard.

**Comment by theychx** [comment]
This is currently not possible to implement, as the chromecast app we are using for `cast_site` requires this approach to work properly. Addressing the real issue here (which is the flaky cc-app), is currently not a priority.
