### ISSUE TITLE
Timeout when chromecast connecting to HTTP server.

### ISSUE THREAD

**Issue by vext01** [skorokithakis/catt#294]
Hi,

Tried catt for the first time yesterday. Really great, thanks.

One problem I had when serving a file from my laptop over wifi: the chromecast takes a little while to connect to the http server and this can cause issues.

I saw two failure modes:
 - catt would exit before the chromecast could connect.
 - the chromecast would connect and start playing the file, then catt would stop the http server.

The latter is presumably a race condition?

My guess is that catt waits for a fixed time (e.g. 5 seconds) for the chromecast to connect? I wonder if it just needs to wait a little longer? If that's the case, should the timeout be configurable?

I was able to get a video playing after several attempts though :)

Thanks

**Comment by skorokithakis** [comment]
Hmm, yes, now that you mention it I've seen this happen for me as well, and I had to retry. I glanced at the PyChromecast code and didn't see a timeout parameter, so it might not be user-configurable, but I might be wrong.

**Comment by vext01** [comment]
It looks like [there is a hardcoded timeout](https://github.com/skorokithakis/catt/blob/6e516767cdc163177d9b08ad4d5b86de1b373ded/catt/cli.py#L233) of 10 seconds.

Perhaps this should be configurable in the config file, or at least (in the short term) bumped up to a higher value.

**Comment by skorokithakis** [comment]
Oops, thanks, I missed that. Yes, turning that up to 30 seconds can't hurt, I wouldn't want it as a config option as it's not that important to be able to tweak it away from 30 seconds... Can you change the parameter locally and see if it helps?

**Comment by vext01** [comment]
I'll try it later and get back to you.
