### ISSUE TITLE
Being cast to different device

### ISSUE THREAD

**Issue by mutlucan96** [skorokithakis/catt#296]
![Screenshot 2020-09-22 at 18 09 32](https://user-images.githubusercontent.com/42113538/93901503-40aa8b00-fcff-11ea-90e0-75ccd3b21d93.png)

As you can see I type to cast on "Nest Hub" and instead it cast to "Nest Mini" which is also visible in console output.
Also, for example if I try to cast "Nest Mini" it casts to "Chromecast" instead.

It was working fine when I first installed. I'm not sure but the problem happened after I restarted my router (IP addresses may have changed). I restarted the Pi and problem solved. I'm opening this issue thinking may help to solve a potential bug.

**Comment by theychx** [comment]
Thank you for reporting this! It's not a bug though, but rather a deficiency of the current connecting scheme.
(you can use the `--delete-cache` option to clear the discovery cache and thus force re-discovery).

But anyway, the next release of `catt` will be cache-less, so this issue will be resolved as a nice side-effect.
