### ISSUE TITLE
Live stream not playing

### ISSUE THREAD

**Issue by sischnei** [skorokithakis/catt#298]
catt is great :-) However I'd like to play a live stream / radio station which does not seem to be working.

/home/simon/.local/bin/catt cast "https://www.youtube.com/watch?v=21X5lGlDOfg"
Warning: The Youtube app is not available for this device.
Casting remote file https://www.youtube.com/watch?v=21X5lGlDOfg...
Playing "NASA Live: Official Stream of NASA TV" on "Wohnzimmer Mini"...

Anything I can do to debug this? I tried to see if there is a debug/verbose option but the help indicates none.

**Comment by skorokithakis** [comment]
Hmm, I just tried this and it works fine for me, is it a Chromecast you're trying to cast to?

**Comment by mew1033** [comment]
I'm having this problem as well...
