### ISSUE TITLE
Subtitle size?

### ISSUE THREAD

**Issue by aziztcf** [skorokithakis/catt#299]
Since I can't be arsed to buy glasses I could use a feature to increase the subtitle font size. How hard would this be to implement? 

https://css-tricks.com/improving-video-accessibility-with-webvtt/

Would this stuff apply here? Can you simply insert some kinda style block in the subfile?

**Comment by theychx** [comment]
> How hard would this be to implement?

There's doesn't appear to be a way to set font size in the `Default Media Receiver` (the chromecast app we target for all non-YouTube content) from [`PyChromecast`](https://github.com/home-assistant-libs/pychromecast). My knowledge of the official [Cast SDK](https://developers.google.com/cast/docs/reference) is very limited, so I don't know if this is a limitation of `PyChromecast` or the default cc-app.

The [controllers](https://github.com/home-assistant-libs/pychromecast#adding-support-for-extra-namespaces) included with `PyChromecast`, includes [this](https://github.com/home-assistant-libs/pychromecast/blob/b022fb89f9f5a165b2171b724b9127a03be0c44d/pychromecast/controllers/yleareena.py) controller that appears to manipulate some subtitles properties in the targeted app.

So to answer your question: Not very easy. At best, we're probably looking at significant contributions to `PyChromecast`, before this kind of functionality can be included in `catt`.

**Comment by nimatrueway** [comment]
[**pychromecast**/.../media.py#L491C5-L491C5](https://github.com/home-assistant-libs/pychromecast/blob/f095de6ae12ad9ec72379ed2dc0a6ceeab083ce8/pychromecast/controllers/media.py#L491C5-L491C5 ) relies on its own defaults

```
media["textTrackStyle"] = {
    "backgroundColor": "#FFFFFF00",
    "edgeType": "OUTLINE",
    "edgeColor": "#000000FF",
}
```

Ideally this would have been configurable but I guess this can be patched on the user's laptop if they wish to.

[**castnow**/.../subtitles.js#L47](https://github.com/xat/castnow/blob/0e1746bf3ac1bbcdd9d510277d7df2c930c070ac/plugins/subtitles.js#L47) library has a pretty decent styling that can be adopted

```
  ctx.options.playlist[0].media.textTrackStyle = {
    backgroundColor: '#00000000',
    foregroundColor: ctx.options['subtitle-color'] || '#FFFF00FF',
    edgeType: 'OUTLINE',
    edgeColor: '#000000FF',
    fontScale: ctx.options['subtitle-scale'],
    fontStyle: 'NORMAL',
    fontFamily: 'Droid Sans',
    fontGenericFamily: 'SANS_SERIF',
    windowColor: '#AA00FFFF',
    windowRoundedCornerRadius: 10,
    windowType: 'NONE'
  };
```

**Comment by skorokithakis** [comment]
Hm, that's a good point, @nimatrueway. Maybe we should add this to the README?
