### ISSUE TITLE
Twitch casting stopped working?

### ISSUE THREAD

**Issue by SashaRyder** [skorokithakis/catt#301]
Hi,

Recently twitch has just stopped working, my chromecast gets presented with a casting icon but it eventually just times out. Wondering if theres a fix already.

Thanks!

**Comment by theychx** [comment]
Thank you for reporting this. There doesn't seem to be any problem with the `youtube-dl` extractor, so we'll have to investigate further. I noticed that the short clips still work.

**Comment by theychx** [comment]
It appears to be working again, so it must have been the extractor after all.
