### ISSUE TITLE
README: mention UIs

### ISSUE THREAD

**Issue by akvadrako** [skorokithakis/catt#305]
I have found that catt to be the best working of the chromecast clients, but a video player really needs a UI for seeking, selecting subtitles, etc...

I am aware of `catt-qt` but I wonder if there are other UIs developed. It would be helpful to new users if there were links to them in the README.

**Comment by skorokithakis** [comment]
Hmm, I'm not really aware of any others, to be honest...

**Comment by theychx** [comment]
@skorokithakis Neither am I, should we update the readme, or just close this ticket?

**Comment by skorokithakis** [comment]
We could add a mention to catt-qt I guess, but it's only one and it doesn't merit a whole list, so I'm ambivalent. I'll close the ticket and leave the update up to you, @theychx.
