### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Drealine** [skorokithakis/catt#312]
Hi,

To bypass timeout of Google cast (10min), it is possible to reload cast without "Dashcast" screen ? 

Thank's a lot.

**Comment by skorokithakis** [comment]
I think @theychx is more knowledgeable than me on this, maybe he'll know.

**Comment by theychx** [comment]
> it is possible to reload cast without "Dashcast" screen ?

Currently, no. My response to #293 also applies here.
