### ISSUE TITLE
Request: Turn off device.

### ISSUE THREAD

**Issue by NeoRanga** [skorokithakis/catt#315]
The option to send a command to a device to turn it off.

**Comment by skorokithakis** [comment]
I don't think this is actually possible. Can you do this from any other app?

**Comment by NeoRanga** [comment]
It is possible from  the google home app and google assistant.  "Turn off device..."

**Comment by skorokithakis** [comment]
Ah, we'll look into that then, thanks.

**Comment by NeoRanga** [comment]
Thank you!

**Comment by skorokithakis** [comment]
Looks like the [PyChromecast functionality](https://github.com/home-assistant-libs/pychromecast/issues/196) required for this isn't looking great.

**Comment by NeoRanga** [comment]
Ah, too bad.
