### ISSUE TITLE
Problem: cannot find Chromecast devices anymore

### ISSUE THREAD

**Issue by brainhunts** [skorokithakis/catt#316]
As of this week (first week of January 2021), Catt stopped working. It doesn't recognize the Chromecast devices anymore and also a 'catt scan' command, generates  "Error: No devices found."
I have both a Google Nest hub and a Google Nest Hub Max.
Any thoughts/suggestions?

**Comment by skorokithakis** [comment]
Hmm, I haven't managed to debug this, but scanning fails for me as well. It works if I specify the IP directly, I should try upgrading Pychromecast to see if it works.

**Comment by theychx** [comment]
Still works for me. (All dependencies are latest version)

**Comment by skorokithakis** [comment]
@brainhunts Does YouTube and other apps work? Mine won't discover the Chromecast either, so I don't think it's a catt issue (at least mine).

**Comment by brainhunts** [comment]
Thanks you for your help.

Did indeed need to reset the router to get everything working properly
again. Strange, since I didn't change anything in the meantime.

One other, but small question: any thoughts on how I can show a website
only for say a minute?

Op vr 8 jan. 2021 om 21:15 schreef Stavros Korokithakis <
notifications@github.com>:
