### ISSUE TITLE
Chromecast gives black screen, but sound plays correctly

### ISSUE THREAD

**Issue by jtrudel** [skorokithakis/catt#317]
I'm really not sure what is the cause of this. I've had the same issue with VLC Chromecast basically, but tried all the fixes I found online and none of them worked.

I'm using Arch Linux, installed CATT v0.12.0

I've tried casting .mkv and .mp4 files, both with the same result. The sound plays correctly, but the video output is a simple black screen.

I tested with chromium and I don't have any issue with video or audio.

**Comment by skorokithakis** [comment]
Does casting directly from YouTube work?

**Comment by jtrudel** [comment]
I just tested and it does work fine directly from YouTube. The problem only occurs when I try to cast local files.

**Comment by skorokithakis** [comment]
I would guess that the video format isn't compatible with your Chromecast.

**Comment by jtrudel** [comment]
Well you were right. Through further investigation, both files I tried had the HEVC codec (H265) which isn't supported by Chromecast. I'll close the issue.
