### ISSUE TITLE
Cast audio only from YouTube?

### ISSUE THREAD

**Issue by thehijacker** [skorokithakis/catt#321]
Hello,

Sorry if this has been answered somewhere but I just can not find it and my memory is not like it used to be.

When I first tried catt I am pretty sure that when I tried to cast YouTube URL to my Google Nest Mini or Google Nest Audio, only audio played. Now when I try it the device starts (blink sound) but nothing is played.

Casting same YouTube URL to my Google Nest Hub works, but there full video plays.

Should this work or not?

Thank you.

**Comment by theychx** [comment]
`catt cast -y "format=bestaudio" <URL>` should work.

We could add more devices to our device-detection scheme, so that the extra -y option isn't necessary. If you could post the output from `catt scan` of any audio-only device you might have, then that would be useful.

**Comment by thehijacker** [comment]
Hello,

Tried it. It works. It played audio only from the video. So happy. 

Here is output from catt scan command:

```
Scanning Chromecasts...
192.168.28.126 - Chromecast Audio - Google Inc. Chromecast Audio
192.168.28.122 - Google Bedroom - Google Inc. Google Nest Mini
192.168.28.117 - Google Cabinet - Google Inc. Google Nest Mini
192.168.28.116 - Google Kitchen - Google Inc. Google Nest Hub
192.168.28.123 - Google Lara - Google Inc. Google Nest Hub
192.168.28.115 - Google Living - Google Inc. Nest Audio
192.168.28.125 - Google Zan - Google Inc. Google Nest Hub
192.168.28.111 - KD-55XF7596 - Google Inc. BRAVIA 4K GB ATV3
192.168.28.116 - Living Group - Google Inc. Google Cast Group
192.168.28.125 - Upstairs Group - Google Inc. Google Cast Group
```

I push this from Home Assistant using shell_command. Would need to do some coding to pass -y only to audio only devices. If you can I kindly ask to add this devices, so -y parameter is not needed. 

Thank you very much.

**Comment by thehijacker** [comment]
So audio only devices are:

```
Google Inc. Chromecast Audio
Google Inc. Google Nest Mini
Google Inc. Nest Audio
```

I was lucky to find Chromecast Audio in flee market. They are not sold anymore. Works great with my Logitech Z906 speaker with optical input.

Let me know if you need any more details.

Thank you.

**Comment by theychx** [comment]
> We could add more devices to our device-detection scheme, so that the extra -y option isn't necessary.

As it happens, we are letting `PyChromecast` decide which devices are audio-only (forgot about that). But the required changes have now been accepted upstream, so you just need to update `PyChromecast` to `8.0.0` to fix this.

**Comment by skorokithakis** [comment]
Fantastic, should we pin our requirement to that version so the next release autoupdates people's installations?

**Comment by theychx** [comment]
@skorokithakis Fine with me.
