### ISSUE TITLE
Just questions

### ISSUE THREAD

**Issue by leifnel** [skorokithakis/catt#322]
1: does catt do anything to keep cast_site running? 
If I run catt from linux, the website seems to keep running indefinitely, great for info screens..
However, belive it or not, not everybody have a linux machine handy.
There are apps to do the same on android, however they all seem to close the browser in the chromecast when I close the app, so the TV goes back to the pause screen when I close the app. Even if I disconnect the phone from wifi, the TV still stops.
Is it just a matter of finding an app. which doesn't force the chromecast to stop when closing the app, or id there some part of catt which run in the background?

2: Is there a catt for windows? Casting a chrome tab from a windows PC still leaves the problem that the rendering is done on the PC, which then have to stay running at the site.

3: Does the browser in the new chrome tv-stick have a higher resolution than the "lowres" from the regular chromecast?

**Comment by skorokithakis** [comment]
1. No part of catt runs in the background, it exits when you see iti exit.
2. It should work on Windows, yes.
3. I'm not sure about that, unfortunately.

**Comment by leifnel** [comment]
Just to inform: Catt indeed can run and work under Windows 10.

Indeed, it can be installed on Android, even run, but alas Catt scan show no devices.

**Comment by skorokithakis** [comment]
Hmm, I think that depends on your setup, because it shows devices on my phone just fine. There are some general scanning issues that may also affect it. Thanks for the update!
