### ISSUE TITLE
Slow on RPI 3B. Run as daemon?

### ISSUE THREAD

**Issue by av01d** [skorokithakis/catt#327]
I recently started playing with catt, and boy is it a lot of fun to start Rick Astley video's all over the house ;-)
catt is installed on my Raspberry Pi 3B. It works very well, but executing a command like 
`catt -d '192.168.1.xx' cast 'https://youtu.be/dQw4w9WgXcQ'` takes about 10 (!!!) seconds to run. Other commands like `stop`, or `volumeup` or `volumedown` still take about 5 seconds.

I guess that under the hood a lot of stuff happens before catt can actually send a command to a Nest hub?
Would it be an idea to run catt as a daemon, and send commands to that daemon?
Just an idea, no idea whether it's feasible, but I would love a faster catt.

**Comment by skorokithakis** [comment]
Loading catt doesn't really take that long, most of the time is spent loading stuff from the network. As such, running as a daemon wouldn't really do much to speed it up, I'm afraid...
