### ISSUE TITLE
Save and restore for tuneIn and spotify

### ISSUE THREAD

**Issue by mcikosos** [skorokithakis/catt#329]
Is it possible to add support for tuneIn and spotify for save/restore commands ?
What I want to achieveis to get back to the stream that was playing before cast command.
BTW: great project :)

**Comment by mcikosos** [comment]
I get 
"Saving state of this kind of content is not supported" while trying to call save when tunein is streaming
so it looks like there is no cst.save_capability

**Comment by theychx** [comment]
TuneIn and Spotify use their own custom chromecast apps, so support for save/restore requires custom `pychromecast` controllers that know how to communicate with these apps.
AFAIK no such controller exists for TuneIn. A controller for Spotify is actually included in `pychromecast`, but looking at the code it does not seem to be capable of initiating playback of content.
