### ISSUE TITLE
Add Error: This action is not supported by the default controller

### ISSUE THREAD

**Issue by dmanojbaba** [skorokithakis/catt#333]
Hello, 
First of all, thanks for this wonderful app.
Please pardon my ignorance, I could not find a solution for this error anywhere, hence raising it as a issue.

I am using Raspberry Pi and cast to Google Home Mini.
I have 'cast' a youtube video URL and it is playing fine. 
Then I am issuing an 'add' command and I get the below error message.
**Error: This action is not supported by the default controller.**

Please suggest.

**Comment by theychx** [comment]
The problem is that Google does not make the YouTube chromecast app available to your Home Mini (and other audio-only devices). And because of this, `catt` is defaulting to a generic chromecast app. Queing is currently not supported with this app, hence the error message you are getting.
