### ISSUE TITLE
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Resting Cat

### ISSUE THREAD

**Issue by Electronlibre2012** [skorokithakis/catt#334]
Hello,

sorry to bother you, i have this error message in Home Assistant : 
```
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Resting Cat
```
Is there a way to solve this please?

Thanks

**Comment by skorokithakis** [comment]
Please file this bug with Home Assistant, thanks!

**Comment by Electronlibre2012** [comment]
lol, one moderator @nickrout say : "That should be done via github issues."

what can i do i on the HA side they tell me that and on your side you tell me to see with HA...

sorry but it mean dead end for me.

**Comment by skorokithakis** [comment]
They told you to file an issue on the HA GitHub. This is an unrelated project.

**Comment by Electronlibre2012** [comment]
ok, i havent understand sorry

**Comment by skorokithakis** [comment]
The message says something about Resting Cat, I don't know what that is, but it's not this project.

**Comment by theychx** [comment]
![](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fkittentoob.com%2Fwp-content%2Fuploads%2F2017%2F02%2Fsleeping-cat-2.jpg&f=1&nofb=1)

**Comment by skorokithakis** [comment]
Hahaha that looks uncomfortable.
