### ISSUE TITLE
Google cast stopping after 10 minutes, option DashCast works?

### ISSUE THREAD

**Issue by dannymertens** [skorokithakis/catt#335]
Hi,

To be honest I have no idea if this is relevant, but if I cast something then I see a screenshot of DashCast now I see this in there issues list, would this be an option for the 10 minute problem with the Google hubs?

I was running into the same issue. In the Google Docs it says you can use `disableIdleTimeout`. So I am trying this:

`window.castReceiverManager.start({statusText: "Application is starting", disableIdleTimeout: true});`

Replace line 163 in receiver.html with the above. I am not 100% sure that it works, but according to the docs it should.

https://github.com/stestagg/dashcast/issues/12

If not please forget and close the issue, but hey always nice to test I think?

**Comment by scooper1** [comment]
10 minutes is normal for cast to Google  it on the Google hub side
I use a 10 minute timer to recast

**Comment by theychx** [comment]
Given that the the root problem is with device firmware, and that a sane workaround would have to be implemented on the chromecast-app side, this is currently out of scope.
