### ISSUE TITLE
Can't cast Spotify playlist

### ISSUE THREAD

**Issue by JordiBoerman** [skorokithakis/catt#336]
I can't seem to find any way to cast Spotify playlists

Example:

catt -d Speakers cast https://open.spotify.com/playlist/37i9dQZF1DWUbycBFSWTh7?si=dd9e54e2640a4b27
ERROR: Unsupported URL: https://open.spotify.com/playlist/37i9dQZF1DWUbycBFSWTh7?si=dd9e54e2640a4b27
Error: Remote resource not found.

Any URL modification gives the same result

**Comment by theychx** [comment]
Currently, only Spotify Podcasts are supported.
