### ISSUE TITLE
Disabling subtitles on Youtube videos.

### ISSUE THREAD

**Issue by Sleuth56** [skorokithakis/catt#342]
Hello, I'm very new to this application. I just downloaded it last night and I really like it. It's nice for people that don't want to use chrome but own a chrome cast. Every time I play a Youtube video it displays the subtitles. And the only option that remotely looked like it would disable them was `--no-subs`. But that didn't seem to work. I tried on these two videos.
```
catt cast --no-subs "https://www.youtube.com/watch?v=j5v8D-alAKE"
catt cast "https://www.youtube.com/watch?v=t-_VPRCtiUg" --no-subs
```
The first one both with and without `--no-subs` and the second only with `--no-subs`. Is this the correct option? If so it's not working.

**Comment by theychx** [comment]
At this point, `--no-subs` only is for disabling `catt`s search-for-subs-in-videofile-folder functionality.
It would be nice to have though, so lets keep this issue open.

**Comment by chapmanjacobd** [comment]
I believe you can create an empty text file and tell catt to use that sub file:

```sh
touch /tmp/sub.srt
catt cast -s /tmp/sub.srt https://utbe/link?v=u373u4urdu
```
