### ISSUE TITLE
Not loading local .mp4  

### ISSUE THREAD

**Issue by Ernstwys86** [skorokithakis/catt#344]
I am getting the loading screen whenever i want to load a .mp4

catt -d "Office" cast "./video.mp4"

Wonder if there is a solution for this. .jpg works fine though.

Anybody experience?

**Comment by skorokithakis** [comment]
Hmm, why the double dash? Just `video.mp4` should work.

**Comment by Ernstwys86** [comment]
my bad.. typo!

**Comment by skorokithakis** [comment]
Hmm, that's odd, that should work.

**Comment by Ernstwys86** [comment]
playing around with the permission.. but no succes

**Comment by Ernstwys86** [comment]
> Hmm, that's odd, that should work.

Tried it with another device.. it worked !! Any idea how to find out the current does not work?

**Comment by skorokithakis** [comment]
I'm afraid not, but it sounds more of a device problem than a catt problem... I'll close the ticket, but feel free to reopen if you do pinpoint the problem on catt's side!

**Comment by Ernstwys86** [comment]
Totally true.. all works fine! Thanks for the quick reply
