### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TechBrain64** [skorokithakis/catt#346]
Given the current features of catt, does it offer the capability to cast a security camera stream (RTSP) to a chromecast enabled TV?
If not, I think that would make a great addition to the Home Assistant/Automation community.

**Comment by skorokithakis** [comment]
I'm fairly sure I cast my camera, though it may have been a MJPEG stream. Can you try and let us know if RTSP works?

**Comment by theychx** [comment]
This is not possible without transcoding the stream, which currently is out of scope for this project.
