### ISSUE TITLE
issues with spaces in Device names ? 

### ISSUE THREAD

**Issue by omgbox** [skorokithakis/catt#350]
i have a device named "Chromecast1290 TV"  unable to cast using device name, My Stick is the First Gen Chromecast. 

> C:\Users\zerocool>catt set_default 'Chromecast1290 TV'
Usage: catt set_default [OPTIONS]
Try 'catt set_default -h' for help.

Error: Got unexpected extra arguments ('Chromecast1290 TV')

C:\Users\zerocool>catt set_default 'Chromecast1290 TV - Google Inc. Chromecast'
Usage: catt set_default [OPTIONS]
Try 'catt set_default -h' for help.

Error: Got unexpected extra arguments ('Chromecast1290 TV - Google Inc. Chromecast')

C:\Users\zerocool>catt set_default '192.168.1.101'
Usage: catt set_default [OPTIONS]
Try 'catt set_default -h' for help.

Error: Got unexpected extra argument ('192.168.1.101')

any help would be cool

**Comment by skorokithakis** [comment]
Yes, this is bad UX on our part. Currently, you need to run `catt set_default -d 192.168.1.101`, but we need to change that.

**Comment by omgbox** [comment]
> catt set_default -d 192.168.1.101

`catt set_default -d 192.168.1.101
Usage: catt set_default [OPTIONS]
Try 'catt set_default -h' for help.

Error: no such option: -d
`
what a strange error, does not seem to work i have even reinstalled python3 and rebooted.  what might be the issue last week it was working perfectly i can only think chromecast firmware maybe is updated with is blocking it.

**Comment by omgbox** [comment]
more errors

`ERROR: Unable to download webpage: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it> (caused by URLError(ConnectionRefusedError(10061, 'No connection could be made because the target machine actively refused it', None, 10061, None)))
Error: Remote resource not found.`

**Comment by skorokithakis** [comment]
This doesn't seem to be caused by `catt`.

**Comment by jtonk** [comment]
Do you by any chance run a Unifi network? I've had the same error a while ago and could partially trace it down to a multicast issue. A reboot of the network and the chromecast solved it for me. Couldn't reproduce it so I'm still not sure what it was.

**Comment by omgbox** [comment]
> Do you by any chance run a Unifi network? I've had the same error a while ago and could partially trace it down to a multicast issue. A reboot of the network and the chromecast solved it for me. Couldn't reproduce it so I'm still not sure what it was.

not at all, just a standard 2.4gh wireless

**Comment by theychx** [comment]
-d is an option to catt itself, not the set_default subcommand. So the correct syntax is:
```
catt -d <name_or_ip> set_default
```

**Comment by skorokithakis** [comment]
Oops, you are correct.

**Comment by omgbox** [comment]
there appears to be an issue with catt, i have tested with 
https://www.npmjs.com/package/chromecast-cli and https://github.com/vishen/go-chromecast without issues.

**Comment by omgbox** [comment]
my apologies guys, it's working perfectly i had my windows proxy turned on and could not connect to chromecast through it. now it's off everything works what a silly mistake. many thanks for your help. i will close this now.
