### ISSUE TITLE
`make dist` error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by mjsir911** [skorokithakis/catt#352]
Hi,

on `make dist`, I get this error:

```
python setup.py bdist_wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
make: *** [Makefile:80: dist] Error 1
```

I realize I don't actually need to *do* this, but currently that entire make target is broken.

```
$ python --version
Python 3.9.6
```

**Comment by skorokithakis** [comment]
Ah, thanks for that. Maybe I should just remove the Makefile, I never use it...

**Comment by mjsir911** [comment]
That sounds like a good idea @skorokithakis, it would be a bit less misleading and would hint to users that `setup.py` is the canonical way to install this with a local clone.

**Comment by skorokithakis** [comment]
Done, thanks!
