### ISSUE TITLE
Characters in aliases are converted to lower case

### ISSUE THREAD

**Issue by rikis-salazar** [skorokithakis/catt#366]
First of all, thank you very much for all the effort that goes into this project. I'm sure there are a lot of users like me that really appreciate it.

Today I installed `catt` in my laptop running Arch Linux via `pipx` -- as described in the project main _readme_ file. The installation was successful and I proceeded to scan my network:

```
[user_name@arch-laptop ~]$ catt --version
catt v0.12.2, Zaniest Zapper.
[user_name@arch-laptop ~]$ catt scan
Scanning Chromecasts...
192.168.1.xx - Chromecasts - Google Inc. Google Cast Group
192.168.1.xx - Fake Name One - Google Inc. Chromecast
192.168.1.yy - Fake Name Two - Google Inc. Chromecast
192.168.1.zz - Tercer Nombre Falso - Google Inc. Chromecast
```

Next, I tried setting up an alias for my devices...

```
[user_name@arch-laptop ~]$ catt -d Fake\ Name\ One set_alias FakeOne
...
```

and tried to cast a video; but I was met with an error that puzzled me for a little while:

```
[user_name@arch-laptop ~]$ catt -d FakeOne cast ./sample_vid.mp4 
Error: Specified device "FakeOne" not found.
```

It wasn't until I fiddled with `catt.cfg` that I realized the issue lies with the writing of _alias_ to this file: upper case letters are converted to lower case.

```
[user_name@arch-laptop ~]$ cat .config/catt/catt.cfg 
[options]
device = Fake Name One

[aliases]
fakeone = Fake Name One
faketwo = Fake Name Two
falsotres = Tercer Nombre Falso
```

I reckon this is caused by the call to the  `ConfigParser` class in `catt/cli.py`.  I also reckon this is a non-issue for _windows_ users.

May I suggest (maybe as a temporary fix) a small change to the description of `set_alias`.

```
[user_nam@arch-laptop ~]$ catt -h
...
  set_alias     Set an alias name for the selected device. Characters in alias are converted to lower case.
...
```

**Comment by skorokithakis** [comment]
Hmm, I'll look into this, thanks for the heads up!

**Comment by rikis-salazar** [comment]
Thanks. I tried to come up with a fix and issue a pull request... but I know next to nothing about python.

**Comment by skorokithakis** [comment]
That's OK, it sounds like it'll be a simple fix.

**Comment by rikis-salazar** [comment]
Thanks for the fix. May I also suggest modifying the `set_alias` description.

```
set_alias     Set an alias name (case insensitive) for the selected device.
```

**Comment by skorokithakis** [comment]
Isn't that kind of the default? That's what you expected in the first place, for example.

**Comment by skorokithakis** [comment]
Hmm yes, that makes sense. I'll change the description, thank you!
