### ISSUE TITLE
Fix yt-dlp support

### ISSUE THREAD

**Issue by skorokithakis** [skorokithakis/catt#367]
Actually, it seems fe9097565767e255b146b5ad35f5a7486c5fa922 needs a fixup to port `stream_info.py` (and also `test_catt.py`) to use `yt-dlp`.

Here are the docs for that: https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp, and this is the most relevant bit:

> **Tip**: If you are porting your code from youtube-dl to yt-dlp, one important point to look out for is that we do not guarantee the return value of `YoutubeDL.extract_info` to be json serializable, or even be a dictionary. It will be dictionary-like, but if you want to ensure it is a serializable dictionary, pass it through `YoutubeDL.sanitize_info` as shown in the example above

_Originally posted by @FranciscoPombal in https://github.com/skorokithakis/catt/issues/354#issuecomment-991135771_

**Comment by anthonyrocom** [comment]
The latest Docker build fails with the error below:

FROM python:3.7
RUN pip install catt

Running catt results in:

```
Traceback (most recent call last):
  File "/usr/local/bin/catt", line 5, in <module>
    from catt.cli import main
  File "/usr/local/lib/python3.7/site-packages/catt/cli.py", line 14, in <module>
    from .controllers import CastState
  File "/usr/local/lib/python3.7/site-packages/catt/controllers.py", line 22, in <module>
    from .stream_info import StreamInfo
  File "/usr/local/lib/python3.7/site-packages/catt/stream_info.py", line 4, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'
Traceback (most recent call last):
  File "/usr/local/bin/catt", line 5, in <module>
    from catt.cli import main
  File "/usr/local/lib/python3.7/site-packages/catt/cli.py", line 14, in <module>
    from .controllers import CastState
  File "/usr/local/lib/python3.7/site-packages/catt/controllers.py", line 22, in <module>
    from .stream_info import StreamInfo
  File "/usr/local/lib/python3.7/site-packages/catt/stream_info.py", line 4, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'
```

**Comment by anthonyrocom** [comment]
@skorokithakis a new "pipx install catt" also fails with the same error.

**Comment by skorokithakis** [comment]
Ah, damn it. I didn't realize we had changed the dependency. Can you perhaps make a PR, @anthonyrocom? I'll cut a new release afterwards.

**Comment by anthonyrocom** [comment]
Hey @skorokithakis I didn't mean to leave you hanging. I haven't had time to analyze the changes needed. For anyone who needs it, you can RUN pip install youtube-dl before RUN pip install catt if you're building your Dockerfile.

I'll see if I can get a PR done at the end of this week.

**Comment by skorokithakis** [comment]
Oh, no problem. However, youtube-dl is discontinued and probably doesn't work with many sites. We're switching over to yt-dlp, so I don't know if the workaround you mention in your comment would actually work.

**Comment by theychx** [comment]
@skorokithakis

> youtube-dl is discontinued

Is this official?

**Comment by skorokithakis** [comment]
@theychx I don't know about official, it hasn't had any activity since July so I'd say that's as official as it's going to get...

**Comment by anthonyrocom** [comment]
My workaround makes catt run again but it doesn't mean YouTube or other links will cast 😅 I am streaming a local source so I wasn't thinking of it.

It's a good call seeing youtube-dl as inactive since they previously had a monthly or more often release cadence.

**Comment by theychx** [comment]
@skorokithakis 

The main `youtube-dl` maintainer just resurfaced from his hiatus, and made a fresh release. So I suggest we switch back to `youtube-dl`.

**Comment by skorokithakis** [comment]
Hmm, that's very interesting, has he said if he's going to be maintaining it? I don't know if he's just going to go away again...

**Comment by skorokithakis** [comment]
#369 relates to this.

**Comment by anthonyrocom** [comment]
I just finished the pull request too :D

**Comment by skorokithakis** [comment]
Haha, yes, excellent timing :P By the way, as per the comment above, I think `extract_info` needs to be passed through `sanitize_info` first. I'm not entirely sure if we serialize it (I think not), but it can't hurt...

**Comment by anthonyrocom** [comment]
I also noticed you just updated catt/cli.py so I'm out of date too.

**Comment by anthonyrocom** [comment]
Maybe we need to choose youtube-dl or yt-dlp, one or the other for now because right now the build is broken if you don't have youtube-dl installed.

**Comment by skorokithakis** [comment]
> I also noticed you just updated catt/cli.py so I'm out of date too.

That shouldn't be an issue, your code has no conflicts.

> Maybe we just need to choose youtube-dl or yt-dlp, one or the other for now, because right now the build is broken if you don't have youtube-dl installed. Up to you, make the call! :)

Yeah, we do need to choose one. On one hand, I'm inclined to go with the original, on the other, we know that yt-dlp is maintained, but YouTube-dl's status is unsure.

**Comment by skorokithakis** [comment]
@theychx I had a look and it seems that ytdl just released the 6-month-old code. There doesn't seem to be any new code merged or any work done, so I don't know how active the maintainer is. Given that catt is currently breaking, I think we should merge @anthonyrocom's PR and release, and we can think about switching back later if ytdl catches up to yt-dlp at some point. The latter seems to be much better maintained nowadays anyway.

**Comment by anthonyrocom** [comment]
I agree with going to yt-dlp right now because you have the agility to easily switch. Right now that's the well maintained project.

**Comment by skorokithakis** [comment]
Looks like ytdl is officially dead, at least for now: https://github.com/ytdl-org/youtube-dl/commit/21b759057502c6e70d51011cfb3fb86d84055182

**Comment by skorokithakis** [comment]
The tests are failing. I did some work on this in a branch, but yt-dlp seems to have changed a few things related to finding the best format and I need to figure out how to do that before we can release a fixed version...

**Comment by anthonyrocom** [comment]
Hey @skorokithakis sorry, I've been offline due to holidays. Anything I can help with? I admit I did a simple test but nothing more extensive. Is test_catt.py not passing?

**Comment by skorokithakis** [comment]
Ah, no problem. Yes, the tests are failing, but I haven't managed to figure out why. It seems to be because they changed the format specifiers, but I didn't look into it more.
