### ISSUE TITLE
Cast site resolution settings

### ISSUE THREAD

**Issue by foraone** [skorokithakis/catt#372]
Is it possible to set resolution for cast site? I found only this mention in README:

```
Please note that the Chromecast has a slow CPU but a reasonably recent version of Google Chrome. The display resolution is 1280x720.
```

It doesn't look good when casting site to 4k display

**Comment by skorokithakis** [comment]
What kind of Chromecast do you have?

**Comment by theychx** [comment]
Nope, it is not possible, I'm afraid.
