### ISSUE TITLE
Cannot cast to display, receive SocketClient object has no attribute isAlive

### ISSUE THREAD

**Issue by darrylb83** [skorokithakis/catt#374]
OS: HomEassistant OS core-2021.12.8 (Supervised)
Ptyhon: 3.9.7
OS 5.10.88

Installed on HomeAssistant using SSH with the command:  python3 -m pip install catt==0.11.3 there were dependencies I couldn't address with HomeAssistant to get to the latest.

Trying to run : catt -d "Kitchen Display" cast_site http://192.168.11.25:8123/lovelace/security
Receive error: Attribute Error: 'SocketClient' object has no attribute 'isAlive'. 

I have rebooted the server to try and resolve with no success. Searching doesn't come up with much, so open to any suggestions. Please let me know if there is any additional information I can provide as well.

**Comment by skorokithakis** [comment]
This sounds like an issue with the dependencies, can you try with pipx or in a virtualenv?

**Comment by darrylb83** [comment]
I did a pip uninstall catt, and then did a pipx install catt. This failed. 

Pip failed to build package: pycryptodomomex.

error: command 'gcc' failed: No such file or directory. 

I then tried to install gcc, to find that no matching distro found for gcc. 

Seems the HomeAssitstant OS doesn't support gcc at least with a pipx install?

Thanks!

**Comment by skorokithakis** [comment]
That might be your issue, try installing `build-essential` and see if that fixes it. Unfortunately, non-standard OSes are not supported.
