### ISSUE TITLE
Device not found when attempting to cast

### ISSUE THREAD

**Issue by hamiltlr** [skorokithakis/catt#375]
I just installed `catt` and when I tried to cast, I got a device not found error:

```
$ catt scan
Scanning Chromecasts...
192.168.1.xxx - Bedroom TV - Google Inc. Chromecast
192.168.1.yyy - Bedroom speaker - Google Inc. Chromecast Audio
...

$ catt -d "Bedroom TV" cast https://www.youtube.com/watch?v=dQw4w9WgXcQ 
Error: Specified device "bedroom tv" not found.
```

I can however cast by entering the IP:
```
$ catt -d 192.168.1.xxx cast https://www.youtube.com/watch?v=dQw4w9WgXcQ 
Casting remote file https://www.youtube.com/watch?v=dQw4w9WgXcQ...
Playing "Rick Astley - Never Gonna Give You Up (Official Music Video)" on "Bedroom TV"...
```

It seems like the device name is being lowercased. Doing some digging, I found issue #366 which seems to be related, and this commit e52394d

I also can't set an alias to this device, or set it as default via the cli:
```
$ catt -d "Bedroom TV" set_alias bedroom
Error: Specified device "bedroom tv" not found.
$ catt -d "Bedroom TV" set_default
Error: Specified device "bedroom tv" not found.
```

However if I manually create a config and set an alias, I can use it:
```
$ cat catt.cfg 
[aliases]
bedroom = Bedroom TV
$ catt -d bedroom cast https://www.youtube.com/watch?v=dQw4w9WgXcQ 
Casting remote file https://www.youtube.com/watch?v=dQw4w9WgXcQ...
Playing "Rick Astley - Never Gonna Give You Up (Official Music Video)" on "Bedroom TV"...
```

I am running version v0.12.5

**Comment by skorokithakis** [comment]
I've run into this too sometimes, unfortunately it seems that someone will need to use Wireshark to debug this, but I can't reproduce it any more.

**Comment by hamiltlr** [comment]
I think I found the issue actually. It really is just the name getting converted to lowercase.

In `cli.py` in the [process_device function](https://github.com/skorokithakis/catt/blob/b5dbe64c71be98eceb8c97fe6a915c649f1a6998/catt/cli.py#L101):
```
    if is_ipaddress(device_desc):
        return device_desc
    else:
        if device_desc:
            device_desc = device_desc.lower()
        return aliases.get(device_desc, device_desc)
```

That is lowercasing device_desc and then if the alias is not found in the dictionary, it returns that lowercase string.

I believe something like this would fix it:
```
    if is_ipaddress(device_desc):
        return device_desc
    else:
        if device_desc:
            device_desc_lower = device_desc.lower()
        return aliases.get(device_desc_lower, device_desc)
```

**Comment by skorokithakis** [comment]
Oh hmm, this code was so that the lookup would be case-insensitive. I guess if it doesn't work while case-insensitive, we could drop that, but it seems like there could be a solution that would satisfy both requirements. Would you be willing to open a PR? I can't test this currently, unfortunately.

**Comment by hamiltlr** [comment]
Yup I'll do some testing and open a PR.

**Comment by thehijacker** [comment]
I can confirm that this change is needed so device is found. I was getting same error:

```
# catt -d 'Google Kitchen' info
Error: Specified device "google kitchen" not found.
```

With this fix the command is working again.

**Comment by skorokithakis** [comment]
Excellent, so yesterday's release is working fine for you?

**Comment by thehijacker** [comment]
I installed Catt via PIP. Did not get version with this fix.

```
# catt --version
catt v0.12.5, Zaniest Zapper.
```

**Comment by skorokithakis** [comment]
Can you try the latest version?
