### ISSUE TITLE
502: bad gateway

### ISSUE THREAD

**Issue by weemaba999** [skorokithakis/catt#379]
I get a 502: bad gateway error while trying to go to the ssh terminal after installing the addon and rebooting.

Config looks this way:

init_commands:
  - python3 -m pip install catt
packages: []
share_sessions: false
ssh:
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
  authorized_keys: []
  compatibility_mode: false
  password: secret
  sftp: false
  username: root
zsh: true

**Comment by skorokithakis** [comment]
This is a command line utility, so this doesn't sound like it applies here.
