### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by weemaba999** [skorokithakis/catt#380]
Hi,

Tried to install using pip and pip3 in hassio terminal. After a lot of success messages, I get following error and CATT has not been installed:

![image](https://user-images.githubusercontent.com/96292884/149834710-1ca699b3-d3a4-4efa-bc92-67745e5c2afc.png)

**Comment by skorokithakis** [comment]
Looks like you need to install gcc on your system for the installation to complete. Try installing build-essential.
