### ISSUE TITLE
Smooth Scrolling looks terrible 

### ISSUE THREAD

**Issue by jhamilt0n** [skorokithakis/catt#383]
Long story short, I'm casting a page I built (I'm self taught so please don't be too critical) to a Chromecast using Cast All The Things It contains the following....

 <script type="text/javascript">

/***********************************************
* IFRAME Scroller script- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
* Please keep this notice intact
* Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
***********************************************/

//specify path to your external page:
var iframesrc="livescores.htm"

//You may change most attributes of iframe tag below, such as width and height:
document.write('<iframe id="datamain" src="'+iframesrc+'" width="100%" height="100%" marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>')

</script>
And references:

<html data-kantu="1"><head><meta http-equiv="Content-Type" content="text/html; charset=windows-1252"></head><body>

<div id="datacontainer" style="position: absolute; left: 1px; top: 5px; width: 100%;" onmouseover="scrollspeed=0" onmouseout="scrollspeed=cache">

<iframe src="https://digitalpool.com/tournaments/20220124-monday-night-10-ball-tournament/scores?navigation=false" style="border: none;" name="2022/01/19 Wednesday Night 9-Ball Tournament" scrolling="no" frameborder="0" marginheight="0px" marginwidth="0px" height="1250px" width="100%" allowfullscreen></iframe>

</p></div>

<script type="text/javascript">

/***********************************************
* IFRAME Scroller script- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
* Please keep this notice intact
* Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
***********************************************/

//Specify speed of scroll. Larger=faster (ie: 5)
var scrollspeed=cache=3

//Specify intial delay before scroller starts scrolling (in miliseconds):
var initialdelay=500

function initializeScroller(){
dataobj=document.all? document.all.datacontainer : document.getElementById("datacontainer")
dataobj.style.top="5px"
setTimeout("getdataheight()", initialdelay)
}

function getdataheight(){
thelength=dataobj.offsetHeight
if (thelength==0)
setTimeout("getdataheight()",10)
else
scrollDiv()
}

function scrollDiv(){
dataobj.style.top=parseInt(dataobj.style.top)-scrollspeed+"px"
if (parseInt(dataobj.style.top)<thelength*(-1))
dataobj.style.top="5px"
setTimeout("scrollDiv()",40)
}

if (window.addEventListener)
window.addEventListener("load", initializeScroller, false)
else if (window.attachEvent)
window.attachEvent("onload", initializeScroller)
else
window.onload=initializeScroller

</script>

</body>
</html>
It looks great in a browser, but when I cast it using Cast All The Things, it takes forever to load and looks terrible. Any suggestions? I've googled until I'm blue in the face, however, because I'm self taught, I'm not even sure if I'm googling the right things to be able to smooth scroll and see something quickly without really long load times.

Any alternate suggestions? Or any suggestions to make this work seamlessly? Thanks in advance!

**Comment by skorokithakis** [comment]
Unfortunately we can't help because this isn't a CATT issue, since it appears that it casts correctly.
