### ISSUE TITLE
Issue when casting DASH stream

### ISSUE THREAD

**Issue by huynhtanloc2612** [skorokithakis/catt#386]
Hi CATT tool developers,
Thanks for creating great tool.
I have an issue when casting DASH stream (https://storage.googleapis.com/wvmedia/clear/h264/tears/tears.mpd). It shows errors as shown below
`catt cast https://storage.googleapis.com/wvmedia/clear/h264/tears/tears.mpd`
`Error: No suitable format was found.`
I tried some other DASH streams but the same errors occurred.
Please help give me some guidelines
Thanks,

**Comment by theychx** [comment]
I think this is related to the transition to `yt-dlp`. Direct URLs doesn't seem to work anymore. I'll try and have  a look this weekend.

**Comment by theychx** [comment]
I was wrong about this. Your manifest only contains audio-only or video-only streams. Casting this, requires a special receiver app on the chromecast end that is able to mux audio+video.
It would be possible to make such a receiver, as plenty of commercial services already employ these. Nobody did just yet, unfortunately.
