### ISSUE TITLE
feature request: add local streamed file filepath to `catt info`

### ISSUE THREAD

**Issue by chapmanjacobd** [skorokithakis/catt#390]
~~It would be nice if `catt` provided an interface similar to mpv's `--input-ipc-server`~~ 

Actually `catt stop` solves half of my problems:

```ahk
; autohotkey integration 🆒 
#If, GetKeyState("Alt" , "P")
 *1::Run, wsl.exe -- mpcatt,,Hide, process_id
 *2::Run, wsl.exe -- catt volumedown,,Hide
 *3::Run, wsl.exe -- catt volumeup,,Hide
 *4::Run, wsl.exe -- catt stop,,Hide
 *5::Process, Close, %process_id%
```

The other half would be solved if I could pull out the original file path for a local streamed file. Can we add that field to `catt info` ? Maybe the file path could be added to `media_metadata` before streaming starts or something ?

this is working okay as a short-term solution or if you don't want to add the filepath to the catt metadata
```fish
function mpcatt
   for file in (fd . ~/d/80_Now_Listening/ -tf | shuf -n50)
      echo "$file" > /tmp/mpcatt_playing

      catt cast "$file" &

      grep -qEi "(Microsoft|WSL)" /proc/version
      if test $status -eq 0
          sleep .9 && mpv.exe (wslpath -w "$file")
      else
          sleep .8 && mpv "$file"
      end

   end
end
```

**Comment by skorokithakis** [comment]
Hmm, what do you want to do exactly? I'm not sure what this code is.

**Comment by chapmanjacobd** [comment]
When I run `catt info` I want to be able to extract the filepath of the file currently playing from the same computer that is streaming to the CC device

**Comment by skorokithakis** [comment]
How would you do that from a separate process?
