### ISSUE TITLE
setup.py Missing When Cloning the Repo

### ISSUE THREAD

**Issue by d-air1** [skorokithakis/catt#395]
Inside the contributing.md file it references using setup.py for various things, but it is missing from the repo.

**Comment by skorokithakis** [comment]
Ah yeah, we use Poetry now. I'll update, thanks.

**Comment by d-air1** [comment]
No probs. Thank you for your quick response.

**Comment by skorokithakis** [comment]
Reopening until I can update the docs.

**Comment by Sugarlust** [comment]
I would like to contribute to this. Can you tell me what needs to be updated? 
I do see mention of setup.py in contributing.md . What you use currently please elaborate?

**Comment by skorokithakis** [comment]
Thanks for reminding me! I have updated the necessary bits, but it would be nice if you could run through them and see if they all work, and fix the docs of whatever doesn't. Thanks again!
