### ISSUE TITLE
TV integrated chromcast function: scan does not show it

### ISSUE THREAD

**Issue by Gunstick** [skorokithakis/catt#397]
I have a LG C1 TV, it has chromecast built in. The youtube app can cast to the TV, but catt does not see the chromecast.
Has anyone encountered this. I suppose the integrated chromecast uses a slight variation of the protocol? Maybe no answering "Im a chromecast" but rather "I'm a TV".

**Comment by theychx** [comment]
Assuming that the box running `catt` and your TV are on the same network, you could use `netdisco` for a "second opinion":
```
pip3 install netdisco
python3 -m netdisco
```

**Comment by Gunstick** [comment]
that upgraded zeroconf 0.28.8 to zeroconf-0.38.7
But still:

$ python3 -m netdisco
Discovered devices:
Discovered 0 devices

**Comment by theychx** [comment]
After googling this for a bit, it does seem as though your LG TV's chromecast implementation is quite non-standard.

We plan to fix the issues with newer versions of `pychromecast`/`zeroconf` in an upcoming release.
