### ISSUE TITLE
Feature Request - Return Status of CATT'd webpage

### ISSUE THREAD

**Issue by Tipalo** [skorokithakis/catt#408]
Greetings and thank you for this wonderful utility.

It would be useful to see a status of what is being CATT'd.  The Status command returns volume level when casting or when idle.  I would like to detect if I am CATTing a Home Assistant dashboard.

The string returned by the Info command  "status_text" or "display_name" would be nice additions to your Status command.

**Comment by theychx** [comment]
You can achieve this with:
```
catt info -j | jq .status_text
```

(you might need to install `jq`)
