### ISSUE TITLE
Some Vimeo videos do not work anymore

### ISSUE THREAD

**Issue by theychx** [skorokithakis/catt#41]
So while fiddling with tests, I discovered that the url that the format selector returns for some vimeo videos, does not play on my cc 2. Turns out that the resolution of the `"best"` format is too high.
Replacing `"best"` with `"best[width <=? 1920][height <=? 1080]"` appears to solve the problem.
The cc ultra might be able to play the higher resolution format, but I do not have access to one of those.

**Comment by skorokithakis** [comment]
Hm, the right thing to do would obviously be to detect the type of Chromecast and then select, but maybe that's too hard... I don't have a CC ultra either, but I have a Mi Box that might do. Do you have a sample video URL?

**Comment by theychx** [comment]
https://vimeo.com/225888984

**Comment by theychx** [comment]
I could do a PR for CC type detection, if I knew what special "ultra" characteristic to look for (could be either `cast_type`, `api_version` or `model_name`). In the meanwhile, I think vimeo not working is pretty annoying, so maybe for the time being, we should just force max. 1080p on everything?

Did you try the above vimeo video on your Mi Box?

**Comment by skorokithakis** [comment]
Sorry, I just tried it now. It says it's going to play, it sends the URL over but playback just fails and shows the gray screen with the Chromecast logo.

**Comment by theychx** [comment]
Yeah, same here (before #42 was merged). Please note that the resolution of the above vimeo video's `"best"` format is 4096x2160, so you might want to try if `"best[width <=? 3840][height <=? 2160]"` works.

**Comment by skorokithakis** [comment]
Yep, that works fine.

**Comment by theychx** [comment]
Interesting. What values do `cast_type`, `api_version` and `model_name` hold for your Mi Box?

**Comment by skorokithakis** [comment]
Oops, sorry, I tried current master, which wouldn't have selected `ULTRA_FORMAT`. Let me retry.

**Comment by skorokithakis** [comment]
Yeah, it picks this:

```
{
  "url": "https://skyfire.vimeocdn.com/1501853115-0xded214b91dc72acae0147c2e85d03cf890be9a0c/225888984/video/793124083/playlist.m3u8",
  "format_id": "hls-fastly_skyfire-12008",
  "ext": "mp4",
  "acodec": "mp4a.40.2",
  "tbr": 12008,
  "width": 2732,
  "vcodec": "avc1.640032",
  "format": "hls-fastly_skyfire-12008 - 2732x1440",
  "height": 1440,
  "protocol": "m3u8_native",
  "http_headers": {
    "Accept-Encoding": "gzip, deflate",
    "Accept-Language": "en-us,en;q=0.5",
    "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7",
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
  },
  "manifest_url": "https://skyfire.vimeocdn.com/1501853115-0xded214b91dc72acae0147c2e85d03cf890be9a0c/225888984/video/793124077,793124085,793124084,793124083,793124082,793124081/master.m3u8",
  "preference": null,
  "fps": 23.976
}
```

**Comment by skorokithakis** [comment]
```
Chromecast('host', port=8009, device=DeviceStatus(friendly_name='Living Room', model_name='MIBOX3', manufacturer='Xiaomi', api_version=(1, 0), uuid=UUID('uuid'), cast_type='cast'))

```

**Comment by theychx** [comment]
Looks like we'll need to use `model_name` then. I was kind of hoping for one of the other two.

**Comment by skorokithakis** [comment]
Yeah, a combination of `manufacturer` and `model_name` seems necessary... It is kind of sad that they don't advertise capabilities.

**Comment by theychx** [comment]
Why would `manufacturer` be necessary?

**Comment by skorokithakis** [comment]
To avoid conflict when two manufacturers call their products the same thing, like `("Google", "Chromecast")` and `("Chinese knockoff", "Chromecast")`.

**Comment by theychx** [comment]
Makes sense.

**Comment by theychx** [comment]
I'll do a PR for this right away.

**Comment by skorokithakis** [comment]
Thank you!
