### ISSUE TITLE
ENH: like,+1,+!: Like currently playing media

### ISSUE THREAD

**Issue by westurner** [skorokithakis/catt#415]
```bash
catt like
catt +1
catt +!
catt -d {ip|alias} +1
# INFO: {track metadata}
# INFO: wrote track metadata to ./likes.csv|./likes.yml|./likes.csvw.yamlld.yml
# DEBUG: HTTP POST to {url}/.well-known/actions/like
# (delay)
# INFO: 200 OK\n{"msg":"Like Created", "result": {"@type":"https://schema.org/LikeAction", ...}}
```

- ([ ] UBY: 'online' REPL)
  - This from 2012 wraps cmdloop for liking di.fm tracks and checking the currently-playing track metadata (without a mdns multicast event on track change): https://github.com/westurner/xbmcstreams/blob/e59de81ce6a186c03b431cd1215a96aabd2b35ef/xbmcstreams.py#L301-L313 (-2012)
    - https://github.com/vincentbernat/nodecastor :
      > You can get updated when the status of the Chromecast changes by listening to the status event:
- [ ] ENH: Chromecast: "Like API": ~ {url}/.well-known/actions/like 
  - [ ] Is there a already pan-chromecast-service API to 'Like'?
  - https://schema.org/LikeAction
  - <url>: `?action=LikeAction&`
  - These prompts currently work w/ Google Assistant on {YT, YT Music,} (2022) :
    - "Like this"
    - "Like this track"
    - https://github.com/endoplasmic/google-assistant

**Comment by skorokithakis** [comment]
I'm not sure what these notes are, please add a lot more detail describing the problem, proposed solution, etc if you want to propose something.

**Comment by westurner** [comment]
Is this specific?

```
catt -d {ip|alias} +1
# INFO: {track metadata}
# INFO: wrote track metadata to ./likes.csv|./likes.yml|./likes.csvw.yamlld.yml
# DEBUG: HTTP POST to {url}/.well-known/actions/like
# (delay)
# INFO: 200 OK\n{"msg":"Like Created", "result": {"@type":"https://schema.org/LikeAction", ...}}
```

**Comment by skorokithakis** [comment]
I don't know what that is. Can you write some prose detailing the feature of bugfix you'd like to propose?

**Comment by westurner** [comment]
I specified the desired inputs and outputs?

Users can 'like' the currently playing media content with `catt` using a `like` command conveniently aliased to `+1` and `+!`, such that downstream content hosting services can field 'LikeAction' event and record said information on behalf of their users (possibly in addition to just appending to a .csv file, pending upstream implementation to support this functionality in the Chromecast protocol(s) so that Chromecast-compatible content providers can receive 'LikeAction' W3C Web Annotations)
