### ISSUE TITLE
ENH: tcpdump: idle and log mDNS and DIAL events

### ISSUE THREAD

**Issue by westurner** [skorokithakis/catt#416]
```
catt tcpdump_all
catt tcpdump_mdns
catt tcpdump_dial
```

- [ ] DOC: `tcpdump` commands to log these
- [ ] ENH: async python implementation with logging

**Comment by skorokithakis** [comment]
I'm not sure what these notes are, please add a lot more detail describing the problem, proposed solution, etc if you want to propose something.

**Comment by westurner** [comment]
```
$ catt tcpdump
# tcpdump -Iany ...
```
