### ISSUE TITLE
[Feature request] Mute/Unmute feature

### ISSUE THREAD

**Issue by neurodiv-eric** [skorokithakis/catt#425]
I've been using Continuously Casting Dashboards, which relies on CATT for its' core functionality. It works great for what it says it does!

However, every time a dashboard is cast and re-casted, the Nest Hub device I'm using mutes (by setting volume to zero) then sets the volume back to 0.5 (5 as displayed on screen). 

This triggers the volume test tone, which is undesirable for my setup. As far as I can tell, this is a limitation of CATT, which does not utilize the set_volume_muted function provided by pychromecast. Is that something that could be implemented?

Note: I might be able to give a pull request a shot myself if that's preferable, but I try to avoid directly messing with projects I don't understand in full.

**Comment by skorokithakis** [comment]
That sounds doable, sure. It would be great if you could give a PR a shot, as you know best how to solve your specific problem, and we can review to make sure the code looks good.

Thanks!

**Comment by neurodiv-eric** [comment]
I noticed that HA 2023.5 is having issues pulling the latest CATT from PyPi. Is there potentially an issue with my PR?

**Comment by b0mbays** [comment]
Hey @neurodiv-eric , i've also noticed this and raised an issue here:

https://github.com/skorokithakis/catt/issues/428

**Comment by skorokithakis** [comment]
I'm going to close this in favor of #428, as it's also completed.
