### ISSUE TITLE
catt is not compatible with the latest release of Home Assistant (2023.5.0)

### ISSUE THREAD

**Issue by b0mbays** [skorokithakis/catt#428]
Hey, appreciate the work that has been done for this project.

Unfortunately it looks like catt is not compatible with the latest release of Home Assistant.

It looks like catt requires pychromecast ">=12.1.4, <13" but they have moved to only 13.x.

https://github.com/skorokithakis/catt/blob/585b8d2252475d94b0e693f1e45290815a251047/pyproject.toml#LL31C31-L31C31

Thank you!

**Comment by skorokithakis** [comment]
Ah, that's too bad, and I don't know how much work it would be to upgrade to PyChromecast 13, hm.

**Comment by neurodiv-eric** [comment]
I've updated my dev copy to PyChromecast v13 via Poetry. I don't see any breaking changes so far and everything looks smooth, but I only have a single setup to test with.

**Comment by b0mbays** [comment]
Appreciate the work to get this fixed, how do we get a new pip package built so I can test this out in Home Assistant? Thank you 👍
