### ISSUE TITLE
New pip package for latest changes

### ISSUE THREAD

**Issue by b0mbays** [skorokithakis/catt#430]
Hi, firstly thanks for creating such a great project.

The latest commits contain a fix so that we can use catt in Home Assistant again, however there is no pip package to use as of yet with these changes. Is it possible to publish a new package?

Thank you!

**Comment by skorokithakis** [comment]
Yep, I'll release one as soon as I can remember how!

**Comment by se-bastiaan** [comment]
https://github.com/skorokithakis/catt/blob/master/.gitlab-ci.yml#L37

Seems like it needs a poetry build and a twine upload :)

Let us know if you need help!

**Comment by skorokithakis** [comment]
Ah, I need to tag it, thanks. I'll do that now.

**Comment by b0mbays** [comment]
Thank you @skorokithakis!

**Comment by skorokithakis** [comment]
You're welcome! The auto-publishing process seems very broken, sadly, but I've uploaded a package manually. Does that work for you?

**Comment by b0mbays** [comment]
I can't check right now, but it looks like it should. I'll report back tonight 😄  thanks!

**Comment by b0mbays** [comment]
It's working great on HA, thanks again!
