### ISSUE TITLE
Update catt package (0.12.11) on PyPI to match newest commit on Github

### ISSUE THREAD

**Issue by GreatTeacherOni** [skorokithakis/catt#442]
The catt package 0.12.11 on PyPI was last updated on May 9, 2023 (see https://pypi.org/project/catt/#history)
Would it be possible to update that package to the newest commit on master?
This way you get the newest working version easily via "pip install catt".

I'm not sure if there is an easy sync function or if it is a bit of a hassle to do that, but that would be very welcome.

**Comment by skorokithakis** [comment]
Released 0.12.12, let's hope it doesn't have any bugs!
