### ISSUE TITLE
Chromecast from Firefox?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [skorokithakis/catt#448]
Hi, thanks for the project. I think, maybe it is possible to integrate with Firefox somehow? Through the browser extension? To be able to cast like from Google Chrome.

**Comment by skorokithakis** [comment]
Yes, there already exist extensions that will launch a program with the current URL as a parameter. I can't point you to a specific one, but I'm sure you can find something with a quick search.

**Comment by vitaly-zdanevich** [comment]
Not found at https://addons.mozilla.org/en-US/firefox/search/?q=catt&type=extension

![image](https://github.com/skorokithakis/catt/assets/3514015/319f3914-4eb5-43e0-9af1-ac043b3adde3)
