### ISSUE TITLE
Subtitles support

### ISSUE THREAD

**Issue by owyongsk** [skorokithakis/catt#46]
Would it be possible?

**Comment by skorokithakis** [comment]
I'm not sure, I haven't looked into it, unfortunately.

**Comment by owyongsk** [comment]
Does the ChromeCast api allow subtitles for a web URL?

**Comment by skorokithakis** [comment]
That's a good question, I think so, but I don't know. If Pychromecast has support for subtitles, it would probably be easy to implement.

**Comment by owyongsk** [comment]
Hmm, I managed to add support to another tool here, so it's possible, anyways, I got my use case figured out. Thanks!

https://github.com/owyongsk/stream2chromecast/commit/da7c239fc9d34464ab4c826090775265923ecb61

**Comment by skorokithakis** [comment]
Oh, very interesting! That doesn't seem too hard, I'll see if I can get something implemented quickly (as I need this myself too). Thanks!

**Comment by owyongsk** [comment]
Good luck, I needed this to learn Spanish in my subtitles. Haha.

**Comment by skorokithakis** [comment]
Damn! I'll keep this open, as we do need this. Thanks for the report!

**Comment by marcosdiez** [comment]
@owyongsk I checked your PR and saw that it's quite easy to add subtitles on `catt`. Thanks for the nice hint.
