### ISSUE TITLE
Catt does not support multiple casting devices

### ISSUE THREAD

**Issue by theychx** [skorokithakis/catt#5]
Hello. So I just bought a Chromecast Audio to go along with my CC2.As you know, this breaks my current setup where I use catt in several ways. So I am proposing the following:

Catt should support an option to set `-d "CCaudio"` or `-d "192.168.1.200"` to make commands specific to this device. Catt should also employ a rudimentary config file (youtube-dl style) so that the user can set a default device (or perhaps other future flags). This could go in `~/.config/catt/config` or perhaps just `~/.catt`. I am not shure how the current caching scheme fits into this, but it would certainly have to change.

Would you consider merging a PR implementing these ideas?

**Comment by skorokithakis** [comment]
Yes, definitely. This is very important, and the only reason I haven't implemented it is because I don't have a second Chromecast. As for the caching, the cache key will just have to include the device name.

**Comment by theychx** [comment]
Cool. I have some further thoughts about the cache. Consider this scenario:

I have setup my CC2 as my default device in `~/.catt`
Occasionally I would like to use catt with my CC Audio like this:
`catt -d "CCaudio" https://www.youtube.com/watch?v=SdHBkYoUXOs`
Now whenever I  want to control playback on the  CC Audio, I would have to do this:
`catt -d "CCaudio" seek 300`

Maybe instead of changing the format of the cache itself, we could change the caching mechanism so that we write to cache everytime a cast command is run. This way you could manipulate the active CC with a command like this: `catt -c seek 300`. Or is this too involved?

**Comment by skorokithakis** [comment]
I think that might be getting a bit too involved, in that it might lead to surprising behaviour because the state is no longer in the command-line options, which is probably not a good idea. Also, given that your terminal can easily autocomplete to previous commands, and that you can set the default in the preferences, I think I'm leaning towards disliking this.

However, there's no reason why there couldn't be a device alias in the preferences file, so you could do -d 1, for example.

**Comment by theychx** [comment]
Good points. I'll keep you posted

**Comment by skorokithakis** [comment]
I'm going to reopen this. Trying to use these features now, I realize that `--write-config` shouldn't be a flag, it should be a full-blown command (`catt write-config`). I'm going to reimplement it.

**Comment by theychx** [comment]
I actually implemented it like this at first, but changed my mind, as the flag seemed like the natural choice. Maybe I was wrong, as the command perhaps is more robust. What convinced you?

**Comment by skorokithakis** [comment]
The fact that you can't `write-config` without another command (e.g. `cast`), mainly. I'm going over the whole thing, trying to implement aliases, but it looks like this method can ONLY set/override click commands, not arbitrary config items. It seems that, if we want to add config items that won't be passed in the command line, we need to find another way to do it :/

Another problem is that `write_config` will be destroying the configuration, if you already have some, as it doesn't read the existing config before writing.

A third problem is that `catt` won't detect my Chromecast at all, currently.

Looks like I'm going to need to work on this a bit :/

**Comment by theychx** [comment]
> A third problem is that catt won't detect my Chromecast at all, currently.

That's strange, everything is working beautifully here

**Comment by theychx** [comment]
> It seems that, if we want to add config items that won't be passed in the command line, we need to find another way to do it :/

I'm at bit curious, what would those be?

**Comment by skorokithakis** [comment]
> That's strange, everything is working beautifully here

Ah, strike that, it turns out my Chromecast had disconnected.

> I'm at bit curious, what would those be?

Device aliases and groups, for example.

**Comment by theychx** [comment]
Looks nice. You are not checking whether the specified CC is on the network though.

**Comment by skorokithakis** [comment]
Oh, is that why that was? So it would fail if the CC wasn't found? I couldn't figure out why it was there, so I took it out, I'll readd with a comment, thanks.

**Comment by theychx** [comment]
Yeah, `catt -d mistake write_config`, would make the next `catt cast "whatever"` fail.

Another thing. Why are you doing this:?

```
except SystemError:
    from controllers import get_stream_info, CastController, Cache
    from http_server import serve_file
```

**Comment by skorokithakis** [comment]
Because if I run `python catt/cli.py <command>` without installing it, the previous imports fail, for some reason.

**Comment by theychx** [comment]
> Because if I run python catt/cli.py <command> without installing it, the previous imports fail, for some reason.

Have a look at [this](http://stackoverflow.com/questions/16981921/relative-imports-in-python-3).
Running `catt` like this: `python3 -m catt.cli cast https://youtu.be/cL43vDm1vGQ` works fine without the weird import statements.

**Comment by skorokithakis** [comment]
Ah, thanks, I removed the imports. It turns out I had this way of running `catt` in my shell history, I had just forgotten.

**Comment by theychx** [comment]
Any reason why this is still open?

**Comment by skorokithakis** [comment]
Good question... I found a branch open as well, but I can't remember where I was with this. Do you? I remember I wanted some changes to the format of the file and to the order with which device selection happens, but I can't remember if we implemented this in the end.

**Comment by theychx** [comment]
The open branch does not contain anything useful, as I believe that you created it, because of some github-related problem on your end. 
As for this issue, the only thing I can think of is that, at some point, you wanted the user to able to select cc with only partial desc. of the cc's name (which I still think is a really bad idea).

**Comment by skorokithakis** [comment]
Ah, right, thanks. I'll close this then.
