### ISSUE TITLE
Format selector question

### ISSUE THREAD

**Issue by theychx** [skorokithakis/catt#50]
https://github.com/skorokithakis/catt/blob/949e60f6ad9d87234f6b5d514cf893106e0b7cb3/catt/stream_info.py#L148

I reckon this line has been in `catt` since it's inception, and I just can't figure out why it's there. Can you remember?

**Comment by skorokithakis** [comment]
Did the list line change? I think it was a dict before, maybe? I'll need to see the commit where it was added, can I do a Git blame on GitHub?

**Comment by theychx** [comment]
> can I do a Git blame on GitHub?

I'm not shure, don't think so.

I was wondering about the `KeyError` but assumed that it was thrown by the format_selector itself.

**Comment by skorokithakis** [comment]
Possibly... I don't remember, I'm wondering if the commit that introduced this had another line in the try, and we changed that and didn't change the exception. Odd, I usually leave comments for these sorts of mysterious lines, I must have forgotten...

**Comment by theychx** [comment]
I'll dig into this.

**Comment by theychx** [comment]
Here it is:https://github.com/skorokithakis/catt/commit/d7f81c22ff9726fa575af153c1d47d51cc8e8fa3

The `KeyError` is thrown when we try to listify `format_selector(info)` (which is weird).

**Comment by theychx** [comment]
Yep, I tested it in an IPython session. It's a bit strange, you'd think that it would contain exactly one entry, in the case of a direct media-link.

**Comment by skorokithakis** [comment]
Yeah, hmm. Can you add a comment in the exception branch so we don't wonder next time?

**Comment by theychx** [comment]
I already did? Or do you want that comment to be worded differently?

**Comment by skorokithakis** [comment]
Oh bah, right, I didn't realize that PR was in the same place as what we're talking about here. I also generally tend to put the comment as the first line inside the "except", so that threw me off a bit. Never mind!

**Comment by theychx** [comment]
Haha, I thought this was the PR comments. :laughing:

**Comment by skorokithakis** [comment]
Maybe we should both take a break and reconvene tomorrow :P
