### ISSUE TITLE
YouTubeController: Error when launching youtube app

### ISSUE THREAD

**Issue by dga711** [skorokithakis/catt#56]
Hey,

I am using only your YouTubeController in an own python script.

Basically i have a NFC reader and launching videos depending on which nfc id (toy figures) is detected. (for the kid)

I have one problem, when the YouTube app is not launched on the ChromeCast yet. I get following output:

> INFO:pychromecast.controllers:Receiver:Launching app 233637DE
DEBUG:pychromecast.socket_client:Sending: Message urn:x-cast:com.google.cast.receiver from sender-0 to receiver-0: {'type': 'LAUNCH', 'requestId': 3, 'appId': '233637DE'}
Traceback (most recent call last):
  File "test_cast.py", line 51, in <module>
    yt.play_video("wOMwO5T3yT4")
  File "/_code/yt_controller.py", line 330, in play_video
    self.start_new_session(youtube_id)
  File "/_code/yt_controller.py", line 318, in start_new_session
    self.update_screen_id()
  File "/_code/yt_controller.py", line 135, in update_screen_id
    self.send_message({MESSAGE_TYPE: TYPE_GET_SCREEN_ID})
  File "/usr/local/lib/python2.7/dist-packages/PyChromecast-1.0.3-py2.7.egg/pychromecast/controllers/__init__.py", line 84, in send_message
    self.namespace, data, inc_session_id, callback_function)
  File "/usr/local/lib/python2.7/dist-packages/PyChromecast-1.0.3-py2.7.egg/pychromecast/socket_client.py", line 618, in send_app_message
    ", ".join(self.app_namespaces)))
pychromecast.error.UnsupportedNamespace: Namespace urn:x-cast:com.google.youtube.mdx is not supported by current app. Supported are urn:x-cast:com.google.cast.debugoverlay, urn:x-cast:com.google.cast.cac, urn:x-cast:com.google.cast.sse

The YT App launches but no video is played. When YT App is already launched, everything is fine.

From the trace I don't get what could be wrong. Any ideas?

Thanks in advance.

**Comment by skorokithakis** [comment]
Hmm, I've seen some races as well, where the YouTube app has to open before the video will play. I'm afraid I don't have a fix, though. @theychx?

**Comment by theychx** [comment]
Some time ago I had similar issues, but it's been pretty stable for the past several weeks. There's some session stuff going on prior to playback, and I honestly don't know what exactly that entails, as I didn't write the controller myself. YouTube might very well have changed some minor details in how the cc-app works, making the controller more unstable. The controller's author (ur1katz) hasn't been active here on Github for almost a year. The last time he pushed commits to his PyChromecast fork was Nov. 2016.

@dga711 If you could show us your script, that would be helpful.

**Comment by skorokithakis** [comment]
I wonder if it will help if we pause a bit while the YouTube app loads...

**Comment by theychx** [comment]
Yeah we could insert a crude check'n'wait in ```YoutubeCastController._prep_yt```. If that doesn't help, then I'm out of ideas.

**Comment by skorokithakis** [comment]
@dga711, can you try that and see?

**Comment by dga711** [comment]
As a quick workaround I tried manually starting the app earlier and waita bit which works.
>receiver_ctrl = self._socket_client.receiver_controller
receiver_ctrl.launch_app("233637DE")

So yeah, the same as you suggested now.

**Comment by dga711** [comment]
Oh and my script is just a few lines to test the whole youtube to chromecast thing

```casts = pychromecast.get_chromecasts()
if len(casts) == 0:
    print("No Devices Found")
    exit()
	
cast = next(cc for cc in casts if cc.device.friendly_name == "xxxxx")
if (cast is None):
	print("CaveCast Not Found")
	exit()

cast.wait()
print()
print(cast.device)

yt = youtube.YouTubeController()
cast.register_handler(yt)

yt.play_video('wOMwO5T3yT4')```

**Comment by theychx** [comment]
Closing, as this issue is not directly related to ```catt```.
@skorokithakis As I've already mentioned, youtube functionality has been very stable for me for some time now. Is it the same for you?

PS: ```skip``` stopped working a few days ago. I've fixed it in the controllers refactor PR.

**Comment by skorokithakis** [comment]
It's been okay for a while for me, yes.
