### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by theychx** [skorokithakis/catt#67]
@skorokithakis :package: :gift: :package: :gift:

**Comment by skorokithakis** [comment]
Certainly, is the latest HEAD stable enough in your tests? If so, I can release now.

**Comment by theychx** [comment]
Yeah, I've been using it as my daily driver for the past week without issue. It also passes a small test suite I've made (just a crude shell script).

**Comment by skorokithakis** [comment]
Done, thanks!

**Comment by theychx** [comment]
@skorokithakis :alarm_clock: :alarm_clock: :alarm_clock:

:smiley:

**Comment by skorokithakis** [comment]
Done! 0.5.7 is out. In other news, `semantic-release` is rather badly written, I should send them a pull request.

**Comment by skorokithakis** [comment]
It's very non-atomic, so I keep ending up with half-baked releases all the time. This time, it created the release on Github, but couldn't find the tag so it crashed and didn't upload anything on PyPI. It should check for things beforehand, and it should have the ability to repeat the same release idempotently.

I'll have to fix some things and issue a PR.

**Comment by skorokithakis** [comment]
Released, thank you!

**Comment by theychx** [comment]
@skorokithakis Remember to release ```0.6.1``` with the readconfig fix, before any of the other stuff is merged.

**Comment by theychx** [comment]
I think it's time for another release! :champagne:

**Comment by skorokithakis** [comment]
Released v0.8.0! :tada:

**Comment by theychx** [comment]
It's that time! :gift: :package:

**Comment by skorokithakis** [comment]
v0.10.0 is out!

**Comment by theychx** [comment]
Thanks!

**Comment by theychx** [comment]
https://www.youtube.com/watch?v=aDkuLZcsp-U

**Comment by skorokithakis** [comment]
[X Y L O P H O N E](https://pypi.org/project/catt/0.10.2/)

**Comment by theychx** [comment]
Thanks!

**Comment by theychx** [comment]
@skorokithakis  :package: :gift: :gift_heart: :package: It's ready!!!

**Comment by skorokithakis** [comment]
:tada:!

Wait, what do we call this one?

**Comment by theychx** [comment]
I don't know.......how about `0.11.0 Yearning Yachtman`? :smiley: :boat:

**Comment by skorokithakis** [comment]
Such an absolutely brilliant name, what a colossus of a man the namer must be.

**Comment by theychx** [comment]
Indeed :smile: , a colossus with a less that colossal memory.

**Comment by skorokithakis** [comment]
What are you guys talking about?

**Comment by theychx** [comment]
@skorokithakis 
:bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock: :bell: :alarm_clock:

**Comment by skorokithakis** [comment]
I tried yesterday but the process was a bit confusing (you can't generate the log without tagging a release and you need to generate the change log before tagging). I'll try again today.

**Comment by skorokithakis** [comment]
Released 0.11.0 Yearning Yachtman!

**Comment by theychx** [comment]
Amazing! Thanks!

**Comment by theychx** [comment]
:package: :gift: :tv: :package: :gift: :tv: :package: :gift: :tv: :package: :gift: :tv: :package: :gift: :tv: :package: :gift: :tv:

**Comment by skorokithakis** [comment]
Yes, definitely! What are we doing for names? Did we skip X?

**Comment by theychx** [comment]
> Did we skip X?

Nope (Xylophone Xtravaganza) :smiley: 
Which means, that it is my turn, and I choose "Zaniest Zapper".

**Comment by skorokithakis** [comment]
Excellent choice, sir. Let's see what the version should be...

**Comment by skorokithakis** [comment]
catt 0.12.0, Zaniest Zapper, is reality! https://pypi.org/project/catt/0.12.0/

**Comment by theychx** [comment]
Thanks!

**Comment by theychx** [comment]
Please make a new release, as new installs of `0.12.7` are currently broken because of the `protobuf` situation.

:woman_dancing: :woman_dancing: :woman_dancing:

**Comment by skorokithakis** [comment]
Done! Some items won't show up in the log, as they didn't have the required `fix:/feat:` thing in the commit, but that's probably OK.

**Comment by theychx** [comment]
Darnit, I keep forgetting that

**Comment by skorokithakis** [comment]
It's OK, I can probably add a GH action or a CI check for it.
