### ISSUE TITLE
Latest version won't execute via PHP

### ISSUE THREAD

**Issue by ouija** [skorokithakis/catt#68]
Hey,  

I've been using Cast All The Things in conjunction with a php script via IFTTT and haven't had any issues with it **until** upgrading to v0.5.3, which for some reason cannot seem to work when being called from an elevated script via php.   

The previous version works fine however, so I'm sticking with it for now, but just thought I'd mention it as I'm somewhat stumped as to why it no longer works. (I'm assuming it is some sort of permissions issue or maybe a path related issue or something like that, but as I mentioned, it runs the script as an elevated user and the previous version has no problems)

Let me know if you have any insight :)   Thanks for a great script.

**Comment by theychx** [comment]
Please check what version of pychromecast you have installed. They just released ```2.0.0```, which have python 2 support removed (In case you are using that).
If that is not the problem, then please supply some form of traceback, or other output that might have clues as to what is wrong.
Thank you for reporting!

**Comment by theychx** [comment]
@ouija I see now that I made a small mistake that prevents ```0.5.3``` from running on python 2. We'll roll out a fix ASAP.

**Comment by skorokithakis** [comment]
Oops, thanks for reporting that, @ouija!

**Comment by skorokithakis** [comment]
Released 0.5.4, please try that one and let us know if there are any more problems, thanks!

**Comment by theychx** [comment]
@ouija After upgrading, please make sure you have ```zeroconf 0.19.1``` installed. The new ```0.20.0``` version also has python 2 support removed.

**Comment by skorokithakis** [comment]
Should we specify that somewhere, perhaps? Or maybe an error message?

**Comment by theychx** [comment]
It's not our dependency, but we could of course update the README if more users struggle with this.
(We could of course make this our dependency, but that seems suboptimal)

**Comment by skorokithakis** [comment]
Oh right, it's a PyChromecast dependency, I forgot. A bit off topic, but we can set the latest PyChromecast as a dependency in our `setup.py` when installing under Python 3, and pin to the Py2-compatible version and compatible zeroconf when installing under 2.

That may be a bit too much effort for a deprecated Python version, but some users are clearly having problems with it. What do you think?

**Comment by theychx** [comment]
My preferred approach then, would be to make a final py2 compatible release with pins on whatever it needs in order to work, and then afterwards remove py2 compat code and make py3-only releases from there. I would honestly not be a fan of having to deal with py2 oddities, when one of our core dependencies no longer work with py2 anyway.

**Comment by skorokithakis** [comment]
Yeah, makes sense. We can just have 0.5.4 be the last Py2-compatible one, if it works well.

**Comment by ouija** [comment]
Hey there,

Apologies for the delay, but I had gotten it working again using the Python2 version;  However, I've recently upgraded everything to the Python3 version, and for some reason, when trying to call catt via a PHP 'shell_exec' command, it doesn't seem to work (nothing gets casted to the device).  The same script works without issues using the python2 version.

Would there be a reason why the python3 version wouldn't execute via a PHP command?
