### ISSUE TITLE
catt does not work on windows if the local file has a space in the file name or folder name

### ISSUE THREAD

**Issue by skanga** [skorokithakis/catt#72]

**Comment by theychx** [comment]
Thank you for reporting.
Are you using "Windows subsystem for Linux"?
And a trackeback would be useful.

**Comment by skanga** [comment]
Windows 7 64 bit
Python 3.5.4 :: Anaconda custom (64-bit)
I don't see a traceback. How do I get one?
It simply does not show the movie on the chromecast

**Comment by theychx** [comment]
I'm afraid I'm not familiar with that setup (I rarely use Windows myself).
What kind of movie file is it? (codec, bitrate, etc.)

**Comment by skorokithakis** [comment]
Can you at least show us how you're running the command? You haven't really provided any info at all.

**Comment by skanga** [comment]
I get the error message
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by skanga** [comment]
I run it using:
catt cast "movie name.mp4"
Will get movie/codec info for you

**Comment by skanga** [comment]
Here is a full dump.


d:\>mediainfo "d:\video\Simple Survival Life Hacks.mp4"
General
Complete name                            : d:\video\Simple Survival Life Hacks.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/iso2/mp41)
File size                                : 61.7 MiB
Duration                                 : 5 min 28 s
Overall bit rate                         : 1 577 kb/s
Writing application                      : HandBrake 0.10.1 2015030800

Video
ID                                       : 1
Format                                   : MPEG-4 Visual
Format profile                           : Simple@L1
Format settings, BVOP                    : No
Format settings, QPel                    : No
Format settings, GMC                     : No warppoints
Format settings, Matrix                  : Default (H.263)
Codec ID                                 : 20
Duration                                 : 5 min 28 s
Bit rate                                 : 1 574 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 29.970 (29970/1000) FPS
Minimum frame rate                       : 23.981 FPS
Maximum frame rate                       : 31.250 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.025
Stream size                              : 61.6 MiB (100%)
Writing library                          : Lavc55.34.1



d:\>catt cast "d:\video\Simple Survival Life Hacks.mp4"
Casting local file d:\video\Simple Survival Life Hacks.mp4...
Playing Simple Survival Life Hacks.mp4 on "Kanga TV"...
Serving local file, press Ctrl+C when done.
192.168.0.213 - - [25/Feb/2018 01:12:08] "GET / HTTP/1.1" 200 -
Traceback (most recent call last):
  File "c:\bin\anaconda3\lib\site-packages\catt\http_server.py", line 40, in do_GET
    self.wfile.write(data)
  File "c:\bin\anaconda3\lib\socket.py", line 594, in write
    return self._sock.send(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

192.168.0.213 - - [25/Feb/2018 01:12:08] "GET / HTTP/1.1" 200 -
192.168.0.213 - - [25/Feb/2018 01:12:31] "GET / HTTP/1.1" 200 -
Traceback (most recent call last):
  File "c:\bin\anaconda3\lib\site-packages\catt\http_server.py", line 40, in do_GET
    self.wfile.write(data)
  File "c:\bin\anaconda3\lib\socket.py", line 594, in write
    return self._sock.send(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host


Aborted!

d:\>

**Comment by skorokithakis** [comment]
I wonder if we just aren't URLencoding the name properly and files with spaces will break on any OS.

**Comment by theychx** [comment]
@skanga 
> Codec ID : mp42 (isom/iso2/mp41)

This codec is not supported by the chromecast. I get a similar traceback when trying to cast local files encoded with unsupported codecs. But ```catt``` should of course fail instead of crashing, so that needs fixing.

@skorokithakis 
During testing I actually got this traceback when trying to cast certain files that ARE supported. This issue seems to be related to bitrate (not sure though). I'll create a new ticket.

**Comment by skorokithakis** [comment]
Ah, thanks. I replaced my Chromecast with a Mi Box, I should check to see what codecs that supports.

**Comment by theychx** [comment]
..and the two files I use for my regular testing scheme (that DO work), both have spaces in their names.

**Comment by skanga** [comment]
Do you have a list of supported bitrates? codecs?

**Comment by theychx** [comment]
@skanga Depends on what device you have, but for Google Chromecast devices you can check [this list](https://developers.google.com/cast/docs/media).

**Comment by theychx** [comment]
Closing, as ticket title seems to be a non-issue. New local file casting issues ticket: #73
