### ISSUE TITLE
UnicodeEncodeError when accent in device name

### ISSUE THREAD

**Issue by jimbo72** [skorokithakis/catt#77]
I have to modify cli.py line 245:

click.echo("{0.host} - {0.device.friendly_name} - {0.device.manufacturer} {0.device.model_name}".format(device))

click.echo(u"{0.host} - {0.device.friendly_name} - {0.device.manufacturer} {0.device.model_name}".decode('utf-8').format(device))

in order to handle device name with accent (a lot of accent in french)

**Comment by skorokithakis** [comment]
Which Python version are you running?

**Comment by jimbo72** [comment]
Python 2.7.9

Thanks

2018-03-29 15:50 GMT+02:00 Stavros Korokithakis <notifications@github.com>:

**Comment by jimbo72** [comment]
catt is only compatible with Python 3. If you need a Python 2-compatible version, please install 0.5.6, the last py2-compatible release.

pip installed me version 0.5.5

I can't find version 0.5.6, available ?

**Comment by skorokithakis** [comment]
It's here: https://pypi.python.org/pypi/catt

**Comment by skorokithakis** [comment]
Can you try:

```
click.echo("{0.host} - {0.device.friendly_name} - {0.device.manufacturer} {0.device.model_name}".format(device.encode("utf8")))
```

and let me know if that works?

**Comment by jimbo72** [comment]
This does not work:

root@Jeedom:~# catt scan
Scanning Chromecasts...
Traceback (most recent call last):
  File "/usr/local/bin/catt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/catt/cli.py", line 290, in
main
    return cli(obj={}, default_map=readconfig())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in
__call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in
main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066,
in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in
invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in
invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/catt/cli.py", line 246, in
scan
    click.echo("{0.host} - {0.device.friendly_name} -
{0.device.manufacturer}
{0.device.model_name}".format(device.encode("utf8")))
AttributeError: 'Chromecast' object has no attribute 'encode'


2018-04-01 5:29 GMT+02:00 Stavros Korokithakis <notifications@github.com>:

**Comment by theychx** [comment]
For me, simply prepending the ```u``` unicode notation, fixes the problem (using 2.7.14).

**Comment by jimbo72** [comment]
You are right, this works like a charm:

click.echo(u"{0.host} - {0.device.friendly_name} - {0.device.manufacturer} {0.device.model_name}".format(device))

**Comment by skorokithakis** [comment]
And I'm trying to run `catt scan` and am getting a zeroconf error, just my luck today.

**Comment by skorokithakis** [comment]
Testing this, I discovered another bug that has to do with incorrect encoding in `cache.get` when the name is non-Latin. @theychx, what do you suggest we do? These are 2.7-specific bugs, but there's the 3-only code in the codebase. We can either cherry-pick that out again and do one last release, or say we don't support 2.7 any more and that people should upgrade to 3.

**Comment by theychx** [comment]
Let's just put py2 support to rest. Unlike the local file casting issue, these encoding problems can be easily worked around by the user.

**Comment by skorokithakis** [comment]
I agree. @jimbo72, I'm afraid you're just going to have to upgrade to Python 3 to solve this :/
