### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by sagism** [skorokithakis/catt#94]
Just installed (on OSX 10.13.3).
    
    % catt cast "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/bin/catt", line 11, in <module>
        sys.exit(main())
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/catt/cli.py", 
    line 380, in main
        return cli(obj={}, default_map=readconfig())
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/catt/cli.py", line 370, in readconfig
        config.read(CONFIG_PATH)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/configparser.py", line 693, in read
        for filename in filenames:
    TypeError: 'PosixPath' object is not iterable

**Comment by theychx** [comment]
Thank you for reporting this. We'll roll out a fix one of these days.

@skorokithakis 
This is caused by ```ConfigParser.read``` not taking path-like objects until py3.6.

**Comment by skorokithakis** [comment]
Ah, thanks. Can you fix or should I? I can take a look later today if not.

**Comment by theychx** [comment]
I can fix it, no problem. Does this complicate ongoing subtitles work? (excuse my low-level git-foo)

**Comment by skorokithakis** [comment]
No, just branch from dev and we'll merge back in there. I can fix any conflicts, although I don't think there will be any. The subtitles PR looks very straightforward. I think I want to release 0.7 with the subtitles, and I wonder if we can also get YouTube-dl to download them.

**Comment by theychx** [comment]
@sagism ```0.6.1``` is out, with a fix for this issue.

**Comment by skorokithakis** [comment]
It's out by accident, but yes, it's out and fixes this :P

**Comment by theychx** [comment]
> by accident

Eh?

**Comment by skorokithakis** [comment]
I ran the release with `--noop` because I wanted to add `fix:` to the commit, but it went ahead and published. Luckily everything went as it was supposed to.
