### ISSUE TITLE
Does not work on WSL (Windows 10) - Workaround Included

### ISSUE THREAD

**Issue by marcosdiez** [skorokithakis/catt#97]
Unfortunately `catt` does not work on WSL on Windows 10.

The issue is in `python-zeroconf`, a library used by `pychromecast`, which is used by `catt`.

If you don't want to wait for the fix on `python-zeroconf` to be merged, `pychormecast` to be updated to use the fixed `python-zeroconf` and `catt` to be updated to use the new version of `pychomecast`, you can simpley type 

`pip install git+https://github.com/marcosdiez/pyzeroconf.git@now_it_works_on_wsl --upgrade`

I suggest this issue to be closed whenever all these merges occur.

**Comment by skorokithakis** [comment]
Thanks for this, it's very helpful. Let's close it when we release a version that works, thank you.

**Comment by theychx** [comment]
https://github.com/jstasiak/python-zeroconf/pull/130 was merged some time ago, and is now featured in the ```0.21.1``` release.

@marcosdiez Thank you for the effort!

**Comment by marcosdiez** [comment]
Hey,
sorry to bug but...
Yes, the code got merged in `python-zeroconf`, but the new version is not explicitly being used on PyChromecast 2.3:

source: https://github.com/balloob/pychromecast/blob/2.3.0/requirements.txt#L3

So technically we should either force the use of  newer version of python-zeroconf on `catt` or keep this issue opened (since no version of PyChromecast explicitly requires `python-zeroconf` > `0.21.1`

**Comment by theychx** [comment]
And besides, I am pretty confident that ```PyChromecast``` will require ```zeroconf>=0.21.1``` in the near future, as ```zeroconf``` scrapped ```netifaces``` in favour of ```ifaddr```, which will make ```PyChromecast``` a lot easier to install.

**Comment by skorokithakis** [comment]
I agree, since `python-zeroconf` isn't our direct dependency, it'd be best if we waited for `PyChromecast` to upgrade it...

**Comment by heckler** [comment]
I see this issue has been open for a more than a year now ...

I`m running catt version 0.10.2, installed via pip on python 3.6.8 on WSL (Ubuntu 18.4.02 LTS) and catt is working just fine.

The version of zeroconf on my system is 0.23.0

I believe this issue can be closed now.

**Comment by skorokithakis** [comment]
Thank you!
