### ISSUE TITLE
Error: no devices found

### ISSUE THREAD

**Issue by zersiax** [skorokithakis/catt#98]
I am probably missing something super obvious, but I gave python permission on Windows to go through the firewall, I run catt scan ...and this is what I get back. My chromecast works fine over Chrome but catt isn't seeing it ...did I mess up?

**Comment by mdiez-modus** [comment]
On Windows, you must disable the firewall for `catt` to work.
Being more specific, on Windows 10, if you run on native windows python, the firewall must be disabled even "scan" to work. on WSL, scan works on the firewall but the rest (casting) does not.

yes, there may be a way to go around that but I did not investigate yet.

**Comment by yangwenmai** [comment]
On macOS High Sierra
When I exec `catt cast "https://www.youtube.com/watch?v=dQw4w9WgXcQ"`, It occur `Error: No devices found.`

**Comment by skorokithakis** [comment]
Is the Chromecast on the same network as the computer?

**Comment by theychx** [comment]
@zersiax @yangwenmai 
Have you been able to resolve this?
This is really not an issue with ```catt``, but rather with ```zeroconf``` on specific platforms.

**Comment by theychx** [comment]
@skorokithakis There's not really any reason to keep this issue open, and no one have responded to my follow up question.

**Comment by skorokithakis** [comment]
I would close this, except I can't get `catt` to discover any devices in my home network either :/ Let's close this and I'll try to figure out what's wrong when I'm home, but `pychromecast`'s `discover_chromecasts()` doesn't work for me, so it's probably not our issue.

**Comment by SanskarP** [comment]
Sorry to bother everyone, but I have this same issue on the Windows 10 kali Linux and I am still new to all this. Anyone have any suggestions on how to fix this?

**Comment by skorokithakis** [comment]
I've found Chromecast to be relatively flaky on my network as well. Even the YouTube app can't find the Chromecast, which indicates that this isn't a catt/pychromecast problem.

Even if it is a pychromecast issue, I'm afraid there isn't much we can do. A packet dump between pychromecast discovery and the network might be useful to post on the pychromecast issue tracker.

**Comment by joselmy-diaz** [comment]
try to update your router in old versions it does not work well
